### ISSUE TITLE
Windows 7 Support

### ISSUE THREAD

**Issue by J1Man** [elishacloud/dxwrapper#1]
Hi Elisha,

Do these wrappers work on Windows 7 Ultimate 64bit?

There is a set of dll files in the main Dxwrapper.zip archive but there are also dll files in subfolders of the zip archive (such as v0.2.1, v0.2.0b).  Which ones are the latest files?

Thanks.

**Comment by elishacloud** [comment]
Hello J1Man,

Yes.  All of these wrappers will work on Windows 7 Ultimate 64bit, as long as you are using them on a 32bit application.  They were primarily made for Windows 10 (32bit and 64bit), however there is nothing in them that would prevent them from running on Windows 7.  I ran a quick test and saw no issues.

One comment is that I just found out that they require the d3dx9_43.dll file.  To get this you need to download the DirectX End-User Runtime.  You can download it from [here](https://www.microsoft.com/en-us/download/details.aspx?id=35).

v0.2.0b and v0.2.1 are two versions of the DdrawCompat libraries which are included in these wrappers.  This only matters if you are using the DdrawCompat feature.  In most cases v0.2.1 works fine.  I only know of two games that require the v0.2.0b: Conquest Frontier Wars and RavenShield.

Thanks,

**Comment by elishacloud** [comment]
Closing issue
