### ISSUE TITLE
Gangsters Organized Crime – volume controls stop working

### ISSUE THREAD

**Issue by azat11** [elishacloud/dxwrapper#100]
After I start using this fix the volume controls aren't working anymore. Windows 7 Pro SP1.

**Comment by elishacloud** [comment]
Looks like this is related to #69 and #70

**Comment by elishacloud** [comment]
I just posted an update patch that should address this issue.  You can see the update here:  [Gangsters Organized Crime patch](https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime)

**Comment by azat11** [comment]
> I just posted an update patch that should address this issue. You can see the update here: [Gangsters Organized Crime patch](https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime)

Thank you very much!

**Comment by elishacloud** [comment]
This should be fixed with the latest update:  https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime
