### ISSUE TITLE
Hitman: Contracts

### ISSUE THREAD

**Issue by SquarePixels** [elishacloud/dxwrapper#110]
Hi,

I'm trying to play the GOG version of Hitman: Contracts but I ran into the same issues as Hitman 2: Silent Assassin (Extremely high frame rates causing in game speed to be very slow)

Used the dxwrapper fix here for Hitman 2: Silent assassin to force vsync which fixed all my issues. Was hoping for an similarly easy fix but it appears there are some issues. (If only it was as easy as forcing vsync / limiting frame rate in the Nvidia Control panel but that didn't work for both games)

Tried a fresh copy of dxwrapper using D3d8to9 as well as attempting to use the fix from Hitman 2 but looks like I'm running into some texture issues. Any help would be much appreciated!

![screen](https://user-images.githubusercontent.com/50791710/104265791-5f729000-545c-11eb-83cf-f4bd78c61756.png)

**Comment by elishacloud** [comment]
I don't have this game, but there are some recent fixes in d3d8to9.  You can try this update and see if it works.  If not I can try and look into this in the future.

Here is the latest update:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11225749/dxwrapper.zip)

**Comment by elishacloud** [comment]
Closing the issue.
