### ISSUE TITLE
Hook::HotPatch error while using the dxwrapper version of d3d8.dll with the ReShade version of d3d9.dll

### ISSUE THREAD

**Issue by Akira13641** [elishacloud/dxwrapper#112]
It's unclear to me if this is actually a "real" problem as everything appears to work correctly when using the configuration described in the issue title anyways, but I thought I would point it out just in case. Specifically, the two errors that show up in the dxwrapper log are:

`Hook::HotPatch Error: 'Direct3DCreate9' is not patch aware at addr=63509000`

and

`Hook::HotPatch Error: 'Direct3DCreate9Ex' is not patch aware at addr=635090F0`

The specific game in question is Unreal 2, which uses a Direct3D 8 renderer natively. My reason for using the dxwrapper version of d3d8.dll instead of simply the one from standalone d3d8to9 is that the dxwrapper version includes support for enabling hardware-based anti-aliasing, which is preferable to any of the post-process ReShade solutions I'd have to use otherwise.

**Comment by elishacloud** [comment]
If the game is using a Direct3D 8 renderer then you can ignore those errors.  They just mean I could not hook the Direct3D 9 APIs.  However, in this case there is no need to hook those APIs.

**Comment by Akira13641** [comment]
Ok, thanks. I'd say this is not actually an issue, then.
