### ISSUE TITLE
Forcing using anisotropic filtering in d3d9

### ISSUE THREAD

**Issue by sun1ight** [elishacloud/dxwrapper#114]
This functionality has been lacking for a long time, not everyone has the opportunity to get into the driver settings and configure filtering.
If you load DgVoodoo to activate anisotropic filtering with the second wrapper, then the load on the computer increases significantly.

**Comment by elishacloud** [comment]
Ok, try with this build.  This should enable anisotropic filtering and set the sampler state to `D3DTEXF_ANISOTROPIC`.  You will need to modify the ini file to enable the `AnisotropicFiltering` option.

Here is the updated build:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/6026947/dxwrapper.zip)

**Comment by sun1ight** [comment]
Anisotropic filtering works fine now, thanks

**Comment by mirh** [comment]
Probably stupid observation: can you force trilinear filtering ***on top of*** the anisotropic one?
I remember some UE3 game showed sensible improvements when you specified `Triliner=TRUE` and `MaxAnisotropy=16`.
