### ISSUE TITLE
ST Armada Stutter & Mouse Issue

### ISSUE THREAD

**Issue by amcghee1** [elishacloud/dxwrapper#115]
Hi there.
When using dxwrapper with Star Trek Armada 1.3, I'm getting a lot of small game stutters, audio cut outs & the mouse is laggy like it's running at 20Hz or something. If I try running at a resolution of 1024*768 the game is mostly ok, but at higher resolutions the mouse basically stops working, the game only seeming to register a half second of input every 4 seconds or so & the lag is worse. The frame rate is poor & unsteady as well.

I'm using the latest dxwrapper & I manually edited the config to match the one from the older armadafix.zip (that version wouldn't let me launch the game at all).

Are there any config settings that would get round this? I'm on W10 20H2, 16 core / 32 thread CPU.

[dxwrapper-armada.log](https://github.com/elishacloud/dxwrapper/files/6055072/dxwrapper-armada.log)

As a side note I tried DGVoodoo on another install. There the game runs perfectly for about 1.5 hrs then I get a CTD. The Armada game log shows an out of memory fatal error. Also with that method the menus are barely usable.

**Edit:**
So the cause of the stutters appears to be enabling HDR in Windows Display Settings. I can switch the issue on & off by toggling that setting. Leaving HDR off keeps the game running smoothly up to & including 4k resolution. Unfortunately this didn't completely fix the mouse or audio problems. The mouse mostly works now but cuts out every so often, feels like around 10 seconds. It's as if the mouse goes over an unreadable surface. The cursor also seems to stick at the edge of the screen sometimes. As for audio it seems perfect until there's a lot going on then it cuts out a pops a lot.

**Comment by elishacloud** [comment]
It could be related to the version of DDrawCompat I am using.  Try with the latest build here: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/6056162/dxwrapper.zip)

Also make sure that all compatibility options are disabled:

![image](https://user-images.githubusercontent.com/25625456/109405548-84489700-7926-11eb-81e5-c75758c687da.png)

**Comment by amcghee1** [comment]
Thanks for that :)
Unfortunately the newer version made no difference, the mouse still cuts out constantly. I tried a different mouse as well with no change.

I don't have any compatibility settings on.

I meant to say originally that in the game menus, both accessed from an active game & from the main menu after launching the mouse & audio is perfect.
