### ISSUE TITLE
Forced window border can't be interacted with

### ISSUE THREAD

**Issue by mirh** [elishacloud/dxwrapper#117]
I'm pretty happily using dxwrapper to start Mirror's Edge in windowed mode (`EnableWindowMode=1`), and `WindowModeBorder=1` also somewhat works nominally. 
But it has no purpose if at the end of the day I can't use it to move the window around.

**Comment by elishacloud** [comment]
I have not focused much on windowed mode.  There is definitionally more that I could do.  However, I tried with several games and when using windowed mode I could move the window around.

Just remember that if the mouse is locked into the window then you need to press alt+tab or the Window Key to get out of the window.  Then in some games the mouse cursor is hidden so you cannot see it when it is hovering over the title bar.  But if you move the mouse out of the game window to the top and then move it down just below the top of the window so it is hovering over the title you can still move the window around even though you cannot see the mouse cursor it can still move the window around.

Here is the latest build, in case it was an issue with an old build: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11226163/dxwrapper.zip)

**Comment by elishacloud** [comment]
Closing as not planned.
