### ISSUE TITLE
Improve logging & docs to allow better debugging if settings are being applied

### ISSUE THREAD

**Issue by asvitkine** [elishacloud/dxwrapper#124]
DxWrapper should log which .ini file it's applying, so it's easy to tell if it's picking up the right one.

Additionally, the documentation should mention where to expect the log file to be - right now it doesn't say - and someone trying to use this for the first time has a hard time of knowing where to look for it (if they've not ran DxWrapper successfully yet).

**Comment by elishacloud** [comment]
This will be addressed in the next update, which I hope to get out in the next week or two.  Thanks!
