### ISSUE TITLE
Easy way to compile from source

### ISSUE THREAD

**Issue by noabody** [elishacloud/dxwrapper#126]
I was curious as to the the easiest way to build this project from source and it seems to be by using the Microsoft [EWDK](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk) which can be natively mounted in Windows 10.

Navigate to that location and double-click LaunchBuildEnv.cmd

Use commands like these:

```
git clone --branch master --recursive https://github.com/elishacloud/dxwrapper.git
cd dxwrapper
msbuild /p:WindowsTargetPlatformVersion=%Version_Number%;Platform=win32;Configuration=Release /t:Clean,Build dxwrapper.sln
```

**Comment by elishacloud** [comment]
I am using Visual Studio 2022 to build.  If you have the correct components installed it should be easy to build.

**Comment by elishacloud** [comment]
Closing this as not planned.
