### ISSUE TITLE
Aargon Deluxe

### ISSUE THREAD

**Issue by davidebeatrici** [elishacloud/dxwrapper#128]
I would like to document the steps to fix Aargon Deluxe on Windows 10.

1. Extract `d3d8.dll` (from `Stub` directory), `dxwrapper.dll` and `dxwrapper.ini` into the game's directory.
2. Open `dxwrapper.ini` and set:
   - `DDrawCompat` to `1` to fix the rendering issue that manifests when the game's window is put in background and then foreground again:
     <img src="https://user-images.githubusercontent.com/5897523/118400007-27749700-b660-11eb-9b8c-454efabec331.png">
     This also fixes the partial rendering issue that I encountered on a small laptop/tablet that has scaling set to 150%:
     <img src="https://user-images.githubusercontent.com/5897523/118400197-de711280-b660-11eb-8f7f-5b9c3e29e5b5.png">
   - `DisableHighDPIScaling` to `0` to prevent the image in the launch window from being rendered incorrectly:
     <img src="https://user-images.githubusercontent.com/5897523/118400238-1415fb80-b661-11eb-8e24-1c21b894bd82.png">

**Comment by mirh** [comment]
PCGamingWiki is all ears for you.

**Comment by davidebeatrici** [comment]
I believe it should also be documented in this repository's Wiki.

**Comment by mirh** [comment]
I have never really understood much of the point in duplicating the content of issues, even considering that sooner or later they are bound the become outdated. 
A specialized wiki could have much more added value here, if it could document technically "the stuff" that Windows more and more leaves behind.

**Comment by elishacloud** [comment]
Thanks for the details.  Closing issue.
