### ISSUE TITLE
Does this work with dear IMGUI?

### ISSUE THREAD

**Issue by whiskasdietgirl** [elishacloud/dxwrapper#129]

**Comment by elishacloud** [comment]
It depends on what rednerer you are using with Dear ImGui.  There are many render engines that Dear ImGui supports, including OpenGL, Vulkan, etc.  To work with dxwrapper you will need to use the dx9 engine.  I believe that is the only engine that dxwrapper supports from list that Dear ImGui uses.

**Comment by elishacloud** [comment]
ImGui has been added to this.  Currently it only works with `dd7to9`.  But later I will port it over to the Direct3D9 wrapper so it can work with `d3d8to9` as well as Direct3D9 games.

**Comment by elishacloud** [comment]
Closing issue.
