### ISSUE TITLE
Coil Whining when using dxwrapper

### ISSUE THREAD

**Issue by rtx92** [elishacloud/dxwrapper#138]
so today i came across a strange thing  wanted to play soul reaver 2 again used dgvoodoo + dxwrapper  d3d8.dll, dinput8.dll, dxwrapper.asi, dxwrapper.dll and dxwrapper.ini. Then edited the ini and set Dinputto8 from 0 to 1 to fix the game.After a while  i noticed some screeching noises from my gpu   i closed the game the noise where gone startet the game again and the noises where back  then i noticed the pitch would change depending on what i do in the game (moving ,looking around,cutscenes)  i closed the game started some other games to test if the noises came back  nothing after that i deletet soul reaver 2  reinstalled the game this time i used only dxwrapper alone  and again screeching noises... does anybody have an idea or got similar effects on other games?

**Comment by mirh** [comment]
Yes, I also had something like that on my desktop (can't remember now the exact circumstances)
AFAICT it just depends on the kind of load you put on your hardware. 
Try to limit your framerate for instance.

**Comment by rtx92** [comment]
my framerate is always capped at 60 in the nvidia panel  and the noises only comes when using dxwrapper  and in this case the workload dont mean anything like i said i tried other games and some tools (cinebench,aida64extreme,3dmark)

**Comment by elishacloud** [comment]
Is the wining coming from your hardware or from your speaker?

**Comment by rtx92** [comment]
Hey its been a while

So  it was definetly from my 2080ti back then i didnt use anything other than bt headphones 

ive looked in getting some help on other places  made a thread on gbatemp about it  and some suggested putting blobbs of hotglue on the coil to reduce the whining but it didnt helped much  

after that i tried to cap the powerlimit of the gpu to 50% since old games dont need much power  it helped a bit the whining wasnt so loud as before 

for me it looked likethe wrapper was forcing the gpu to run always at full powerconsume

since then i build a whole new pc and switched to a 4090  and the whining stopped

**Comment by mirh** [comment]
My 2080S also whines like a madman when I launch my [old stupid benchmark](https://github.com/mirh/HDR_FP16x2) (which can easily get you north of a thousand fps). 
Though it's odd if you just fly low at 60 (conversely, what was the uncapped framerate otherwise?)
Did this happen even just already with d3d8to9 alone?

**Comment by elishacloud** [comment]
Closing issue.
