### ISSUE TITLE
Gangster Organized Crime - UnhandledExceptionFilter: exception code=3221225477 flags=0 addr=00000000

### ISSUE THREAD

**Issue by JTonyC** [elishacloud/dxwrapper#14]
Hi,

Sadly, I'm not having the same success as others on this 

1. My GFX - Nvidia Strix GTX980 
2. Editing dsound.ini with DDrawCompat = 0 - Makes the crash go away, but, same as before, no menu text 
3. Editing dsound.ini with DDrawCompat = 1 - Produces this error log: 

15748 22:36:24.159 Starting DxWrapper v1.0.2114.20 DDrawCompat v0.2.1 DxWnd v2.03.60 
15748 22:36:24.160 Windows 10 64-bit (10.0.15063) 
15748 22:36:24.160 gangsters.exe (PID:1552) 
15748 22:36:24.160 Reading config file: E:\Games\GoG Games\Gangsters\dsound.ini 
15748 22:36:24.162 Disabling High DPI Scaling... 
15748 22:36:24.162 Set exception handler 
15748 22:36:24.163 Hooking ddraw.dll APIs... 
15748 22:36:24.163 Process path: E:\Games\GoG Games\Gangsters\gangsters.exe 
15748 22:36:24.163 Loading DDrawCompat from E:\Games\GoG Games\Gangsters\DSOUND.dll 
15748 22:36:24.163 Loading dinput.dll 
15748 22:36:24.163 Loaded dinput.dll library 
15748 22:36:24.163 Loading uxtheme.dll 
15748 22:36:24.163 Loaded uxtheme.dll library 
15748 22:36:24.163 DDrawCompat loaded successfully 
15748 22:36:24.163 Loading dxwnd.dll 
15748 22:36:24.165 Loading E:\Games\GoG Games\Gangsters\DSOUND.dll 
15748 22:36:24.165 Loaded E:\Games\GoG Games\Gangsters\DSOUND.dll library 
13772 22:36:24.177 Starting fullscreen thread... 
15748 22:36:25.532 Installing DirectDraw hooks 
15748 22:36:25.587 Installing GDI hooks 
15748 22:36:25.592 Installing registry hooks 
15748 22:36:25.592 Finished installing hooks 
15748 22:36:28.731 Loading winmm.dll 
15748 22:36:28.731 Loaded winmm.dll library 
15748 22:36:28.771 Loading dwmapi.dll 
15748 22:36:28.771 Loaded dwmapi.dll library 
15748 22:36:33.444 GDI used DC cache size: 1 
15748 22:36:33.451 UnhandledExceptionFilter: exception code=3221225477 flags=0 addr=00000000 
15748 22:36:33.468 UnhandledExceptionFilter: exception code=3221225477 flags=0 addr=00000000 

4. Running the .exe from the Game directory, as Admin 
5. Compatibility mode - Windows XP (Service pack 2)

**Comment by elishacloud** [comment]
Hello Tony,

Try disabling Compatibility mode settings.  See here for how it should look:

![Compatibility](https://raw.githubusercontent.com/elishacloud/wiki-attachments/master/dxwrapper/Games/Gangsters%20Organized%20Crime/Compatibility.png)

**Comment by JTonyC** [comment]
Hiya,

Thanks for the quick reply, sadly, that’s not made a difference, dsound-gangsters.log reads the same output.

I must be missing something if it works for some and not others, but have no clue as to what that maybe.

**Comment by elishacloud** [comment]
Hello Tony, Check out the post [here](https://www.gog.com/forum/gangsters_organized_crime/broken_on_windows_10_as_well/post26).  rhaak said he solved the issue by modifying the Nvidia settings and disabling G-Sync.  You might want to try disabling G-Sync and Vsync to see if either of these help.  I suspect you may be having an issue with an Nvidia setting also.

**Comment by elishacloud** [comment]
Closing issue for now.  If you can still reproduce this with G-Sync and Vsync disabled you can reopen it.
