### ISSUE TITLE
SimCity Save Patch Windows11

### ISSUE THREAD

**Issue by SpaceBooger** [elishacloud/dxwrapper#140]
I have the patch installed for SimCity and it works great on my Windows 10 machine, but will not work on Windows 11.
When playing SimCity on Win11 it automatically closes when you try to save.
I have used the same files (exact same install) to confirm this works on Win10 but not on Win11.

**Comment by SpaceBooger** [comment]
I have also tried the patch with all compatibility settings on Windows 11 and nothing has worked.

**Comment by mirh** [comment]
"When you try to save" sounds something to do with the windows *Controlled folder access* feature.

**Comment by SpaceBooger** [comment]
When you say log file, do you mean the Windows event file, or is there another log for this patch?

**Comment by elishacloud** [comment]
There should be a file in the game folder called "dxwrapper-classic.log" or something like that.

![image](https://user-images.githubusercontent.com/25625456/149435652-65cfb1fb-6aae-4287-b6eb-d330b4fc311c.png)

**Comment by SpaceBooger** [comment]
There is no log in my folder on my Windows 11 build.
I will check my Windows 10 version tomorrow at work.

**Comment by SpaceBooger** [comment]
![Screenshot 2022-01-13 215430](https://user-images.githubusercontent.com/47699523/149443653-442dd5d0-758c-4814-aa9e-1e742a7b927c.png)

**Comment by SpaceBooger** [comment]
So the files did not produce a log on Win10, but here is the log from the same exact files on a Win10 pc:
[dxwrapper-classic.log.txt]pper v1.0.6378.21
24256 15:22:27.843 HP HP EliteDesk 800 G5 SFF   (Desktop)
24256 15:22:27.843 HP 8592 KBC Version 08.98.00 (Desktop)
24256 15:22:27.843 Intel(R) UHD Graphics 630
24256 15:22:27.846 Windows 10 Enterprise 64-bit (10.0.19041)
24256 15:22:27.846 "CLASSIC.EXE" (PID:18640)
24256 15:22:27.853 Utils::WriteMemory::WriteMemory Writing bytes to memory...
24256 15:22:27.853 Disabling High DPI Scaling...
24256 15:22:27.853 Loaded library: user32.dll
24256 15:22:27.853 Loaded library: shcore.dll
24256 15:22:27.853 Set exception handler
24256 15:22:27.853 Loaded library: kernel32.dll
24256 15:22:27.853 Finished setting exception handler
24256 15:22:27.853 DxWrapper loaded!
24256 15:22:55.784 Quiting DxWrapper
24256 15:22:55.784 Unloading libraries...
24256 15:22:55.784 Unloading exception handlers
24256 15:22:55.784 Reseting screen resolution
24256 15:22:55.925 Reseting font smoothing
24256 15:22:55.927 DxWrapper terminated!

**Comment by elishacloud** [comment]
> There is no log in my folder on my Windows 11 build.

This mean that dxwrapper is not loading on that system.  You need to get dxwrapper to load before it will work.  There could be a few possible fixes:

1. Try disabling all compatibility options.
2. Try running the "CLASSIC.EXE" file directly from the folder in the screenshot above.
3. Try renaming the "dwmapi.dll" to something else.  These are possible names [here](https://github.com/elishacloud/dxwrapper#supported-dlls).

**Comment by mirh** [comment]
What if you run the exe as admin?

**Comment by SpaceBooger** [comment]
Running as admin did not work, but renaming it to "winmm.dll" worked.
Aweseome. Thanks!

**Comment by Instandhaltung** [comment]
> Try renaming the "dwmapi.dll" to something else. These are possible names [here](https://github.com/elishacloud/dxwrapper#supported-dlls). Maybe try "winmm.dll" ...

This helped me as well! Important information

**Comment by elishacloud** [comment]
Closing issue.  You can reopen it is you still have issues.
