### ISSUE TITLE
Using ReShade and dxwrapper at the same time?

### ISSUE THREAD

**Issue by softsoundd** [elishacloud/dxwrapper#143]
Is there a way this can be achieved? You cannot use both dll's in the same folder or they are overwritten

**Comment by mirh** [comment]
You can name dxwrapper dll tens of different ways
https://github.com/elishacloud/dxwrapper/wiki/Configuration#general

**Comment by softsoundd** [comment]
Unfortunately for Mirror's Edge, using a name other than d3d9 doesn't work - dxwrapper just doesn't load (reshade works fine though).

**Comment by softsoundd** [comment]
Actually, turns out ReShade's dll can be renamed. By then loading the renamed dll in the ini config, this fixed the issue
