### ISSUE TITLE
Micro Stutters

### ISSUE THREAD

**Issue by Mitradis** [elishacloud/dxwrapper#145]
Its not issue this project. Micro Stutters - small jerks of frame.
Some games on modern system, or just with a combination hardware\windows\drivers, have Micro Stutters (sometimes they are not at all micro). I ran into this in some old games (need for speed hot pursuit 2, world of warcraft 1.12.1, warcraft 3 1.26a etc). This problem in these games, I could not fix anything. So I decided to write, perhaps you know how such problems can be analyzed and solutions sought. I've tried different wrappers with different options, but they dont helping.

**Comment by mirh** [comment]
That's not something with the rendering pipeline to fix (except perhaps the infamous shader compilation problem of UE4 games). 
https://www.pcgamingwiki.com/wiki/Talk:Troubleshooting_guide/Display_and_visual_problems

**Comment by Mitradis** [comment]
if i have normal DPC and not have any issue in other games. Im just trying to figure out what the problem is with some old games.  What do they not like? DPC? Windows? Network drivers? I have i512600 32gb ram that they are not enough.

**Comment by mirh** [comment]
If your DPC is low, then it's not DPC to cause your problems. It seems self-evident. 
Meanwhile people with shitty DPC are going to have a bad time. 

Then, network drivers could be a [culprit](https://www.pcgamingwiki.com/wiki/Windows#Microstuttering_in_Multiplayer_games) too. Or perhaps older games don't play nice with fullscreen optimizations. 
What happens if you use dgvoodoo2 (besides the way lower performance)?

**Comment by Mitradis** [comment]
i try many wrappers for these games. No one help. I tried different compatibility tools too.

**Comment by mirh** [comment]
I'm sure using dgvoodoo2 with specialK to force flip mode isn't something you tried. 
But alas I'm skeptical that could help by now. 
How about mentioning your specs for starters?

**Comment by Mitradis** [comment]
specialK not help.
Intel Core i5 12600, 3300 MHz (12 x 275)
Gigabyte B660 DS3H DDR4
DIMM2: AMD R9S416G3206U2S (16-18-18-39 @ 1600 МГц)
NVIDIA GeForce GTX 1060 6GB (6 ГБ)

**Comment by Mitradis** [comment]
https://youtu.be/wgmNtlj_qMs

**Comment by mirh** [comment]
A frametime graph wouldn't have hurt. 
Anyhow, well, I have just generic advices for the moment. 
Did you try to boot without anything else running? (msconfig > diagnostic boot)
Also in the bios try to enable only the P-cores, and toggle whatever HPET option you have atm.

**Comment by mirh** [comment]
I asked you to test diagnostic boot (to be sure nothing else is interfering), HPET and P-cores. Even hyper-threading and USB polling rate now that I think to it. 
All of that has effects that are immensely application specific. 
If you have better ideas you are free to diagnose alone.
