### ISSUE TITLE
Star Trek Armada 1 keyboard/mouse no response after mission starts if STintro.bik exists

### ISSUE THREAD

**Issue by yochenhsieh** [elishacloud/dxwrapper#149]
Windows 10 21H2 
nvidia GTX 1660 super, driver 512.95
Armada is retail CD version, updated to 1.3
dxwrapper version: v1.0.6542.21
dxwrapper.ini: [dxwrapper.txt](https://github.com/elishacloud/dxwrapper/files/8857805/dxwrapper.txt)

I love the intro so I put STintro.bik in animations folder and used a no-cd fix.
Problem:
If no STintro.bik in animations folder, everything works.
If STintro.bik is in animations folder, after starting any mission, keyboard and mouse have no response.

This is log when STintro.bik exists:
[dxwrapper-armada-has-intro.log](https://github.com/elishacloud/dxwrapper/files/8857795/dxwrapper-armada-has-intro.log)
I had to kill game process using task manager since mouse and keyboard were not working.

This is log when STintro.bik removed:
[dxwrapper-armada-no-intro.log](https://github.com/elishacloud/dxwrapper/files/8857765/dxwrapper-armada-no-intro.log)
Because mouse/keyboard works so I am able to exit game normally.

**Comment by mirh** [comment]
Nothing seemed wrong [here](https://github.com/elishacloud/dxwrapper/wiki/Star-Trek-Armada-1)...
People also reported it good with [dgVoodoo](https://www.vogons.org/viewtopic.php?f=59&t=54270).

**Comment by yochenhsieh** [comment]
This: https://github.com/elishacloud/dxwrapper/wiki/Star-Trek-Armada-1
keyboard/mouse no response since intro starts. Also cannot use keyboard/mouse at main menu. 

dgvoodoo2: 
Menus can't be full screen. Menu animations won't play. Also cannot use keyboard/mouse after mission starts.

**Comment by yochenhsieh** [comment]
I think I have some clue...
In Windows 10 and when STIntro.bik exists. after mission starts the window focus is on something else(?). The trick is, if I ALT-TAB change focus to desktop and change back to Armada, mouse and keyboard are working again.

I don't know if any settings in dxwrapper is related to this behavior, or if it's fixable.

**Comment by elishacloud** [comment]
I just posted an update patch that should address this issue.  You can see the update here:  [Star Trek Armada 1 patch](https://github.com/elishacloud/dxwrapper/wiki/Star-Trek-Armada-1)

**Comment by yochenhsieh** [comment]
For current version: (file date 2023-04-14)
Win10: Once intro starts, mouse and keyboard are not responsive. cannot click or press Esc to leave intro. At main menu, I cannot click anything. Have to alt-tab to leave game.
Win7&11: Works fine with intro.

**Comment by elishacloud** [comment]
That is weird.  It works on my Windows 10.  Try disabling the following settings:

```ini
[Compatibility]
EnableDdrawWrapper         = 0

[ddraw]
ConvertToDirectDraw7       = 0
ConvertToDirect3D7         = 0
DdrawOverrideBitMode       = 0
```

**Comment by mirh** [comment]
I hope it's not too much douchey to throw out this way (I'm really struggling to find the right amount of time for all these issues)
But after just having replied to #177, I think you really should add flip/present mode info to the logs (if it can help I believe both presentmon and specialk use ETW, but idk really)

**Comment by yochenhsieh** [comment]
Tried those settings and now it behaves like previous version. keyboard/mouse no response after mission starts.
[dxwrapper-armada.log](https://github.com/elishacloud/dxwrapper/files/11240915/dxwrapper-armada.log)
Attached log, hope it helps.

**Comment by elishacloud** [comment]
I am guessing you might have a zorder issue with your windows.  That could be why an alt+tab works, because it resets the zorder.  I disabled some items to see if that helps.

Testing build:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11267474/dxwrapper.zip)

If this still doesn't work then try disabling the following settings, like before:

```ini
[Compatibility]
EnableDdrawWrapper         = 0

[ddraw]
ConvertToDirectDraw7       = 0
ConvertToDirect3D7         = 0
DdrawOverrideBitMode       = 0
```

**Comment by yochenhsieh** [comment]
Really thank you for tracking this issue. I tested it:
default config - same as previous version, kb/mouse no response after a mission starts. 
disabled the settings - intro video won't play (black screen).

I tried installed Win10 on another laptop. It's old but it has intel CPU + nvidia GPU so hardware is different. I can reproduce same result on this laptop. Attached logs here.
[dxwrapper-armada-amd.log](https://github.com/elishacloud/dxwrapper/files/11274105/dxwrapper-armada-amd.log)
[dxwrapper-armada-nvidia.log](https://github.com/elishacloud/dxwrapper/files/11274106/dxwrapper-armada-nvidia.log)

**Comment by elishacloud** [comment]
It is odd because everything looks fine in your log file and I have a laptop with Intel GPU + Nvidia GPU and I am not seeing these issues.  Try with this ini file see if it makes a difference:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11274998/dxwrapper.zip)

_BTW: Are you sure you are using version 1.3 patch in the game?  It should say "1.3.0" in red writing at the bottom left had cornor of the main menu (below the Exit button) after the intro video._

**Comment by yochenhsieh** [comment]
Yes. I'm using 1.3.0. 

Same result for this ini - kb/mouse no response after a mission starts. 
I will try other setting combinations in the weekend.

**Comment by elishacloud** [comment]
Ok, try with this update.  I have implemented the menu using GDI and the actual game play using Direct3D9.

Here is the new update: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12306900/dxwrapper.zip)

**Comment by yochenhsieh** [comment]
Same as previous version, this update also very lag in game play - probably because my old netbook can't handle API conversion? (AMD A6-1450)
Log attached. Just in case: [dxwrapper-armada.log](https://github.com/elishacloud/dxwrapper/files/12328530/dxwrapper-armada.log)

**Comment by mirh** [comment]
Your potato pc can even run DXVK actually (albeit an older version).

**Comment by yochenhsieh** [comment]
Sorry, I don't have any Windows 10 PC to test this. You may close if it cannot be reproduced.

**Comment by elishacloud** [comment]
Ok, thanks.  Closing issue.
