### ISSUE TITLE
Tomb Raider 3 hangs with dd7to9 enabled

### ISSUE THREAD

**Issue by thekovic** [elishacloud/dxwrapper#150]
So I saw Tomb Raider 3 listed as a supported 3D game [here](https://github.com/elishacloud/dxwrapper/wiki/DirectDraw-to-Direct3D9-Conversion) but I've had no success getting it to work. When I enable Dd7to9 and launch the game, the process appears but I never get a window and about 5 seconds later, the process hangs, forcing me to terminate it in Task Manager. I tried enabling all the options suggested under Troubleshooting and their different combinations. I'm using the Steam install of Tomb Raider 3.

Here's a log:
[dxwrapper-tomb3 - kopie.log](https://github.com/elishacloud/dxwrapper/files/8935522/dxwrapper-tomb3.-.kopie.log)

**Comment by mirh** [comment]
Maybe that was with some of the [patches](https://www.pcgamingwiki.com/wiki/Tomb_Raider_III:_Adventures_of_Lara_Croft#Essential_improvements)?

**Comment by thekovic** [comment]
You mean the compatibility was tested with some patches? I used a completely fresh install from Steam, no additional enhancements

**Comment by eddlang** [comment]
> So I saw Tomb Raider 3 listed as a supported 3D game [here](https://github.com/elishacloud/dxwrapper/wiki/DirectDraw-to-Direct3D9-Conversion)

Uh, the support column says "none"; in fact that's for all the 3D games.

**Comment by elishacloud** [comment]
Yeah, I am working on the Direct3D functions, but today only the DirectDraw 2D functions work.  You could try enabling `DDrawCompat` instead of `Dd7to9`.

**Comment by elishacloud** [comment]
Ok. Tomb Raider 3 should be working with the latest build:  [dxwrapper.zip](https://github.com/user-attachments/files/17711178/dxwrapper.zip)

**Comment by elishacloud** [comment]
This build should fix all issues I could find with Tomb Raoder 3: [dxwrapper.zip](https://github.com/user-attachments/files/18083971/dxwrapper.zip)

**Comment by elishacloud** [comment]
This is fixed with the latest release.  You can reopen it if you are still having issues.
