### ISSUE TITLE
Nearest Neighbor rescaling

### ISSUE THREAD

**Issue by MetalSpork** [elishacloud/dxwrapper#154]
Many games have a native resolution of 800x600, and this does not rescale so well to monitors that have a 1080 resolution. 1920x1200 monitors are rare and it's even rarer to find one with decent specs.

What I would like is if there could be a nearest neighbor rescale where the pixel width looks perfect, but some pixels are vertically truncated.

**Comment by elishacloud** [comment]
Unfortunately, Nearest Neighbor ( or Point) filtering does not work correctly with this game.  There is no easy way to fix this.  It is unlikely that we will be able to do that.

With default filtering:

![Screenshot 2022-08-09 17-36-28](https://user-images.githubusercontent.com/25625456/183786193-f7e37db5-7cd2-4bae-b8dd-0b8a92c803c8.png)

With Nearest Neighbor filtering (notice the trees):

![Screenshot 2022-08-09 17-42-43](https://user-images.githubusercontent.com/25625456/183786201-96487890-7f00-4a5b-8c2b-ea8c98f766ff.png)

**Comment by nipkownix** [comment]
I think they may be talking about games in general, not just Silent Hill 2?

**Comment by elishacloud** [comment]
If you want to scale 800x600 to 1080p then I think there are two options to keep the pixel width looking perfect:

1. use interpolation
2. add pillar boxes around the picture to fill in the space around the 800x600 image

There are hardware boxes (like the RetroTink 5x Pro) that can do interpolation, but I am not aware of any good software solution for this.

**Comment by mirh** [comment]
Couldn't you (I mean, someone) tinker with magpie to achieve the same result?

**Comment by elishacloud** [comment]
I think they need/want a software solution that will convert PC games from smaller resolution to larger resolution, keeping the pixels intact.  Normally what happens is that the game runs in 800x600 and then the monitor will convert that to the native screen resolution and blur the output.

The issue with software solutions is that it needs to not only convert the screen resolution but, in most cases, it also needs to adjust the mouse movement, which, incidentally can be quite tricky.

dxwrapper does have the ability to add pillar boxes to some old games, but cannot do the sharp interpolation nor does it correct any mouse movements.

I suppose if you got a hardware device that would just pass through 1080p but do sharp interpolation of resolution smaller than 1080p that would work also.  But I am not aware of any device that does that today.  The OSSC Pro is supposed to do that, but it is not out yet.

**Comment by mirh** [comment]
> I think they need/want a software solution that will convert PC games from smaller resolution to larger resolution, keeping the pixels intact. 

Yes, I get that. But isn't that integer scaling, putting aside whatever the odd request of cutting some pixels?
Modern amd and nvidia drivers also ship it (but they aren't customizable, so that's why I proposed the software alternative)

> Normally what happens is that the game runs in 800x600 and then the monitor will convert that to the native screen resolution and blur the output.

Aktually, I believe in 2022 the default if for either windows or the GPU to take care of the scaling part. 
So that you don't see the black screen involved with switching mode.

**Comment by elishacloud** [comment]
> But isn't that integer scaling, putting aside whatever the odd request of cutting some pixels?

You can't do integer scaling from 800x600 to 1080.  It would just scale it 1:1, which is not scaling at all.

> I believe in 2022 the default if for either windows or the GPU to take care of the scaling part.

True.  Some GPUs will do scaling for this and supports sharp scaling.  My Nvidia card can do this in the Nvidia Control Panel.  Good point.

**Comment by mirh** [comment]
> You can't do integer scaling from 800x600 to 1080. It would just scale it 1:1, which is not scaling at all.

Damn, the idiot ball hit me hard. Now everything makes sense. 
Still.. I feel like this would be way less effort to add to magpie, than here. 

The most difficult thing would be probably just to add some hotkey to adjust the cutting position/margin.

**Comment by elishacloud** [comment]
> I'm admittedly a little confused as to why Silent Hill 2 came up.

Sorry I got confused on which thread I was on.  I did a lot of testing for nearest neighbor filtering for Silent Hill 2.

> What I would like is if there could be a nearest neighbor rescale where the pixel width looks perfect, but some pixels are vertically truncated.

Unfortunalty this would not be easy to do for Direct3D, Direct3D8 or Direct3D9 games.   However, by default, dxwrapper does nearest neighbor filtering for games using `Dd7to9`.

If the game is using DirectDraw and `Dd7to9` works for the game you could set the following for games native resolution of 800x600.  This will clip 60 pixels, 30 from the top and 30 from the bottom.

```ini
[Compatibility]
Dd7to9                     = 1

[Dd7to9]
DdrawClippedWidth          = 800
DdrawClippedHeight         = 540
DdrawOverrideWidth         = 1920
DdrawOverrideHeight        = 1080
DdrawIntegerScalingClamp   = 1
DdrawMaintainAspectRatio   = 1
```

**Comment by elishacloud** [comment]
> Scaling like how it's done on the left is what he's requesting, but dxwrapper only does scaling like how it's done on the right.

dxwrapper does not scale it that way.  That scaling is normally done by the video card or monitor.  dxwrapper just outputs at the resolution of the game and the video card/monitor will scale it to fit the resolution of the monitor, usually making it look like some kind of bilinear scaling.

There is only one option in dxwrapper to allow it to scale DirectDraw games.  In this mode it does Nearest Neighbor scaling (a.k.a. [Point Filtering](https://learn.microsoft.com/en-us/windows/win32/direct3d9/d3dtexturefiltertype#d3dtexf_point)), as you can see [here](https://github.com/elishacloud/dxwrapper/blob/1b5b7fcc9201df8c0b35aa4f93779a2732d6e2f9/ddraw/IDirectDrawSurfaceX.cpp#L3924).  I explain how to do this scaling in dxwrapper in the comment [above](https://github.com/elishacloud/dxwrapper/issues/154#issuecomment-1374620627).  However, if you are not using a DirectDraw game then dxwrapper does not do any scaling at all.

_Note:  It is a lot of work for me to add scaling to 3D games.  But if I ever do I will make options for Nearest Neighbor, Bilinear and others._

**Comment by elishacloud** [comment]
> Doesn't that only work if you want an exact 1:1 pixel rescale? I'd certainly like it if you could make it possible to rescale a DirectDraw game like this:

dxwrapper can do that.  Just enable the following options:

```ini
Dd7to9                     = 1
DdrawOverrideWidth         = 1920
DdrawOverrideHeight        = 1080
```

Here is a screenshot of Diablo 1, which uses DirectDraw.  Notice how the screen is stretched, but it is still nearest neighbor (click on it to see the full image):

![image](https://user-images.githubusercontent.com/25625456/230681794-d6452761-d272-4fd6-b570-8f9dc946cbc0.png)

**Comment by elishacloud** [comment]
Closing issue.  If there are more questions you can reopen it.
