### ISSUE TITLE
Wargames graphics fix not working

### ISSUE THREAD

**Issue by Panis684** [elishacloud/dxwrapper#155]
I read [this topic](https://github.com/elishacloud/dxwrapper/issues/142) and hope you could help me. The game crashes the moment I let a hacker/agent work in the command center.
[dxwrapper-wargames.log](https://github.com/elishacloud/dxwrapper/files/9310446/dxwrapper-wargames.log)

Your fix made it possible for me to reply a golden oldie. Thank you for your great work, I hope you'll be able to help me.
[WarGames.zip](https://github.com/elishacloud/dxwrapper/files/9310468/WarGames.zip)

**Comment by elishacloud** [comment]
Ok, try this update:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/9433974/dxwrapper.zip)

**Comment by Panis684** [comment]
Thankj you very much.

**Comment by elishacloud** [comment]
I should also mention that I added a feature in that build to remove the scanlines.  If you don't like that you can disable the setting in the dxwrapper.ini file called:  `DdrawRemoveScanlines`
