### ISSUE TITLE
Creatures 2 Crashes when Importing/Exporting Creatures

### ISSUE THREAD

**Issue by C-Rex1** [elishacloud/dxwrapper#158]
Here's the log:

_10628 11:12:07.069 Starting DxWrapper v1.0.6542.21
10628 11:12:07.069 Running from: E:\Users\Daniel's Files\Documents\Creatures\Creatures 2\dxwrapper.dll
10628 11:12:07.069 Reading config file: E:\Users\Daniel's Files\Documents\Creatures\Creatures 2\dxwrapper.ini
10628 11:12:07.069 ASUSTeK COMPUTER INC. PRIME B450M-K Rev X.0x (Desktop)
10628 11:12:07.069 NVIDIA GeForce RTX 3070
10628 11:12:07.070 Windows 10 Home 64-bit (10.0.19041)
10628 11:12:07.070 "creatures2.exe" (PID:4784)
10628 11:12:07.075 Environment variable __COMPAT_LAYER = "ElevateCreateProcess 16BitColor"
10628 11:12:07.075 Disabling High DPI Scaling...
10628 11:12:07.075 Loaded library: user32.dll
10628 11:12:07.075 Loaded library: shcore.dll
10628 11:12:07.076 Enabling dinputto8 wrapper
10628 11:12:07.076 Loading 'dinput.dll'...
10628 11:12:07.076 Loaded library: C:\Windows\system32\dinput.dll
10628 11:12:07.076 Hooking dinput.dll APIs...
10628 11:12:07.076 Enabling dinput8 wrapper
10628 11:12:07.076 Loading 'dinput8.dll'...
10628 11:12:07.077 Loaded library: C:\Windows\system32\dinput8.dll
10628 11:12:07.077 Loading 'ddraw.dll'...
10628 11:12:07.077 Hooking ddraw.dll APIs...
10628 11:12:07.077 Enabling ddraw wrapper
10628 11:12:07.077 Enabling d3d9 wrapper
10628 11:12:07.077 Loading 'd3d9.dll'...
10628 11:12:07.079 Loaded library: C:\Windows\system32\d3d9.dll
10628 11:12:07.079 Loaded library: gdi32.dll
10628 11:12:07.079 DxWrapper loaded!
10628 11:12:07.247 dd_DirectDrawCreate
10628 11:12:07.247 dd_DirectDrawCreateEx
10628 11:12:07.247 Redirecting 'DirectDrawCreate' IID_IDirectDraw to --> 'Direct3DCreate9'
10628 11:12:07.247 Creating interface m_IDirectDrawX::m_IDirectDrawX (0069F710) converting interface from v1 to v9
10628 11:12:07.247 d9_Direct3DCreate9
10628 11:12:07.247 Redirecting 'Direct3DCreate9' ...
10628 11:12:07.271 Creating interface m_IDirect3D9Ex::m_IDirect3D9Ex (006B2398)
10628 11:12:07.271 m_IDirectDrawX::CreateSurface2 Warning: MipMap not Implemented.
10628 11:12:07.271 Creating interface m_IDirectDrawSurfaceX::m_IDirectDrawSurfaceX (06223038) converting interface from v1 to v9
10628 11:12:07.271 Creating interface m_IDirectDrawClipper::m_IDirectDrawClipper (006616D8)
10628 11:12:07.271 m_IDirectDrawX::CreateSurface2 Warning: MipMap not Implemented.
10628 11:12:07.271 Creating interface m_IDirectDrawSurfaceX::m_IDirectDrawSurfaceX (06223228) converting interface from v1 to v9
10628 11:12:07.271 m_IDirectDrawX::CreateSurface2 Warning: MipMap not Implemented.
10628 11:12:07.271 Creating interface m_IDirectDrawSurfaceX::m_IDirectDrawSurfaceX (06223418) converting interface from v1 to v9
10628 11:12:07.271 m_IDirectDrawX::CreateSurface2 Warning: MipMap not Implemented.
10628 11:12:07.345 Creating interface m_IDirect3DDevice9Ex::InitDirect3DDevice (062044F8)
10628 11:12:07.346 Creating interface m_IDirect3DTexture9::m_IDirect3DTexture9 (063D9388)
10628 11:12:07.362 m_IDirectDrawSurfaceX::~m_IDirectDrawSurfaceX (06223228) deleting interface!
10628 11:12:07.362 Creating interface m_IDirect3DTexture9::m_IDirect3DTexture9 (063D91F0)
10628 11:12:07.365 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:07.365 Creating interface m_IDirect3DTexture9::m_IDirect3DTexture9 (063D9268)
10628 11:12:07.390 m_IDirectDrawSurfaceX::~m_IDirectDrawSurfaceX (06223228) deleting interface!
10628 11:12:07.400 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:07.492 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:07.506 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:07.562 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:07.662 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:07.762 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:07.863 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:07.962 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:08.062 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:08.162 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:08.262 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:08.362 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:08.462 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:08.562 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:08.662 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:08.762 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:08.862 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:08.963 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:09.062 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:09.162 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:09.262 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:09.362 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:09.462 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:09.562 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:09.662 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:09.670 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:09.762 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:09.862 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:09.962 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:10.062 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:10.162 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:10.262 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:10.398 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:10.462 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:10.562 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:10.662 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:10.762 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:10.862 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:10.962 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:11.062 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8
10628 11:12:11.244 m_IDirectDrawSurfaceX::Blt Error: could not find source surface! 0x007024F8_

All .exe files are set to run in 16-bit apart from launcher.exe and start.exe.

**Comment by C-Rex1** [comment]
Anyone?

**Comment by elishacloud** [comment]
Here is a fix for this issue.  It is now using Direct3D9 rather than GDI:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12488798/dxwrapper.zip)

**Comment by elishacloud** [comment]
This issue should be fixed in the latest release:  https://github.com/elishacloud/dxwrapper/wiki/Creatures-2:-The-Albian-Years
