### ISSUE TITLE
can't get LoadCustomDllPath to work

### ISSUE THREAD

**Issue by ghost** [elishacloud/dxwrapper#162]
i would like to use dgvoodoo's d3d9.dll and another d3d9.dll at the same time but can only get one to work.

i've put dgvooodoo in the realdllpath and the other in the LoadCustomDllPath but the second dll is ignored.

is there a special method to get LoadCustomDllPath to work?

the other wrapper is helixmod for disabling game shaders.

game is soldier of fortune 3. need dgvoodoo for vsync and framerate cap. and the other wrapper to make the graphics less blurry.

**Comment by elishacloud** [comment]
@ghost, please see this comment here:  https://github.com/elishacloud/dxwrapper/issues/134#issuecomment-1236024653

If you still have questions after that let me know.

**Comment by mirh** [comment]
I'm afraid this account won't be back

**Comment by elishacloud** [comment]
Ok, closing the issue.
