### ISSUE TITLE
Question about leaving the game on (Without Pause) for Multitasking

### ISSUE THREAD

**Issue by toibry** [elishacloud/dxwrapper#163]
Hi,

I tried all the options for the game in question (Prince of Qin), I have only these options enabled Dd7to9, EnableWindowMode. The result is that now I fixed the zoom problem in the game, and I can have a clear peek in the game window from the Taskbar in the windows 10 but, the game will pause and I rally want to pass that so that the game even after loosing focus, it will still work in the background.

Is there any hack for this? 

Thanks
[dxwrapper.txt](https://github.com/elishacloud/dxwrapper/files/10050805/dxwrapper.txt)
![Untitled](https://user-images.githubusercontent.com/42876415/202928937-17b42c0b-25b7-494d-b6e0-07d3739370a5.jpg)

**Comment by toibry** [comment]
I would like also to add that either a solution to make the game working in the background all the time even after losing focus or, having the game window opened all the time on one of the screens, means I can still open another window for any other app and the game window will never minimized to the Taskbar.

**Comment by toibry** [comment]
Update: By enabling Dd7to9, EnableWindowMode, and FullScreen, I was able to force the game window to stay in one screen and play a movie on another for example, or surfing the net using only mouse input not keyboard.

When I try to input any by keyboard the game window will not allow it forcing the game comeback quickly after I try to select an empty space where I should write any, in another means also clicking the mouse will cause the game window calls back to top of the screen with every click.

**Comment by toibry** [comment]
Update: The work around I found for this using DXWnd open source DX wrapper is enabling (Do not notify on task switch) but again this software has not profile settings for the game and when I play using default setting the game will hang when trying to save a game or delete a saved game.

Another wrapper is (3D Analyze) is using (Disable State Switch).

**Comment by toibry** [comment]
Update: Found this related tweak that works only for steam games I assume (RequireFocusToUpdate=false)

**Comment by elishacloud** [comment]
Yes.  dxwrapper does not have very good support for adding windowed mode to a game that does not support it.  There is a lot that needs to be do for that.  It seems like you found a workaround.  If not you could try [cnc-ddraw](https://github.com/FunkyFr3sh/cnc-ddraw).

**Comment by elishacloud** [comment]
Closing this issue.
