### ISSUE TITLE
Change window position?

### ISSUE THREAD

**Issue by thekovic** [elishacloud/dxwrapper#169]
I'm using `D3d8to9=1`, `EnableWindowMode=1`, and `WindowModeBorder=1` to force a game to windowed mode (the game in particular is Indiana Jones and the Emperor's Tomb). Everything works great, however, I'm not able to move the game window around the desktop. If I alt+tab to attempt to lose the focus from the window in order to be able to grab it with my mouse on the desktop, the game window disappears completely instead. It reappears when I alt+tab back into the game (into focus). It would be great if either the window didn't disappear (so that I could grab it in the desktop context) or if I could set the position of the window in the configuration file.

**Comment by elishacloud** [comment]
Related to Issue #117

**Comment by elishacloud** [comment]
Closing issue as duplicate.
