### ISSUE TITLE
Status of DxWrapper on ARM hardware (through an x86 emulator)

### ISSUE THREAD

**Issue by lorn10** [elishacloud/dxwrapper#171]
Hi all

Here follows a short question about the ARM compatibility of DxWrapper via x86 emulation.

Exist there any explicit shortcomings / caveats (despite the performance impact) when DxWrapper is used on ARM hardware in an x86 emulator?

This topic is of special interest for example here: [Mesa - Current status of Gallium Nine on Panfrost](https://gitlab.freedesktop.org/mesa/mesa/-/issues/8293).

**Comment by elishacloud** [comment]
I am not aware of any limitations of using DxWrapper on ARM hardware via an x86 emulator.  This should work with no issues.

**Comment by mirh** [comment]
If any, the nicer thing would be being able to compile this natively for arm. 
(even though it's kinda the can of worms when the architecture goes hand in hand with drivers subpar in their turn)

**Comment by elishacloud** [comment]
If I recompiled it for ARM then it would only work on legacy games that were also recompiled for ARM.  However, I am not even sure if the OS running on ARM even has all the ddraw and other APIs needed for DxWrapper or legacy games...

**Comment by lorn10** [comment]
Okay, many thanks for the information.

So DxWrapper _should_ effectively work also in a x86 emulation environment. :+1:

**Comment by lorn10** [comment]
A short addition. It was mentioned at the above Mesa page that the underlying problem in the affected ARM test environment is most likely that DxWrapper doesn't support at the moment any legacy Direct3D "forwarding". So this may become better when that support will be added.

However, but maybe we will see at some point also a native **Gallium** implementation of the legacy DirectDraw API. That would be awesome nice. :wink:
