### ISSUE TITLE
Question: Support Dx9 to Dx10/11

### ISSUE THREAD

**Issue by palmerj** [elishacloud/dxwrapper#179]
I'm a macos user, and love playing old fighting games which are dx9 via wine. Would you be open to support translation from dx9 to dx10 or 11? The reason being is Dx9 support on wine is very slow but dx10 and dx11 is fast and have translations to the underlying metal API.

**Comment by elishacloud** [comment]
I don't plan to do this.  I am currently only working on DirectX from 9 and older.  However, there are tools that convert from Dx9, Dx10 and Dx11 to Vulcan, which should run good under Wine.  The project is called [dxvk](https://github.com/doitsujin/dxvk).
