### ISSUE TITLE
Cannot open include file: 'detours.h': No such file or directory

### ISSUE THREAD

**Issue by LethalManBoob** [elishacloud/dxwrapper#18]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'detours.h': No such file or directory	dxwrapper	C:\Users\XXX\Downloads\dxwrapper-master\DDrawCompat\Experimental\Common\Hook.cpp	11	

Maybe retargeting the solutions is causing this but I can't be blamed for having the latest version of windows sdk and visual studio so.. :(

**Comment by LethalManBoob** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	RC1015	cannot open include file 'afxres.h'.	stub	C:\Users\User\Downloads\dxwrapper-master\Stub\stub.rc	11.

Another error i get

**Comment by mirh** [comment]
Did you install the stuff mentioned [here](https://github.com/elishacloud/dxwrapper#development)?

**Comment by LethalManBoob** [comment]
I downloaded Detours Version 3.0 Build_343. What should I do with it.

Also do i need both directx sdk's when i have windows 10 sdk?

**Comment by mirh** [comment]
Yes, you absolutely need it. 
Both of them. 

> What should I do with it.

Given you miss its include file, I'd suppose add it to your include folders.

**Comment by elishacloud** [comment]
On my computer Detours is installed to `C:\Program Files (x86)\Microsoft Research\Detours Express 3.0\include`.  If you have it installed somewhere else you can change the path in Visual Studio:
1. Open the dxwrapper project in Visual Studio.
2. Click `Debug` --> `dxwrapper Properties`
3. Go to the `VC++ Directories` folder and you will see an item called `Include Directories`.  You can change the Detours path here.

Note: you will also likely need to change that path to the Directx81 files as well.  dxwrapper has dependencies on both of these.

**Comment by elishacloud** [comment]
Closing this issue since the original question is answered. You can reopen it if you still have an issue.

**Comment by mirh** [comment]
Btw, isn't detours open now? https://github.com/microsoft/detours
