### ISSUE TITLE
Dd7to9 has switched textures

### ISSUE THREAD

**Issue by dkollmann** [elishacloud/dxwrapper#180]
Hello Elisha, I am working on getting Black & White run in D3D9 mode. I had to make some specific fixes and so far I have a good start.

![image](https://user-images.githubusercontent.com/936152/235372663-3d9a6c2f-0d66-4637-91f6-10edbd24d195.png)

However, I have the issue that some textures seem to be switched. I wanted to ask if yoiu have a suggestion why this happens.

[dxwrapper-runblack.log](https://github.com/elishacloud/dxwrapper/files/11362160/dxwrapper-runblack.log)

I added the functionality to decode DirectX textures through CopySurface.

It would be great if you had a few minutes to look at some of the fixes I did. Some are really more hotfixes, but they did the trick for now.
https://github.com/elishacloud/dxwrapper/compare/master...dkollmann:dxwrapper:black_n_white

Thank you,
Daniel

**Comment by elishacloud** [comment]
Hello Daniel,

First of all, it is great to see this code working on a 3D game.  This is the furthest I have seen it on any 3D game.

I added an updated version of the code you modified into the project [here](https://github.com/elishacloud/dxwrapper/commit/9a98001a5ab849d2178ed91716ad361f7883f02e), I hope you don't mind.  This should have everything you added except the "[hotfix for rtx remix](https://github.com/elishacloud/dxwrapper/commit/7fc44ed58a8e3763d51a4accd7c68d9f4c373376)" and the "[config setting to auto create a stencil and depth buffer](https://github.com/elishacloud/dxwrapper/commit/6a58c67d78049bc1a20d5ff6c21e4e80ecc631bd)".

I'm not completely sure why the wrong texture would be shown here.  The texture code has not really been fully implemented or tested yet.  However, maybe I can point you in the right direction.

Textures are created in [QueryInterface()](https://github.com/elishacloud/dxwrapper/blob/9041444d6fcad45cecadc0b7c8e9b38ca60809e1/ddraw/IDirectDrawSurfaceX.cpp#L132-L152) if the DirectDrawSurface.  Once it is created I [attach](https://github.com/elishacloud/dxwrapper/blob/9041444d6fcad45cecadc0b7c8e9b38ca60809e1/ddraw/IDirectDrawSurfaceX.cpp#L138-L148) it to that surface.  There could be a bug with this code.

There are also two different SetTexture() functions.  One [SetTexture()](https://github.com/elishacloud/dxwrapper/blob/9041444d6fcad45cecadc0b7c8e9b38ca60809e1/ddraw/IDirect3DDeviceX.cpp#L639) for IDirect3DDevice3 and older and one [SetTexture()](https://github.com/elishacloud/dxwrapper/blob/9041444d6fcad45cecadc0b7c8e9b38ca60809e1/ddraw/IDirect3DDeviceX.cpp#L678) for IDirect3DDevice7.  This game is certainly using the one for IDirect3DDevice7.  There could be an issue with this code.

I don't have the Black & White game, but if you know where I can get a copy of it I can look into this more.

If you figure anything out here please let me know.  I'm happy for you to add any pull requests as well.

Thanks,
Elisha

**Comment by mirh** [comment]
Some ideas here maybe
https://github.com/openblack/openblack

**Comment by dkollmann** [comment]
Hello Elisha, thank you, I was hoping you could take a look.

To get the game, it is pretty easy to find if you search for a download. You basically have to follow this guide to install the latest community version:
https://forum.bwgame.net/threads/running-black-white-on-windows-10.7916/

Configure the game using Setup.exe and enable the window mode. You then have to set DdrawOverrideWidth/Height to the same settings.

But you will need to set DdrawAutoStencilFormat to D16, otherwise there is no depth rendering. So you will need your own implementation, if mine is too hacky.

Thank you again, I will merge your changes back into my version.

@mirh Thank you, I was no aware of it. This might be useful in the future.

**Comment by elishacloud** [comment]
> Configure the game using Setup.exe and enable the window mode. You then have to set DdrawOverrideWidth/Height to the same settings.

I just put a fix in that eliminates this issue.  You no longer need to set DdrawOverrideWidth/Height with this fix: 9dfaede83e7941782fd91830a3fe60e5ea4cef97

It also should get the proper window handle now because it doesn't attempt to create the d3d9 device until after SetCooperativeLevel is called.

**Comment by dkollmann** [comment]
The textures seem to be correctly assigned now.

**Comment by sharkticonnz** [comment]
Hey Team, sorry to revive an old thread how ever I too am seeing this issue on the game Grand Prix legends. When I set DdrawOverrideWidth/Height to the same resolution in game and DdrawAutoStencilFormat to D16 the black texture issue disappears. 

How do I go about implementing this fix?

'You no longer need to set DdrawOverrideWidth/Height with this fix: https://github.com/elishacloud/dxwrapper/commit/9dfaede83e7941782fd91830a3fe60e5ea4cef97'

Thanks in advance
