### ISSUE TITLE
Crash with RTX Remix due to unknown backbuffer format

### ISSUE THREAD

**Issue by dkollmann** [elishacloud/dxwrapper#186]
This change causes a crash with RTX Remix, as the backbuffer format is unknown.

https://github.com/elishacloud/dxwrapper/commit/5e8858531ee793ee36a6b032983d01930c212dfd?diff=split

**Comment by elishacloud** [comment]
Looks like this will get fixed with PR #185

**Comment by dkollmann** [comment]
I changed this with "BPP = Utils::GetBitCount(hWnd);" as suggested before and it works.
