### ISSUE TITLE
SetAppCompatData info out of date

### ISSUE THREAD

**Issue by CookiePLMonster** [elishacloud/dxwrapper#20]
According to the source:

```
* SetAppCompatData code created based on information from here:
* http://www.blitzbasic.com/Community/post.php?topic=99477&post=1202996
```

website seems to be down, however, and I can't find any proper info on SetAppCompatData anywhere else. Any pointers? I specifically wanted to see if there is any **documented** way of toggling DXMaximizedWindowedMode.

**Comment by mirh** [comment]
There isn't. 
I clearly remember jackfuste posting the screenshot of the disassembly of some dll. 
DisableMaxWindowedMode (iirc?) was it, and I guess like one'd have to be thankful if they still haven't removed it yet. 

With the help of my mighty browser history and some google-fu, I think even `forcelocknowindow forcebnowindow lockcolorkey fullscreenwithdwm disablelockemulation enableoverlays disablesurfacelocks` had something to do with the whole picture.. But that's it..

**Comment by mirh** [comment]
*FUCK YEAAH*
http://web.archive.org/web/20170418171908/http://www.blitzbasic.com/Community/posts.php?topic=99477

**Comment by elishacloud** [comment]
Thanks for the updated link!  Somehow I was not able to find the page on The Way Back Machine last time I looked.  Glad you found it.  Let me know if you need anything else here.

**Comment by elishacloud** [comment]
@CookiePLMonster, which version of DX are you trying to call `DXMaximizedWindowedMode` for?

In DX8 and DX9 there is an API added for this:

* Direct3D8EnableMaximizedWindowedModeShim()
* Direct3D9EnableMaximizedWindowedModeShim()

You can see an example of the APIs [here](https://github.com/elishacloud/DirectX-Wrappers/blob/9ba5e5d7eb9d8f8759b49a008df5e8a5c7a11fb2/d3d8/dllmain.cpp#L57-L60) and [here](https://github.com/elishacloud/DirectX-Wrappers/blob/9ba5e5d7eb9d8f8759b49a008df5e8a5c7a11fb2/d3d9/dllmain.cpp#L137-L140).

For DirectX 1-7 you can call `SetAppCompatData` using the DWORD 12, like this:
```c++
HMODULE hDDraw = LoadLibrary(_T("ddraw.dll"));
if(hDDraw)
{
    SetAppCompatDataFunc SetAppCompatData = (SetAppCompatDataFunc)GetProcAddress(hDDraw, "SetAppCompatData");
    if(SetAppCompatData)
    {
        SetAppCompatData(12, 0);
    }
    FreeLibrary(hDDraw);
}
```

For more details check out this post [here](http://web.archive.org/web/20170522041255/http://www.blitzbasic.com/Community/post.php?topic=99477&post=1281001).

**Comment by mirh** [comment]
> Somehow I was not able to find the page on The Way Back Machine last time I looked. 

No surprise. It doesn't even appear in their search tool for some reason. 
I just have "the right code to it" because I was actually the one doing the backup.

**Comment by elishacloud** [comment]
> I was actually the one doing the backup.

Wow!  Very good.

> OTOH I also found this now.

Nice!  It looks like everything that was on blitzbasic.com is now on mojolabs.nz.  I tried several different links.  You just remove the domain and the first directory and replace it with mojolabs.nz.

* So this: `www.blitzbasic.com/codearcs/codearcs.php?code=3064` becomes this: `mojolabs.nz/codearcs.php?code=3064`

* And this: `www.blitzbasic.com/Community/posts.php?topic=101428` becomes this: `mojolabs.nz/posts.php?topic=101428`

Etc...

**Comment by elishacloud** [comment]
Closing this issue since the original question is answered.  You can reopen it if you still have an issue.
