### ISSUE TITLE
Monitor Refrash rate in full screen

### ISSUE THREAD

**Issue by Mitradis** [elishacloud/dxwrapper#201]
It is possible set refrash rate (hz) for output? If need lock refresh rate to 60 for example (because game not support more) in full screen mode. To prevent frames stratters (75 with 60 fps not smooth). If not, how i can do this?

**Comment by elishacloud** [comment]
It depends on the game.  If you are using older DirectDraw/Direct3D games there is an option called `DdrawOverrideRefreshRate` that can be used for this.  This only works if the game supports `Dd7to9` or `EnableDdrawWrapper`. 

However, keep in mind that even if you override the refresh rate if the game was coded for a different refresh rate this may just cause the same screen to appear on multiple frames or it could speed up or slowdown the game play.  It will need to be tested on each game to see how it works.

**Comment by elishacloud** [comment]
Closing the issue for now.  If you still have questions about this you can reopen it.
