### ISSUE TITLE
Gangsters: Organized Crime does not start in Windows 11

### ISSUE THREAD

**Issue by Briggadoon** [elishacloud/dxwrapper#203]
Followed the instructions here: https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime

A process starts in the task manager and a log file is generated from dxwrapper but the game never starts.

**Comment by elishacloud** [comment]
Can you attache the log file to this ticket?  There may be something in there that gives me a clue as to what is happening.

**Comment by Briggadoon** [comment]
Attached. Thank you!
[dxwrapper-gangsters.log](https://github.com/elishacloud/dxwrapper/files/11671038/dxwrapper-gangsters.log)

**Comment by elishacloud** [comment]
I see a bunch of compatibility settings for this:

```log
24260 15:43:56.138 Environment variable __COMPAT_LAYER = "DWM8And16BitMitigation 8And16BitTimedPriSync 8And16BitAggregateBlts Layer_ForceDirectDrawEmulation DisableThemes Installer"
```

Try renaming `gangsters.exe` to something like `gang.exe` just to see if that helps.  The compatibility options are specific to the process name so renaming it will temporarily remove the compatibility settings.

**Comment by Briggadoon** [comment]
Same issue. Updated log file.
[dxwrapper-gang.log](https://github.com/elishacloud/dxwrapper/files/11671158/dxwrapper-gang.log)

**Comment by elishacloud** [comment]
Try adding this line to the ini file:

```ini
DisableHighDPIScaling = 0
```

**Comment by elishacloud** [comment]
Can you try disabling all of the options in the ini file that are related to `DDrawCompat`?

**Comment by Briggadoon** [comment]
Still nothing, I'm afraid.

**Comment by elishacloud** [comment]
Try using this ini file.  This is just the default settings without anything special enabled.  It should allow the game to play normal, as if dxwrapper was not there:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11680270/dxwrapper.zip)

**Comment by PonomarevAlexxander** [comment]
> Can you try disabling all of the options in the ini file that are related to `DDrawCompat`?

Sorry to interrupt, this worked for me (game starts), but it hasnt solved the problem with main menu

**Comment by elishacloud** [comment]
Thanks @PonomarevAlexxander!  The issue with the main menu is harder to fix.

**Comment by elishacloud** [comment]
Ok, try it with this update and see if it helps:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12271708/dxwrapper.zip)

**Comment by elishacloud** [comment]
This issue should be fixed with the latest release here:  https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime
