### ISSUE TITLE
[Feature] Add function to start game at specific screen coordinates

### ISSUE THREAD

**Issue by Kim2091** [elishacloud/dxwrapper#204]
It'd be amazing if dxwrapper could force games to start in a specific location on a given screen. Many of these older games hate being forced into a window, then I have to use a tool like SRWE to force it back into position every time I launch it. Thanks!

**Comment by elishacloud** [comment]
Good idea.  Let me look into this.  Should be easy to add.

**Comment by elishacloud** [comment]
Ok, I added this function in the Direct3D9 wrapper.  So this will only work in games that support `Dd7to9`, `D3d8to9` or `EnableD3d9Wrapper`.

The new options are:

```ini
SetInitialWindowPosition   = 0
InitialWindowPositionLeft  = 0
InitialWindowPositionTop   = 0
```

Here are the steps to use it:
1. You need to be using this new build below.
2. You need enable one of the following (whichever one the game supports): `Dd7to9`, `D3d8to9` or `EnableD3d9Wrapper`.
3. The game needs to be running in window mode or you need to set the `EnableWindowMode` option.
4. You need to enable `SetInitialWindowPosition`
5. You can define the initial window position with these options: `InitialWindowPositionLeft` and `InitialWindowPositionTop`

Here is the new build: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11682479/dxwrapper.zip)

**Comment by Kim2091** [comment]
That's great, thank you! I'll give it a try tonight and post back if there's any issues

**Comment by Kim2091** [comment]
It works well, no issues that I could find  🙂
