### ISSUE TITLE
Gangsters: Organized Crime Fix doesn't work for Windows 11 Pro

### ISSUE THREAD

**Issue by VynS-UwU** [elishacloud/dxwrapper#207]
Installed the fix for Gangsters to no avail. Game does not open just freezes windows until I end the process

[dxwrapper-gangsters.log](https://github.com/elishacloud/dxwrapper/files/11901382/dxwrapper-gangsters.log)

**Comment by elishacloud** [comment]
Ok, try it with this update and see if it helps:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12271708/dxwrapper.zip)

**Comment by elishacloud** [comment]
Duplicate of #203
