### ISSUE TITLE
If you can load this dll to make o2jam window mode

### ISSUE THREAD

**Issue by jcgo16** [elishacloud/dxwrapper#21]
D3dHook.dll from https://www.fileplanet.com/198137/190000/fileinfo/D3DWindower-English-version/

I wanted to make the game Window without running the Exe of the d3dwindower, hope theres a way to do it

http://o2jam.com.ph

**Comment by mirh** [comment]
You can already use [ultimate asi loader](https://github.com/ThirteenAG/Ultimate-ASI-Loader) if you are just looking to force windowed mode. 

Not sure that's really in the scope of this project.

**Comment by elishacloud** [comment]
DxWrapper can already do this.  Just add this line into the ini file:

```text
LoadCustomDllPath = D3dHook.dll
```

**Comment by jcgo16** [comment]
wow nice, thank you <3 it work the asi loader

**Comment by elishacloud** [comment]
Closing this issue since the issue has been solved.
