### ISSUE TITLE
Terrain not working

### ISSUE THREAD

**Issue by Marble1MC** [elishacloud/dxwrapper#212]
I use a PC running Windows 11 64-bit. When I downloaded the dxwrapper plugin, I found that the wrapper would not activate until I pressed “load city”, in which case the game would go slightly haywire. So, I renamed the “dwmapi.dll” file to “winmm.dll”. While that got the wrapper working in CLASSIC.EXE, the Terrain Editor’s save function is still broken. How do I fix this?

**Comment by PatrickvL** [comment]
Just a bystander here, bit what software are you talking about? Surely you don't expect people to mind read the circumstances of your report?

**Comment by Marble1MC** [comment]
SimCity Classic. Sorry, I didn't realise it was a universal page for all of elisha's repositories.

**Comment by elishacloud** [comment]
Ok, try this update.  It should work better for you:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12211335/dxwrapper.zip)

**Comment by elishacloud** [comment]
This issue should be fixed with the latest release:  https://github.com/elishacloud/dxwrapper/wiki/SimCity-Classic
