### ISSUE TITLE
Gunmetal (1998, unrelated to 2002's "Gun Metal") Timing Issues in Windows

### ISSUE THREAD

**Issue by AlbertHamik** [elishacloud/dxwrapper#214]
Gunmetal is a 1998 FPS game that was a late era MS-DOS title that is extremely demanding in emulation for MS-DOS, but also included a Windows build of the game with an opposite issue, in that it was not properly coded to account for modern fast CPUs and the timing is completely off as a result, with the game going too fast and sound cues being out of sync with ingame events among other things (certain levels made more difficult if not impossible).

To summarize what I've learned, it appears that this is not at all related to the graphics side of things and is purely a situation involving how the game process accesses the CPU timing routine, as in the sleep() function. This bug exists with the DOS version too except the scenarios in which you can pull that off are a bit harder to show off for obvious reasons. Apparently there's a small number of late era DOS games to have suffered similar coding mistakes and also wind up running incorrectly on modern CPUs as a result.

Not entirely certain if the dxwrapper project would be able to solve for such an issue. In the past and in Linux with wine I was able to mess with another wrapper from another github developer to almost get the timing right, but again that was in Linux where it seems the system calls are more predictable compared to Windows where it seems the game will randomly pick just how too fast it goes, completely ruining whatever that manual hex edit and forced vsync lock solution was.

I saw in a issue report discussion elsewhere in this repository that there was talk of "high resolution timer" stuff which I've come to understand might partially relate to this situation, though in the case of Gunmetal what it sounds like needs to happen is we ideally need to hook the timing calls to feed the game a proper timing thread where it never runs too fast or too slow, but consistently and reliably across all systems regardless of clock speeds, which is necessary for not only the singleplayer game but multiplayer as well.

**Comment by elishacloud** [comment]
I don't have the game so I cannot check.  But you can try with dxwrapper.  Here is the latest build:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12271675/dxwrapper.zip)

Just unzip this into the Gun Metal folder.  You can try with just enabling `Dd7to9` in the dxwrapper.ini file.  If the timing is still too fast you can try enabling `EnableVSync`.

**Comment by AlbertHamik** [comment]
Apologies, I forgot I had submitted this issue when I had merely been workshopping it. You can just ignore it, and also the usual vysnc hook of directx won't work for this game in any case as that's not really the best solution to this issue as I had clarified before. I think dxwrapper might be handy for this game but perhaps not in the capacity of fixing the timing issue.

**Comment by AlbertHamik** [comment]
I didn't realize I had submitted this question post until now. I was simply workshopping it as a mere contingency, and there has been some fresh exploration into the issue. dxwrapper might be of use though the timing issue will have to be solved with something more direct like what I had stated in that rough post. Is there a way to fully delete an issue? Sorry.
