### ISSUE TITLE
setup CI

### ISSUE THREAD

**Issue by Trass3r** [elishacloud/dxwrapper#215]
To make sure compiling the project doesn't depend on some local machine-specific setup.

https://github.com/elishacloud/dxwrapper/compare/master...Trass3r:dxwrapper:master#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f

See https://github.com/Trass3r/dxwrapper/actions/runs/5779138294
`d3dumddi.h` is missing.
The WDK is [installable](https://github.com/Trass3r/dxwrapper/compare/master...Trass3r:dxwrapper:ci?expand=1#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f), or might even be [installed already](https://github.com/actions/runner-images/issues/5235#issuecomment-1181599684) but it still doesn't find it.
https://github.com/Trass3r/dxwrapper/actions/runs/5784006311/job/15673863504

**Comment by elishacloud** [comment]
> The WDK is [installable](https://github.com/Trass3r/dxwrapper/compare/master...Trass3r:dxwrapper:ci?expand=1#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f), or might even be [installed already](https://github.com/actions/runner-images/issues/5235#issuecomment-1181599684) but it still doesn't find it.

I guess that both SDK and WDK are not the same versions.  You can try changing the the [SDK version](https://github.com/elishacloud/dxwrapper/blob/4bd95dd9c7301e219d6b68c72f239a2a837d5f8d/dxwrapper.vcxproj#L16) to match whatever WDK you have installed.

**Comment by elishacloud** [comment]
Thanks @Trass3r!
