### ISSUE TITLE
The surface is misaligned

### ISSUE THREAD

**Issue by mr-mugp** [elishacloud/dxwrapper#221]
Dd7to9 
![$0 Z07%~AH@AJ@$9DDAOHSA](https://github.com/elishacloud/dxwrapper/assets/143257268/8ede6617-6a53-401e-938c-7203ed8ba812)

**Comment by elishacloud** [comment]
Yes, this happens on some games when using windowed mode in the game.  Change the in-game settings to use fullscreen mode.

**Comment by mr-mugp** [comment]
https://github.com/elishacloud/dxwrapper/issues/222#issuecomment-1694434605

**Comment by mr-mugp** [comment]
Thanks for your efforts, and hope to see a fully supported window mode sooner

**Comment by elishacloud** [comment]
If the game is only using 2D DirectDraw and not Direct3D you could try enabling the following settings:

```c++
DdrawEmulateSurface = 1
DdrawWriteToGDI = 1
```

**Comment by mr-mugp** [comment]
Thanks, that's okay, but the Hook game quits, need a new hook position?

**Comment by mr-mugp** [comment]
Thanks, normal, but the hook game quit, do you need a new hook position

**Comment by mr-mugp** [comment]
Thanks, normal, but can't hook the game

**Comment by elishacloud** [comment]
You could also try setting these settings to your screen resolution:

```c++
DdrawOverridePrimaryWidth  = 0
DdrawOverridePrimaryHeight = 0
```

**Comment by mr-mugp** [comment]
OK

**Comment by mr-mugp** [comment]
Thanks, I tried it, Releases v1.0.6542.21 doesn't have this setting item?

**Comment by elishacloud** [comment]
Here is the latest release.  Try just changing the ini settings to your display resolution.  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12455757/dxwrapper.zip)

**Comment by mr-mugp** [comment]
If Gui is enabled, it will not enter d3d9.dll, and the original hook will become invalid
![image](https://github.com/elishacloud/dxwrapper/assets/143257268/ba744591-1e6c-49cc-81b8-7ee8904e2f5d)

**Comment by mr-mugp** [comment]
After turning on DdrawWriteToGDI=1, the ImGui in the DebugOverlay .cpp can also be displayed normally?

**Comment by mr-mugp** [comment]
Compiled with the 84e47b5 update, the problem is more complicated. Now I'm using 9d01079 with dxwnd.dll it's normal

**Comment by elishacloud** [comment]
Ok, try this update.  I added basic window support.  Note: when using in-game windowed mode you should enable `DdrawUseNativeResolution`.

Here is the update:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12488768/dxwrapper.zip)

**Comment by mr-mugp** [comment]
Thank you very much for your interest and continuous update
This time the game window is normal, but there are still 4 problems. 
1. After the window is minimized, the mouse moves slowly
2. When moving the game window, the ImGui of the hook does not follow the movement 
3. The mouse message received by ImGui is in the wrong position
4. The game cannot open multiple windows and will be very stuck. After closing one window, everything else is gone

This should be caused by SurfaceToGdi, 9d01079 is normal when used with dxwnd

**Comment by mr-mugp** [comment]
Thank you very much for your interest and continuous update
This time the game window is normal, but there are still 4 problems. 
1. After the window is minimized, the mouse moves slowly
2. When moving the game window, the ImGui of the hook does not follow the movement 
3. The mouse message received by ImGui is in the wrong position
4. The game cannot open multiple windows and will be very stuck. After closing one window, everything else is gone

This should be caused by SurfaceToGdi.

9d01079 is normal when used with dxwnd 
dxwrapper.ini    
Dd7to9=1

dxwnd.ini     
ver0=9
flag0=134348834
flagg0=1275068416
flagh0=20

**Comment by mr-mugp** [comment]
> 1. After the window is minimized, the mouse moves slowly
> 2. When moving the game window, the ImGui of the hook does not follow the movement
> 3. The mouse message received by ImGui is in the wrong position
> 4. The game cannot open multiple windows and will be very stuck. After closing one window, everything else is gone
> 5. When the window moves off-screen, the picture is compressed
> 
> This should be caused by SurfaceToWindows.
> 
> [9d01079](https://github.com/elishacloud/dxwrapper/commit/9d01079b47cb17289b97aa76c8a03ef4532c8b28) is normal when used with dxwnd dxwrapper.ini Dd7to9=1
> 
> dxwnd.ini ver0=9 flag0=134348834 flagg0=1275068416 flagh0=20

Thanks, 1. Problem solved

**Comment by mr-mugp** [comment]
1.The imgui window is always positioned relative to the desktop and does not follow the game movement
![3M6IVK5S@BS(2A9@}$U}QG8](https://github.com/elishacloud/dxwrapper/assets/143257268/b7217636-0d62-4d48-bc5d-66b18e180424)

2.The game moves outside the left table, and the game screen does not go outside
![CNMT18_2OC HYW%N1`4(1{2](https://github.com/elishacloud/dxwrapper/assets/143257268/247af931-e076-4a00-a0c0-8493ccbcf11c)

**Comment by elishacloud** [comment]
> 1.The imgui window is always positioned relative to the desktop and does not follow the game movement
> 2. When moving the game window, the ImGui of the hook does not follow the movement

Yes, this is because of how the game and DirectDraw works, unrelated to dxwrapper.  The game writes to the location of the surface where the window is located.  So if you move the window then the game writes to the surface in a different location.

I can fix this by emulating the surface and then always writing to the real surface in the upper right hand corner of the surface.  That is probably the right way to solve this issue.

> 3. The mouse message received by ImGui is in the wrong position

This is related to the issue above.  When I solve that one it should solve this one.

> 4. The game cannot open multiple windows and will be very stuck. After closing one window, everything else is gone

Yes, dxwrapper always assumes that there is only one game window.  This won't be solved very soon.

> 5. When the window moves off-screen, the picture is compressed

This is probably something I am doing wrong.  I will need to look into this more.

**Comment by mr-mugp** [comment]
Thank you very much, about point 4, it's already no problem, case DLL_PROCESS_DETACH:, causing other windows to crash, I'll just comment it out

**Comment by elishacloud** [comment]
> case DLL_PROCESS_DETACH:, causing other windows to crash

Can you tell me which line(s) is causing this?  Also, try adding this line to the ini file `ResetScreenRes = 0`.

**Comment by elishacloud** [comment]
The latest build should fix most of these issues.  Here is the build:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12532762/dxwrapper.zip)

**Comment by mr-mugp** [comment]
It has been tested, very good, thank you very much for your efforts,

**Comment by elishacloud** [comment]
Ok, great.  Let me know if there are any issues left here.

**Comment by elishacloud** [comment]
This issue is fixed with the latest release.
