### ISSUE TITLE
Wargames low FPS issue

### ISSUE THREAD

**Issue by NuisanceRFB** [elishacloud/dxwrapper#227]
Having some trouble with getting Wargames to run smoothly 
Alot of the functions like the main menu, briefing screen, scrolling the map and selecting units in game is jerky and slow.
Running it with EnableWindowMode and WindowModeBorder has much better results, but the in game mouse will only show while the windows mouse is in the top left corner. playing this way by moving the window into the corner or expanding the window does make it better, but its out of sync with the ingame buttons and units 

![out of sync 1](https://github.com/elishacloud/dxwrapper/assets/416974/6d42def6-1365-4cec-89e0-69c7a872354f)
![out of sync 2](https://github.com/elishacloud/dxwrapper/assets/416974/d1f27798-fd44-42e4-8f6b-c9a665679ad2)

**Comment by elishacloud** [comment]
You could try disabling vsync or enabling fullscreen windowed mode.

**Comment by elishacloud** [comment]
I think this game does best at 30FPS, because that is how it was expected to run.  Try with this latest build, this has some new features to allow setting the FPS timer better:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12689136/dxwrapper.zip)

**Comment by NuisanceRFB** [comment]
Sweet, using the new Dxwrapper sorted it out mint. 
weird though as I installed the same build from the main wargames page onto my main computer and had zero issues,

**Comment by Mitradis** [comment]
@elishacloud ty, i try use this for "the battle for middle-earth" and it work good. This game have 30 fps cap too.

**Comment by Mitradis** [comment]
30 FPS problem have next games:  the battle for middle earth\tiberian wars\red alert 3. It is possible make image more smoother for this games?

**Comment by Mitradis** [comment]
WoW! i just try capture this shit on phone and see this:
![20230926_203842](https://github.com/elishacloud/dxwrapper/assets/21084600/6bcc05f0-96ab-4946-b0f8-71dd1099a806)
![20230926_203847](https://github.com/elishacloud/dxwrapper/assets/21084600/2eb6e9e1-b519-48e4-9705-f5b1cd4360b7)
![20230926_203852](https://github.com/elishacloud/dxwrapper/assets/21084600/2c95f068-4c36-430b-8468-95bbb4d562c0)
![20230926_203855](https://github.com/elishacloud/dxwrapper/assets/21084600/8af63f4b-8de0-4e82-887b-5fc6ecadadab)
![20230926_203859](https://github.com/elishacloud/dxwrapper/assets/21084600/a6a336a7-aa39-47e4-beaf-333aa3508633)

**Comment by Mitradis** [comment]
whats happening?

**Comment by elishacloud** [comment]
Can you upload the log files?  Is this a 3D game?

**Comment by Mitradis** [comment]
This "the battle for middle earth".

**Comment by Mitradis** [comment]
GTA Vice City render 30 fps (as say all programs), but have smooth image. How it work?

**Comment by Mitradis** [comment]
@elishacloud This basic TFT monitor problem. I want to offer this solution to the problem. The essence of the problem: 2 frames are output with a delay of 33ms (for 60hz with 30FPS). So we need to reduce the frame output time, but how can we know the future frame? We don't need to know this. When rendering a new frame, we combine it with the previous one and first display an intermediate frame and only then a new frame. Yes, we will get a delay of 1 frame, I don’t think a person is able to feel it. It is possible?

**Comment by elishacloud** [comment]
Thanks for the logs.  Did you intend to use the debug build for this?  That build is a lot slower.  Here is the latest build, it should be a lot faster:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12779750/dxwrapper.zip)

As far as a delay to reduce the FPS of a game, I just added that to dxwrapper a couple of weeks ago.  It is called `LimitPerFrameFPS`.  It can precisely limit the frame rate based on a high performance timer to exactly what your frame rate is.  So for example, if you frame rate is 59.933 you can specify that in dxwrapper, since the frame rate is not actually ever exactly 60.

**Comment by elishacloud** [comment]
This issue should be fixed with the latest release:  https://github.com/elishacloud/dxwrapper/wiki/WarGames
