### ISSUE TITLE
Elishacloud's fix of Gangster Organized Crime not working on Windows 11 

### ISSUE THREAD

**Issue by RickSully** [elishacloud/dxwrapper#229]
When I put the file in the directory the game simply won't start. Any idea why?

**Comment by elishacloud** [comment]
Yes, DDrawCompat 3.1 has an issue with Windows 11.  Try this update.  You may need to terminate gangster or reboot before this will work.

Here is the update:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12785172/dxwrapper.zip)

**Comment by RickSully** [comment]
Thank you! It fixed it! If it doesn't bother you, could you put the update on the main page? A few friends of mine wanted to play as well but they were having the same issue.

**Comment by elishacloud** [comment]
I am working on getting a release out and I will update it soon.

**Comment by RickSully** [comment]
Thank you!

**Comment by elishacloud** [comment]
I updated the patch page with the latest update:  https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime
