### ISSUE TITLE
Armada 1

### ISSUE THREAD

**Issue by amcghee1** [elishacloud/dxwrapper#23]
Hello.
First of all thanks very much for the DXWrapper for Armada 1 for Windows 10. Great to be able to fire it up again.

However I'm having an issue with the game I'm hoping you can help with. I am completely unable to use any in-game drop down menus. The menu will drop down fine, but flicker then close. This stops me from doing things like changing the resolution so I'm stuck with the 640*480 resolution for now.

**Comment by elishacloud** [comment]
The menus in Star Trek Armada 1 work differently than menus in Windows.  You need to hold the mouse button down when you click the menu and keep the mouse button down while you select the item from the menu.  If you just single-click the menu it will appear and then disappear.

**Comment by elishacloud** [comment]
Yes, the patch is still using DirectX 7, which has a Maximum VGA Resolution of 2048x1536, AFAIK.  I am working on converting this to Direct3D9, which will solve this problem.  But that is still a ways off.

**Comment by mirh** [comment]
https://github.com/UCyborg/LegacyD3DResolutionHack

**Comment by elishacloud** [comment]
Thanks @mirh!  This should be pretty easy to add to dxwrapper.

**Comment by mirh** [comment]
Would be also cool if you could shed some light on the mystery I raised https://github.com/UCyborg/LegacyD3DResolutionHack/issues/2

**Comment by elishacloud** [comment]
Sure.  When I get a chance I will look into it.  I have been super busy lately.

**Comment by elishacloud** [comment]
I added [LegacyD3DResolutionHack](https://github.com/UCyborg/LegacyD3DResolutionHack) to the project.  This allows the game to play in 4K resolution.

Download the update from here: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/2872436/dxwrapper.zip)

**Comment by elishacloud** [comment]
Closing issue.  Should be fixed now!
