### ISSUE TITLE
alt tab can be trigged but the selected window cannot show up.

### ISSUE THREAD

**Issue by iujakchu** [elishacloud/dxwrapper#236]
I tried to use it with plant vs zombie.
I have to enable FullscreenWindowMode so the game launch with fullscreen mode,
but I cannot switch to another window.

**Comment by elishacloud** [comment]
Yes, `FullscreenWindowMode` forces the window to be on the top.  Try pressing Win+D to minimize all windows.  Then you should be able to switch to another window after that.

**Comment by elishacloud** [comment]
Ok, try this update and let me know if it works or not:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/13292225/dxwrapper.zip)

**Comment by rebb** [comment]
I fiddled around with a similar Alt-Tab Issue a while ago, but it was for Windowed Mode, not sure if it applies here too.
Don't know what the code changes are in the ZIP, maybe they are pretty much the same.

I haven't gotten around to pushing some of my stuff to my fork yet for a possible PR ( wasn't sure if it was too hacky anyway ).

My main code change was in `IDirect3D9Ex.cpp, AdjustWindow Function` changing `SetWindowPos(MainhWnd, HWND_TOP, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER | SWP_FRAMECHANGED);` to `SetWindowPos(MainhWnd, HWND_NOTOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_NOZORDER | SWP_FRAMECHANGED);`

**Comment by elishacloud** [comment]
Try this update and let me know if this works or not:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/13326353/dxwrapper.zip)

**Comment by rebb** [comment]
:thinking:

**Comment by elishacloud** [comment]
I am not sure if the last fix solved this issue.  However, I can reproduce this issue with `dd7to9` on a couple of games.  What features of dxwrapper are you using for this game?  I don't think setting `HWND_NOTOPMOST` is the right fix.  I have seen where removing `D3DCREATE_NOWINDOWCHANGES` has solved this for some games.

**Comment by elishacloud** [comment]
Alt+Tab should work for most games with the latest build here:  [dx7 binaries.zip](https://github.com/user-attachments/files/16318118/dx7.binaries.zip)

**Comment by elishacloud** [comment]
Closing issue.
