### ISSUE TITLE
Tomb Raider 3 Support

### ISSUE THREAD

**Issue by Speedwagen** [elishacloud/dxwrapper#237]
Feel Free to close this if you do not have the time but I was wondering if there was any way to test support for Tomb Raider 3 or maybe 4?

**Comment by elishacloud** [comment]
I just tested Tomb Raider 3.  It uses Direct3D version 2, which dxwrapper does not have good support for yet.

**Comment by elishacloud** [comment]
I tested this game and the issue is that the textures in this game are all blank.  I enabled `DdrawFillSurfaceColor` and you can see that the game is working, but all the textures are blank.  I need to figure out why the game is not able to load the correct texture here.

**Comment by elishacloud** [comment]
Ok. Tomb Raider 3 should be working with the latest build:  [dxwrapper.zip](https://github.com/user-attachments/files/17711178/dxwrapper.zip)

**Comment by elishacloud** [comment]
This build should fix all issues I could find with Tomb Raoder 3: [dxwrapper.zip](https://github.com/user-attachments/files/18083971/dxwrapper.zip)

**Comment by elishacloud** [comment]
This is fixed with the latest release. You can reopen it if you are still having issues.
