### ISSUE TITLE
Windowed Gangsters: Organized Crime?

### ISSUE THREAD

**Issue by Itay080** [elishacloud/dxwrapper#24]
Thank you for your Windows 10 patch for Gangsters: Organized Crime! But when I try to use DxWnd to play it in windowed mode the game just crashes, is there a configuration which is used to run it in windowed mode?
Thanks

**Comment by elishacloud** [comment]
I have tried many different ways to get this game to work, including: [WineD3D](https://fdossena.com/?p=wined3d/index.frag), [dgVoodoo](http://dege.freeweb.hu/), [DxWnd](https://sourceforge.net/projects/dxwnd/), [DDrawCompat](https://github.com/narzoul/DDrawCompat), [Microsoft ACT](https://docs.microsoft.com/en-us/windows/deployment/planning/act-technical-reference).  This is the only solution for Windows 10 that I know of at the time, without modifying the original binary files which I don't want to do.  My solution requires the game to run at fullscreen.  It will not work in windowed mode.

However, I am working on creating a [ddraw to d3d9 converter](https://github.com/elishacloud/dxwrapper/commit/af51e8c270e134d97e37457e6ce181e79dffdc9b).  This converter allows most games to run in windowed or fullscreen mode.  But this is a long project and will likely take me more than a year to complete.  Also this game makes heavy use of GDI, which may be hard to convert to d3d9.

dgVoodoo does convert from ddraw to d3d11, however it is more of a ddraw _emulator_ that uses d3d11 as its graphics engine.  This can cause performance and other issues.  I am planning to make as close to 1-to-1 mapping of the ddraw APIs to d3d9 APIs as possible, so it should allow games to run at their native speed.  It already works with a handful of games and is MUCH faster than ddraw.

**Comment by Itay080** [comment]
In that case I'll just wait patiently for your converter! :)
Thank you for making old games work on modern Windows!

**Comment by mirh** [comment]
Well, `dd7to9=1` has certainly progressed since.
And even beside that, there is a lot of fullscreen-related settings you can experiment with.

**Comment by elishacloud** [comment]
> any chance you've created something to run the game in windowed mode?

No.  This game uses a lot of GDI calls, some of which work slightly different in newer versions of Windows.  I am not sure of a way to play this game in Windowed mode.
