### ISSUE TITLE
On the Page for Blood II The Chosen - Dead Link for Dege's High Resolution Patch

### ISSUE THREAD

**Issue by MasterO2** [elishacloud/dxwrapper#242]
@elishacloud, on https://github.com/elishacloud/dxwrapper/wiki/Blood-II-The-Chosen, where it says `To fix the crash when using too high of resolution I'm using the dege high resolution patch, which can download from [here](http://dege.freeweb.hu/Patches/Patches.html)`, that download link no longer works / is dead.

The Blood II dege high resolution patch can now be found at http://dege.freeweb.hu/Patches/bin/Blood2ResPatch.zip.

**Comment by elishacloud** [comment]
Thanks!  It should be fixed now.
