### ISSUE TITLE
Star Trek Armada: transparent cursor

### ISSUE THREAD

**Issue by yochenhsieh** [elishacloud/dxwrapper#247]
OS: Windows 11
Armada-fix: 2023/10/03 (use Dd7to9)
dxwrapper.dll 1.1.6900.22

![Armada 2023-12-27 23-29-32-54](https://github.com/elishacloud/dxwrapper/assets/1897377/880af590-06be-4c47-8dbc-78f214ca36c3)
![Armada 2023-12-27 23-30-07-30](https://github.com/elishacloud/dxwrapper/assets/1897377/f259a5cb-2ae9-45d0-9866-6141d636618c)

Normal:
![Armada 2023-12-27 23-44-32-69](https://github.com/elishacloud/dxwrapper/assets/1897377/ec70eb85-73be-4464-a1d7-07cac6664a2a)
![Armada 2023-12-27 23-44-40-66](https://github.com/elishacloud/dxwrapper/assets/1897377/06817350-1481-40d1-acae-01ec58dd748b)

The normal screenshot was using 2023/04 fix (use DDrawCompat)
dxwrapper.dll 1.0.6615.21

**Comment by elishacloud** [comment]
Yes, I know about the semi-transparent cursor.  This has to do with the way dxwrapper's dd7to9 handles when the game writes to the the front buffer.

**Comment by elishacloud** [comment]
This issue has been resolved in the latest build.  You can download it here:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/14625809/dxwrapper.zip)

**Comment by yochenhsieh** [comment]
Confirmed it's fixed. Thank you!

**Comment by elishacloud** [comment]
Ok, thanks.  Closing issue.
