### ISSUE TITLE
Laghaim

### ISSUE THREAD

**Issue by nallrad** [elishacloud/dxwrapper#25]
Think you could make it work with Laghaim? It's a Korean game I think and the most famous western server is http://www.lhgenericname01.lc, it's SUPER laggy in windows 10.

**Comment by elishacloud** [comment]
It looks like Laghaim was created to use DirectX8.  You could try using the `d3d8to9` option.  This would convert the graphics to DirectX9 and can fix some issues like this.

Anyways, I am closing this old issue for now.
