### ISSUE TITLE
Crash with NV D3D12

### ISSUE THREAD

**Issue by Mitradis** [elishacloud/dxwrapper#253]
I decided to create a general topic in order to tie together the common problem of wrappers.
https://www.vogons.org/viewtopic.php?p=1228733#p1228733
As can be understood from what is described there, there is some problem with new drivers and old hardware.

For example, on the new version of the drivers I have a problem with NFS Underground 2 with dgVoodoo. But if i setup dxwrapper everything is fine.

But with dxwrapper and ForceDirect3D9On12 option i cant play in Space Rangers 2 for example (CTD). Before driver update no have problem.

Both wrappers have a similar problem but manifest themselves differently in different games.

**Comment by Mitradis** [comment]
[dxwrapper-rangers.log](https://github.com/elishacloud/dxwrapper/files/14056786/dxwrapper-rangers.log)

**Comment by elishacloud** [comment]
The ForceDirect3D9On12 option just uses a different API.  I have no control of that code, as that is Microsoft's code.  It is open source though.  You can see the code [here](https://github.com/microsoft/D3D9On12).

Some games work fine with that code and some games don't work with it.

**Comment by Mitradis** [comment]
I understand, but it started to depend on the driver version, which is not very good...

**Comment by elishacloud** [comment]
Understood.  But this is not my code so I have no control over it.  At this time I don't plan on spending time to fix their issue.  I have too many other things to do right now.

**Comment by elishacloud** [comment]
Closing this issue.
