### ISSUE TITLE
Instability when testing Buggy (1998, d3d) 

### ISSUE THREAD

**Issue by Ryder17z** [elishacloud/dxwrapper#256]
Depending on the options selected, the game process may halt early and exit. (common issue on modern windows) or the game crashes when d3d is selected instead of the software render and the game loads the 3d levels. The game also offers a 3dfx mode but it is irrelevant for dxwrapper - This game can cause the dxwrapper executable to crash.

[zipped log file (game crash) dxwnd.zip](https://github.com/elishacloud/dxwrapper/files/14211947/dxwnd.zip)

**Comment by elishacloud** [comment]
dxwrapper includes a very old version of dxwnd but does _not_ maintain the code for dxwnd.  Please contact the owner of dxwnd for issues in that project.

**Comment by Ryder17z** [comment]
I thought it was part of this project as I have only glanced over the
readme. Thanks for the quick reply though.
