### ISSUE TITLE
Gangsters: Organized Crime not starting

### ISSUE THREAD

**Issue by jozsaVilmos** [elishacloud/dxwrapper#259]
Hi!

Using the latest version of the fix on Windows 11. Game does not start only black screen then exits. Log attached.

[dxwrapper-gangsters.log](https://github.com/elishacloud/dxwrapper/files/14324810/dxwrapper-gangsters.log)

**Comment by elishacloud** [comment]
I believe that is an old build with an issue on Windows 11.  Try with this update.  Just unzip this file into the game folder overwriting the older file:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/14504778/dxwrapper.zip)
