### ISSUE TITLE
The Guild 1 Steamversion

### ISSUE THREAD

**Issue by LPDaVinci** [elishacloud/dxwrapper#26]
Hey idk if you know the guild 1 its a old game from thq nordic.
The gog version which uses the gildegold.exe  works flawless with the ddraw.dll

but the steam version does not.

it uses the Europa1400Gold.exe  or 1400Gold_TL.exe
It crops some textures.

**Comment by elishacloud** [comment]
Hello @LPDaVinci, I am working on a tool to convert ddraw into d3d9.  Attached is an early version of this tool.  I tested it with the GOG version of `Europa1400Gold_TL.exe` and it seemed to work for me.  It does _not_ yet work with `Europa1400Gold.exe`.  I am not sure what the difference is between the two.

You can give it a try and let me know if it works for you when using the "TL" version of Steam.  Just unzip these 3 files into "The Guild 1" install folder: [ddraw.zip](https://github.com/elishacloud/dxwrapper/files/2173893/ddraw.zip)

This will convert the game into Direct3D9.

**Comment by LPDaVinci** [comment]
If i use the attached one it cuts the edges, too.. i guess it has something to do with steam cuz it hooks for steam. It starts the wrapper and than in the log it does this:
`4876 19:33:02.005 Starting DxWrapper v1.0.5871.21
4876 19:33:02.005 To be filled by O.E.M. To be filled by O.E.M. To be filled by O.E.M. (Desktop)
4876 19:33:02.005 ASUSTeK COMPUTER INC. 970 PRO GAMING/AURA Rev 1.xx (Desktop)
4876 19:33:02.006 NVIDIA GeForce GTX 1050 Ti
4876 19:33:02.007 Windows 8.1 64-bit (6.3.9600) 
4876 19:33:02.007 Europa1400Gold_TL.exe (PID:3548)
4876 19:33:02.008 Reading config file: dxwrapper.ini
4876 19:33:02.009 Enabling ddraw wrapper
4876 19:33:02.009 Disabling High DPI Scaling...
4876 19:33:02.010 Loaded library: Shcore.dll
4876 19:33:02.010 Set exception handler
4876 19:33:02.010 Loaded library: kernel32.dll
4876 19:33:02.010 Finished setting exception handler
4876 19:33:02.010 Hooking ddraw.dll APIs...
4876 19:33:02.012 Loaded library: d3d9.dll
4876 19:33:02.267 Quiting DxWrapper
4876 19:33:02.267 Unhooking APIs...
4876 19:33:02.267 Unloading libraries...
4876 19:33:02.267 Unloading exception handlers
4876 19:33:02.267 Reseting screen resolution...
4876 19:33:02.273 DxWrapper terminated!`

**Comment by LPDaVinci** [comment]
I guess it must be something to do with the manipulated core files . cuz the steam overlay hooks into the original exe file. with the gog version it works i tested it at a friend of mine. Maybe steam is just breaks it.

**Comment by elishacloud** [comment]
Yes, it could be just an issue with what Steam does to the game.  I have a number of projects ahead of this one so I won't be able to look at it right away.  But I will put it on my list.

**Comment by LPDaVinci** [comment]
thank you, dankeschön.

**Comment by elishacloud** [comment]
I just realized, based on narzoul's comments, that the TL version is using d3d8.  Try this new update.  I am not sure if it will help, but this will convert d3d8 to d3d9.

[ddraw.zip](https://github.com/elishacloud/dxwrapper/files/2178670/ddraw.zip)

**Comment by LPDaVinci** [comment]
Ok i hate steam. I switch back to the gog Version where it works without any problems. I need to contact Steam Support that they should use the gog corefiles. but thank you anyway elishacloud

**Comment by elishacloud** [comment]
Closing issue.
