### ISSUE TITLE
How to contact you?

### ISSUE THREAD

**Issue by Kim2091** [elishacloud/dxwrapper#261]
I'm one of a few admins running the RTX Remix Discord server, and I'd like to PM you regarding dxwrapper and your work on it. If you could please provide a method to do so, that'd be great 🙂. Thank you

**Comment by elishacloud** [comment]
I am not on Discord.  But you can email me if you like.  I can give you my email address.

**Comment by Kim2091** [comment]
That would be great :)

**Comment by elishacloud** [comment]
My email address is:  elisha@novicemail.com

**Comment by elishacloud** [comment]
Added my email to the last (deleted) post.  Let me know if you did not get it.

**Comment by Kim2091** [comment]
I got it, thank you. I'll be sending an email relatively soon
