### ISSUE TITLE
How to properly remove dxwrapper

### ISSUE THREAD

**Issue by sxdxmfeeder** [elishacloud/dxwrapper#262]
I've removed the 3 required files from the game folder: ddraw.dll, dxwrapper.dll, dxwrapper.ini
Now every time I open the game, it shows this message: Could not find Dxwrapper.dll functions will be disabled!

![dxwrapper](https://github.com/elishacloud/dxwrapper/assets/161795324/16c47ad6-e951-4281-b457-00dbcf2ed050)

The game can still start but this message keeps appearing when launching the game.

**Comment by sxdxmfeeder** [comment]
My apology,
I think I copied an extra file to the game folder: d3d9.dll
And that triggered the message.

I deleted the .dll and it stopped showing the message box.

**Comment by elishacloud** [comment]
No problem.  I'll close out the ticket.
