### ISSUE TITLE
[Warning] Area 51 (2005)

### ISSUE THREAD

**Issue by SilentMRG** [elishacloud/dxwrapper#263]
Hello everybody!

I just want to let you know that the source code is available here: https://github.com/ProjectDreamland/area51

And it's important to remember that the game in question is Freeware, and free of copyright since 2008, so if any programmer is interested in starting a source port project now is a good time, and there will be no barriers to it.

Cheers!

**Comment by elishacloud** [comment]
Thanks @SilentMRG!  I am not planning to do any work on specific games like this.  I want to spend my time working on `dd7to9`.

**Comment by SilentMRG** [comment]
Elisha, no problem... I thank you for your attention! And thanks for all your work on dxwrapper. =)
