### ISSUE TITLE
Mechwarrior 3 on Vista

### ISSUE THREAD

**Issue by KoleckOLP** [elishacloud/dxwrapper#267]
The game is using DX6.1 and I want to use this wrapper to wrap it to DX9 which is better supported on my gpu.

I copied ddraw.dll dxwrapper.dll and dxwrapper.ini next to the game executable Mech3.exe
and when I launch it it says Could not find DxWrapper.dll functions will be disabled

Meaning I only get DX6 to DX7 and not DX9, I don't know how to fix this.

**Comment by KoleckOLP** [comment]
oh, I assume this is a Vista issue meaning that on windows 10 it finds the file just fine and on vista it does not.

**Comment by elishacloud** [comment]
Yeah, the release and new builds only likely work on Windows 7 and newer.  I did make a build that should work with Windows XP.  You can try this is the latest build compiled for Windows XP:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/14891609/dxwrapper.zip)

**Comment by elishacloud** [comment]
Closing issue.
