### ISSUE TITLE
WinBolo fails in VMware

### ISSUE THREAD

**Issue by FunkyFr3sh** [elishacloud/dxwrapper#275]
Posting here so we don'T have to spam off-topic things in the other issue 😄

Game doesn't seem to work with the test build you posted, got many of these in the logs:

```
3936 03:29:17.199 m_IDirectDrawSurfaceX::ColorFill Error: invalid rect: {0,85,3,85}
3936 03:29:17.199 m_IDirectDrawSurfaceX::ColorFill Error: invalid rect: {12,85,15,85}
3936 03:29:17.199 m_IDirectDrawSurfaceX::ColorFill Error: invalid rect: {36,85,39,85}
3936 03:29:17.199 m_IDirectDrawSurfaceX::PresentSurfaceToWindow Error: Failed to copy surface: {574,325,613,410} -> {446,155,485,240}
3936 03:29:17.200 m_IDirectDrawSurfaceX::PresentSurfaceToWindow Error: Failed to copy surface: {149,442,621,477} -> {21,272,493,307}
3936 03:29:17.200 m_IDirectDrawSurfaceX::PresentSurfaceToWindow Error: Failed to copy surface: {590,255,597,269} -> {462,85,469,99}
3936 03:29:17.200 m_IDirectDrawSurfaceX::PresentSurfaceToWindow Error: Failed to copy surface: {590,269,597,283} -> {462,99,469,113}
3936 03:29:17.200 m_IDirectDrawSurfaceX::PresentSurfaceToWindow Error: Failed to copy surface: {478,400,538,423} -> {350,230,410,253}
3936 03:29:17.200 m_IDirectDrawSurfaceX::PresentSurfaceToWindow Error: Failed to copy surface: {571,197,611,237} -> {443,27,483,67}

```

To test just start the game and click on tutorial (this is where the actual gameplay starts)

**Comment by elishacloud** [comment]
That is weird.  Works fine for me.  I tried both the tutorial and the practice.

Here is the debug build.  Maybe this will give us some clues:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/15425961/dxwrapper.zip)

**Comment by FunkyFr3sh** [comment]
I forgot to mention that the game is actually closing (crashing?) once you get into the gameplayer

Here's a log from my Win7 VM where the bug occurs:

[dxwrapper-winbolo.log](https://github.com/elishacloud/dxwrapper/files/15426007/dxwrapper-winbolo.log)

**Comment by elishacloud** [comment]
Do you have a Windows 10 to try with?  I have not tested on Win7 in a long time.

**Comment by FunkyFr3sh** [comment]
Same problem there

**Comment by elishacloud** [comment]
That is weird because it works fine for me.

https://github.com/elishacloud/dxwrapper/assets/25625456/c5ba14a2-366a-409b-983f-12a1f8db562e

For you, it looks like it is failing here:

```c++
3248 03:45:19.597 m_IDirectDrawSurfaceX::PresentSurfaceToWindow Error: Failed to copy surface: {621,247,661,287} -> {443,27,483,67}
```

The code that is failing is [here](https://github.com/elishacloud/dxwrapper/blob/748e86f1045b14f9adef81838e1c34d25e260967/ddraw/IDirectDrawSurfaceX.cpp#L6478), which runs this code [here](https://github.com/elishacloud/dxwrapper/blob/748e86f1045b14f9adef81838e1c34d25e260967/d3d9/IDirect3DDevice9Ex.cpp#L1974-L1989).  I don't think I have ever seen that code fail.  Must be something to do with your video card.  I see you are using VMware.  Do you have a physical device you can try on?  I wonder if it is a VMware issue?

**Comment by elishacloud** [comment]
I just tried it on VMware and I am seeing something similar.  I am not sure if dxwrapper can support VMware.  I need to look into what is happening.

**Comment by FunkyFr3sh** [comment]
Ah right... Well, it's not that important I guess, just wanted to report it.

It does work in other games though, I got almost all of my games in these VM's and DxWrapper had no issues in there so far

**Comment by elishacloud** [comment]
This is fixed with the latest build.  Just enable the `dd7to9` feature and it should work, even on VMware.

[dxwrapper.zip](https://github.com/user-attachments/files/17237056/dxwrapper.zip)
