### ISSUE TITLE
Atlantis: The Lost Empire Trial by Fire can't launch with dgVoodoo via RealDllPath

### ISSUE THREAD

**Issue by gordonfreeman01** [elishacloud/dxwrapper#281]
Hi, so Atlantis: The Lost Empire Trial by Fire is a very temperamental game which only dxwrapper seems to fix reliably but to scale up the resolution I need to use dgVoodoo in tandem and it doesn't seem to work.

Here's what I tried (all in the game's installation directory):
1. Copy dxwrapper.dll, dxwrapper.ini and ddraw.dll stub
2. In dxwrapper.ini enable:
`DDrawCompat                = 1`
3. Copy dgVoodooCpl.exe, set up the desktop as resolution in the DirectX tab

At this point I tried using the RealDllPath to launch via dgVoodooCpl but it doesn't inject. I can't replace the stubbed ddraw.dll from dxwrapper with the one from dgvoodoo otherwise it won't launch dxwrapper so I tried setting RealDllPath to "D3DImm.dll" and copy that one from dgvoodoo instead, no dice. I then tried moving dgvoodoo's ddraw.dll stub into another folder together with the conf and control panel and set that dll full path in RealDllPath and it still doesn't load. The dxwrapper logs don't seem to indicate the dll was changed either.

The documentation for dxwrapper tells to rename dxwrapper.dll into the target dll and then set RealDllPath but then how would it find dgvoodoo and run it? Please help clarify the steps to combine dgVoodoo and dxwrapper.

**Comment by elishacloud** [comment]
[DDrawCompat](https://github.com/narzoul/DDrawCompat) will not work in conjunction with other wrappers because DDrawCompat goes down to the DDE driver level to manipulate things.  Other wrappers don't see that activity.

**Comment by gordonfreeman01** [comment]
> [DDrawCompat](https://github.com/narzoul/DDrawCompat) will not work in conjunction with other wrappers because DDrawCompat goes down to the DDE driver level to manipulate things. Other wrappers don't see that activity.

Thanks, I tried using EnableDdrawWrapper and set RealDllPath to the dgvoodoo ddraw.dll in another folder but it still doesn't inject. Is there a similar constraint there? Using Dd7to9 doesn't work as the game audio runs but the visuals are just garbled colored lines.

**Comment by elishacloud** [comment]
Setting `RealDllPath` only works in the dxwrapper.ini file if dxwrapper is wrapping a dll.  But since it is named as dxwrapper.dll it is not wrapping any dll.  It may be hooking into a dll but not wrapping.

To fix this you can add a configuration file for the stub.  If you are using the ddraw.dll file as the stub then you can create a ddraw.ini file and add the `RealDllPath` option to the stub.  See [here](https://github.com/elishacloud/dxwrapper/wiki/Configuration-(stub)) for more details.

**Comment by gordonfreeman01** [comment]
Ah, cool so I renamed dxwrapper to ddraw.dll, renamed the ini file to ddraw.ini and set the realdll to dgvoodoo's ddraw folder where I also placed the dgvoodoo conf and control panel. Using only EnableDdrawWrapper enabled it doesn't seem to be injecting dgvoodoo but in the dxwrapper logs loading d3d9.dll after loading ddraw.dll, is that expected behaviour?

**Comment by gordonfreeman01** [comment]
> > but in the dxwrapper logs loading d3d9.dll after loading ddraw.dll, is that expected behaviour?
> 
> Sounds like you have dd7to9 enabled. If you have that enabled it will overwrite ddraw.dll.

I just enabled EnableDdrawWrapper, everything else is off, other than the realddll path. I tried setting it to dgvoodoo's D3D9.dll and got this in the ddraw logs:
`18724 16:21:15.652 Wrapping 'ddraw.dll'...
18724 16:21:15.652 Loading '"C:\Program Files (x86)\Disney Interactive\Atlantis - Trial by Fire\dgvoodoo\D3D9.dll"' as real dll...
18724 16:21:15.654 Error: Failed to load '"C:\Program Files (x86)\Disney Interactive\Atlantis - Trial by Fire\dgvoodoo\D3D9.dll"'!`

**Comment by elishacloud** [comment]
> I just enabled EnableDdrawWrapper, everything else is off, other than the realddll path.

You don't really need `EnableDdrawWrapper`.  For RealDllPath, make sure you include the relative path to the new dll.  For example, if you are using dgVoodoo2 then you need to copy over both ddraw.dll and the D3DImm.dll file.  You can rename the dgVoodoo2's DDraw.dll to dgDDraw.dll and then add dgDDraw.dll to the ini file.

Don't use the D3D9.dll file for dgVoodoo2 unless you convert the game to Driect3D9.  For example, if you use the `dd7to9` option in dxwrapper then you can covert the game to d3d9 and then you can just copy the d3d9.dll file from dgVoodoo2 into the same folder.  In this case you won't need to use the RealDllPath option at all.

**Comment by gordonfreeman01** [comment]
Thanks for clarifying. I thought for dx7 fixes I'd need to enable one of the options related to it. Thanks, it works now! The reason why I am trying this combination is that this game is crash-heavy and the fix in this thread seems to be the only way so far to get proper widescreen working:
https://github.com/ThirteenAG/WidescreenFixesPack/issues/1517

The resolution changing requires dgvoodoo as the game does not support it internally but it seemed to crash a lot with just dgvoodoo prior to v2.82.5 (tested on v2.82.3). Using dxwrapper with none of the special modes turned on and the configuration for realdll as you described works but leads to hitches, probably due to the two wrappers running at the same. Closing this issue as the injection works!

I would suggest putting a sample of how to configure an alternate realdll (maybe even the one you just used on the wiki page) to make the configuration wiki page a bit clearer as that helped me better understand it. Confirmed that putting dgvoodoo in its own folder doesn't work, at least for this game :)
