### ISSUE TITLE
GTA vice city weather constently change @ DxWrapper newest commit

### ISSUE THREAD

**Issue by niresh1234** [elishacloud/dxwrapper#289]
GTA vice city weather constently change @ DxWrapper newest commit

**and issue exactly start from this commit** https://github.com/elishacloud/dxwrapper/commit/7e4007ec71f7cb914b9fcba1e68a5af6c9a8e702
before this commit, not have this issue

the issue appears when install mixsets, but only with newest dxwrapper commit (which is mentioned hare)

mods installed:

- ddraw patch by silent
- cleo 2.0.0.6
- ual
- widescreenFix
- mixsets
- & dxwrapper (latest artifact)

### For testing purpuse, I make a zip file to extract clean GTA-VC (asuming game version 1.0 & no-cd exe is installed) 👉 [for_testing_only.zip](https://github.com/user-attachments/files/16614652/for_testing_only.zip)

see issue

https://github.com/user-attachments/assets/d4ecbd1f-9e12-4c6c-96fe-66862c174bea

**Comment by elishacloud** [comment]
Thanks for reporting this and figuring out which commit has the issue. Can you test with this update to see if it fixes the issue:  [dxwrapper.zip](https://github.com/user-attachments/files/16616038/dxwrapper.zip)

**Comment by niresh1234** [comment]
Sure! I will check but tomorrow, Currently I'm almost sleeping

**Comment by niresh1234** [comment]
> Thanks for reporting this and figuring out which commit has the issue. Can you test with this update to see if it fixes the issue: [dxwrapper.zip](https://github.com/user-attachments/files/16616038/dxwrapper.zip)

### yes! fixed issue with this

**Comment by elishacloud** [comment]
Ok, great.  I just checked in the fix.

**Comment by niresh1234** [comment]
Well Done 👌 The issue fixed in latest commit/Artifacts

so, you can close this issue as completed........, if you want

**Comment by elishacloud** [comment]
Thanks!
