### ISSUE TITLE
How about adding shader scalers ability?

### ISSUE THREAD

**Issue by Randall-Glass** [elishacloud/dxwrapper#29]
Adding hardware shaders sclaers ability would be great for this wrapper.

With this you could download any shader scaler - for example a hq2x shader scaler , OR xbrz OR super xbr shader.

You could use any shader scaler you could find on the Internet. 

It would breath new life into old low resolution programs.

**Comment by elishacloud** [comment]
I definitely don't want to reproduce what [ReShade](https://github.com/crosire/reshade) does.  ReShade is a great program and I would like it to be able to run it along side this one.  My latest version of dxwrapper (unreleased as of yet) does have the ability to stretch a DirectX1-7 game's resolution from 320x200  to any larger size that your monitor supports.

However as far as using shaders like hqx, I am not sure if that should be done before you stretch the image or not.  I assume if you do hqx after you stretch the picture much of advantage of hqx is lost.  Anyways I am not sure if ReShade is able to do this.  I will need to investigate to figure out how I can stretch the screen and use hqx, preferably using ReShade so I don't have to duplicate any of the good work that [crosire](https://github.com/crosire) is doing.

Anyways, thanks for the comments.  I did not realize ReShade did this already.

**Comment by elishacloud** [comment]
Closing this as not planned in the near future.
