### ISSUE TITLE
Can dxwrapper help with Bioshock Remastered stretched vertically in 16:10?

### ISSUE THREAD

**Issue by Hexaae** [elishacloud/dxwrapper#292]
Do you think this tool can help with Bioshock Remastered not supporting 16:10 and stretching viewport vertically to fully cover the screen instead of the usual two horizontal black borders up and down?
This DX11 game supports only 16:9 resolutions and widescreen 21:9... Wondering if your tool can help in rare cases like this game where viewport gets always stretched to fill the whole screen, doesn't matter if this will alter proportions (circles becomes ovals, squares to rectangles etc.). Most games in 16:9 resolutions just add black borders keeping the letter-boxed screen centered, but at least keeps also proportions of UI correctly.

**Comment by elishacloud** [comment]
No.  DxWrapper does not support do anything with DX11.  It can hook into DX11 games but it does not have a DX11 wrapper.  I mostly focus on older games..  DX9 and older.

**Comment by Hexaae** [comment]
Ok thanks. It seems it doesn't exist yet a wrapper (dx9-10-11) to force aspect ratio, sigh...

**Comment by Hexaae** [comment]
Would be really useful with some games indeed.

**Comment by elishacloud** [comment]
Closing issue as I don't currently have any plans to support DX11.
