### ISSUE TITLE
audio/sound not working in "Scarface - The world is Yours"

### ISSUE THREAD

**Issue by niresh1234** [elishacloud/dxwrapper#293]
audio/sound not working in Scarface The world is Yours

using `EnableD3d9Wrapper` and any one from below
`EnableWindowMode` OR `FullscreenWindowMode`

the issue only exist in from 2023 release, 2021 release not having these issue

I find exact commit where issue was introduced 👉 https://github.com/elishacloud/dxwrapper/commit/3abc22d7174fc386e117bed1d1e56c1c9c584c63
 
.
.
.
.

 
### I trying to revert a single line from these commit and sound/audio sudenly start working

https://github.com/elishacloud/dxwrapper/blob/c843ec2abafd8d102caceb6bbda714a9aad396f9/d3d9/IDirect3D9Ex.cpp#L581

**I change from**
`if (AnyChange && Config.FullscreenWindowMode)`
**to**
`if (Config.FullscreenWindowMode && AnyChange)`

.
.
.
.

### But wait, Im not a programmer and I dont know how it is working, so not saying what is solution

**Comment by elishacloud** [comment]
> **I change from**
> `if (AnyChange && Config.FullscreenWindowMode)`
> **to**
> `if (Config.FullscreenWindowMode && AnyChange)`

That shouldn't make any difference.  Since both of these are just bool variables the order of check should not matter.  Have you tried with the latest build I just updated yesterday?

See here: https://github.com/elishacloud/dxwrapper/actions/runs/10550360657

**Comment by niresh1234** [comment]
yes! sound/audio newest artifact.... and the issue actually was fixed in 👉 [this](https://github.com/elishacloud/dxwrapper/actions/runs/10536676645)

im try to experiment in latest repository where issue was already fixed.....😂

**Comment by elishacloud** [comment]
Sorry about all the work testing it.  But thank you for the detailed evaluation.  I really appropriate it.

**Comment by niresh1234** [comment]
you can close this not as working

**Comment by elishacloud** [comment]
Closing

**Comment by niresh1234** [comment]
actually, issue was fixed
