### ISSUE TITLE
Windows XP Build

### ISSUE THREAD

**Issue by AITUS95** [elishacloud/dxwrapper#298]
Hey, I downloaded the latest build and I'm using the Windows XP build on a virtual machine through VMware 17.5.2. When I try to run a game, I keep getting an error message about 'InitializeCriticalSectionEx' in KERNEL32.dll.

**Comment by AITUS95** [comment]
I was wrong to download version, sorry.

**Comment by mirh** [comment]
Follows #233 and should have been improved further in #283.
