### ISSUE TITLE
Gangsters black screen

### ISSUE THREAD

**Issue by ElbiChot** [elishacloud/dxwrapper#301]
I downloaded a fresh game from GOG and installed patch you provided. I also changed a registry edit that was stated on gog was required to play the game 

$~ 16BITCOLOR DWM8And16BitMitigation 8And16BitTimedPriSync 8And16BitAggregateBlts Layer_ForceDirectDrawEmulation

But now all i get a is black screen. The buttons appear when I alt tab out and come back in. If i dont then the whole screen is black. How can I fix?
![image](https://github.com/user-attachments/assets/33962c3e-82c0-4188-8a49-c7ffa4c9680d)

**Comment by ElbiChot** [comment]
6584 17:59:46.872 Starting DxWrapper v1.1.6900.22
6584 17:59:46.872 Running from: C:\Program Files (x86)\GOG Galaxy\Games\Gangsters\dxwrapper.dll
6584 17:59:46.872 Reading config file: C:\Program Files (x86)\GOG Galaxy\Games\Gangsters\dxwrapper.ini
6584 17:59:46.872 ASUSTeK COMPUTER INC. ROG Strix G614JI_G614JI 1.0 (Notebook)
6584 17:59:46.872 ASUSTeK COMPUTER INC. G614JI 1.0 (Notebook)
6584 17:59:46.872 Intel(R) UHD Graphics
6584 17:59:46.872 Windows 10 Home 64-bit (10.0.22621)
6584 17:59:46.873 gangsters.exe (PID:35924)
6584 17:59:46.879 Environment variable __COMPAT_LAYER = "DisableThemes RunAsAdmin DWM8And16BitMitigation 8And16BitTimedPriSync 8And16BitAggregateBlts Layer_ForceDirectDrawEmulation Installer"
6584 17:59:46.879 Disabling High DPI Scaling...
6584 17:59:46.879 Loaded library: user32.dll
6584 17:59:46.879 Loaded library: shcore.dll
6584 17:59:46.879 Enabling dinputto8 wrapper
6584 17:59:46.879 Loading 'dinput.dll'...
6584 17:59:46.879 Loaded library: C:\WINDOWS\system32\dinput.dll
6584 17:59:46.879 Hooking dinput.dll APIs...
6584 17:59:46.879 Enabling dinput8 wrapper
6584 17:59:46.879 Loading 'dinput8.dll'...
6584 17:59:46.879 Loaded library: C:\WINDOWS\system32\dinput8.dll
6584 17:59:46.879 Loading 'ddraw.dll'...
6584 17:59:46.879 Loaded library: C:\WINDOWS\system32\ddraw.dll
6584 17:59:46.879 Hooking ddraw.dll APIs...
6584 17:59:46.880 Enabling DDrawCompat
6584 17:59:46.880 Enabling ddraw wrapper
6584 17:59:46.880 Process path: C:\Program Files (x86)\GOG Galaxy\Games\Gangsters\gangsters.exe
6584 17:59:46.880 Loading DDrawCompat dynamically from C:\Program Files (x86)\GOG Galaxy\Games\Gangsters\dxwrapper.dll
6584 17:59:46.880 Loaded library: winmm.dll
6584 17:59:46.880 Loaded library: uxtheme.dll
6584 17:59:46.880 DDrawCompat v0.3.1 version loaded successfully
6584 17:59:46.880 DxWrapper loaded!
6584 17:59:47.180 dd_DirectDrawCreateEx
6584 17:59:47.180 Redirecting 'DirectDrawCreateEx' ...
6584 17:59:47.180 Installing display mode hooks
6584 17:59:47.206 Installing registry hooks
6584 17:59:47.206 Installing Direct3D driver hooks
6584 17:59:47.206 Installing Win32 hooks
6584 17:59:47.212 Installing DirectDraw hooks
6584 17:59:47.212 Installing Direct3D hooks
6584 17:59:47.213 Installing GDI hooks
6584 17:59:47.216 Finished installing hooks
6584 17:59:47.222 Creating interface m_IDirectDrawX::m_IDirectDrawX (06768B90) v7
19632 17:59:47.231 Loaded library: dwmapi.dll
6584 17:59:48.876 Creating interface m_IDirectDrawSurfaceX::m_IDirectDrawSurfaceX (05068BD8) v7
6584 17:59:48.876 Creating interface m_IDirectDrawSurfaceX::m_IDirectDrawSurfaceX (04FD25A0) v7
6584 17:59:48.876 Creating interface m_IDirectDrawPalette::m_IDirectDrawPalette (0504F798)
6584 17:59:48.876 di_DirectInputCreateA
6584 17:59:48.876 di_DirectInputCreateEx
6584 17:59:48.876 Starting dinputto8 v1.0.54.0
6584 17:59:48.876 Redirecting 'DirectInputCreate' IID_IDirectInputA version 0x500 to --> 'DirectInput8Create'
6584 17:59:48.876 di8_DirectInput8Create
6584 17:59:48.876 Redirecting 'DirectInput8Create' ...
6584 17:59:48.887 Creating interface m_IDirectInput8A::m_IDirectInput8A (00CE6788)
6584 17:59:48.887 Creating interface m_IDirectInputX::m_IDirectInputX(067D6B88) converting interface from v1 to v8 using ANSI
6584 17:59:48.888 Creating interface m_IDirectInputDevice8A::m_IDirectInputDevice8A (067DB270)
6584 17:59:48.888 Creating interface m_IDirectInputDeviceX::m_IDirectInputDeviceX(067E8350) converting interface from v1 to v8 using ANSI
6584 17:59:48.944 Creating interface m_IDirectInputDevice8A::m_IDirectInputDevice8A (067DB318)
6584 17:59:48.944 Creating interface m_IDirectInputDeviceX::m_IDirectInputDeviceX(067E81B0) converting interface from v1 to v8 using ANSI
6584 17:59:48.998 m_IDirectDrawSurfaceX::~m_IDirectDrawSurfaceX (05068BD8) deleting interface!
6584 17:59:48.998 m_IDirectDrawPalette::~m_IDirectDrawPalette (0504F798) deleting interface!
6584 17:59:50.506 m_IDirectDrawX::~m_IDirectDrawX (06768B90) deleting interface!
6584 17:59:50.506 Redirecting 'DirectDrawCreateEx' ...
6584 17:59:50.523 Creating interface m_IDirectDrawX::m_IDirectDrawX (06768E88) v7
6584 17:59:52.596 Creating interface m_IDirectDrawSurfaceX::m_IDirectDrawSurfaceX (067733B0) v7
6584 17:59:52.597 Creating interface m_IDirectDrawPalette::m_IDirectDrawPalette (0504F798)
6584 17:59:52.627 m_IDirectDrawSurfaceX::~m_IDirectDrawSurfaceX (067733B0) deleting interface!
6584 17:59:52.627 m_IDirectDrawPalette::~m_IDirectDrawPalette (0504F798) deleting interface!
6584 17:59:54.237 m_IDirectDrawX::~m_IDirectDrawX (06768E88) deleting interface!
6584 17:59:54.237 Redirecting 'DirectDrawCreateEx' ...
6584 17:59:54.247 Creating interface m_IDirectDrawX::m_IDirectDrawX (06768FB8) v7
6584 17:59:55.915 Creating interface m_IDirectDrawPalette::m_IDirectDrawPalette (0504F798)
6584 18:00:11.409 m_IDirectDrawSurfaceX::~m_IDirectDrawSurfaceX (067F5C60) deleting interface!
6584 18:00:16.508 m_IDirectInputDevice8A::~m_IDirectInputDevice8A (067DB270) deleting interface!
6584 18:00:16.508 m_IDirectInputDeviceX::~m_IDirectInputDeviceX (067E8350) deleting interface!
6584 18:00:16.508 m_IDirectInputDevice8A::~m_IDirectInputDevice8A (067DB318) deleting interface!
6584 18:00:16.508 m_IDirectInputDeviceX::~m_IDirectInputDeviceX (067E81B0) deleting interface!
6584 18:00:16.508 m_IDirectInput8A::~m_IDirectInput8A (00CE6788) deleting interface!
6584 18:00:16.508 m_IDirectInputX::~m_IDirectInputX (067D6B88) deleting interface!
6584 18:00:16.839 m_IDirectDrawX::~m_IDirectDrawX (06768FB8) deleting interface!
6584 18:00:17.636 Quiting DxWrapper
6584 18:00:17.636 DDrawCompat detached successfully
6584 18:00:17.636 Unloading libraries...
6584 18:00:17.636 DxWrapper terminated!

**Comment by ElbiChot** [comment]
If I remove dxwrapper.dll from the folder I get a warning saying dxwrapper cant be initialized some fuctions wont work, but the game starts up the menu has no letters but if i start a new game it seems to plays fine. So it seems im in a partial fix at the moment.

**Comment by elishacloud** [comment]
Yeah, there is an issue with the latest version.  Instead, try the patch [here](https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime).

**Comment by ElbiChot** [comment]
![image](https://github.com/user-attachments/assets/514946cc-28e8-4e0d-b80a-755f14b86002)
this is what the main menu looks like when i use the patch you linked me. If I remove the dxwrapper.dll the game works but no letters.

**Comment by elishacloud** [comment]
I think this is the same issue as #258.

**Comment by ElbiChot** [comment]
It seems like it. But I'm not technical enough to know how to fix. Seems putting it in WI dow mode is the fix for them? I'd have to try that on my side

**Comment by elishacloud** [comment]
I plan to fix the black screen issue with the DDrawCompat integration into dxwrapper.

_BTW: I do have a windowed mode option, but I implemented it in Direct3D9.  So it only works with DirectDraw games if you enable `dd7to9`.  Unfortunately, Gangsters uses GDI and DirectDraw together in a way that makes it hard to port to Direct3D9.  Not sure when or if I will ever support Gangsters with `dd7to9`._

**Comment by elishacloud** [comment]
DDrawCompat black screen is fixed with the latest build.

**Comment by ElbiChot** [comment]
Awesome I'll check it out

**Comment by elishacloud** [comment]
Here is the latest fix for this:  [dxwrapper.zip](https://github.com/user-attachments/files/18000466/dxwrapper.zip)
