### ISSUE TITLE
Kane & Lynch: Dead Men crashes on boot with DeviceLookupCacheTime set to anything but 0

### ISSUE THREAD

**Issue by MrEWhite** [elishacloud/dxwrapper#303]
Since Kane & Lynch: Dead Men has an issue with dinput8 devices being checked too often, causing stuttering, I thought I'd try dxwrapper's dinput8Wrapper and DeviceLookupCacheTime setting, but it turns out if I have DeviceLookupCacheTime set to anything but 0, it crashes on startup. Attached is the debug log from the latest build.
[dxwrapper-kaneandlynch.log](https://github.com/user-attachments/files/17270567/dxwrapper-kaneandlynch.log)

**Comment by elishacloud** [comment]
Looks like I did not do a good job of checking if the cache was created.  I guess I am sending an empty cache to the game so it is not able to find any devices.

Try this update:  [dxwrapper.zip](https://github.com/user-attachments/files/17272769/dxwrapper.zip)

**Comment by MrEWhite** [comment]
> Looks like I did not do a good job of checking if the cache was created. I guess I am sending an empty cache to the game so it is not able to find any devices.
> 
> Try this update: [dxwrapper.zip](https://github.com/user-attachments/files/17272769/dxwrapper.zip)

Yup, that seems to work!

**Comment by elishacloud** [comment]
Closing issue since it is fixed.  You can reopen it if you still have an issue.
