### ISSUE TITLE
Outlaws not working correctly with DdrawUseNativeResolution=1

### ISSUE THREAD

**Issue by MrEWhite** [elishacloud/dxwrapper#304]
Attempting to play Outlaws with DdrawUseNativeResolution=1 will have the game properly open in the correct resolution, but upon the game changing modes (menu -> gameplay for example), it will go into a small window in the top left of the monitor.
<img width="1919" alt="Screenshot 2024-10-07 231038" src="https://github.com/user-attachments/assets/a44712f2-073f-48bd-91f2-526535abb8ab">
![Screenshot (1)](https://github.com/user-attachments/assets/3d77e34e-1789-44a9-9da2-506fb9796ccf)

**Comment by elishacloud** [comment]
It looks like the game runs in fullscreen windowed mode and the game modifies its own window.  You could just force exclusive mode by enabling `ForceExclusiveFullscreen`.  It seems to work ok with this game.

**Comment by MrEWhite** [comment]
> It looks like the game runs in fullscreen windowed mode and the game modifies its own window. You could just force exclusive mode by enabling `ForceExclusiveFullscreen`. It seems to work ok with this game.

Still goes into a small window in the top left when going from menu/cutscene to gameplay.

**Comment by elishacloud** [comment]
I am not 100% sure, but it appears that the game is changing the window size when it starts the actual gameplay.  Try enabling `ForceDirect3D9On12` in addition to `ForceExclusiveFullscreen`.  It appears that native Direct3D9 works differently from Direct3D12.  Driect3D9 allows the game to change the window size in exclusive mode but Direct3D12 does not seem to allow that.

_Note: I don't really want to add a bunch of fixes to the `DdrawUseNativeResolution` option.  I just offer best effort support for it._

**Comment by MrEWhite** [comment]
> I am not 100% sure, but it appears that the game is changing the window size when it starts the actual gameplay. 

It is, the game runs at 800x600 if set through olcfg.exe, but the menu/FMVs runs at 640x480 no matter what.

**Comment by elishacloud** [comment]
> the game runs at 800x600 if set through olcfg.exe

Oh, I did not know about that tool. LOL

Anyways, I tried setting the game to 800x600 and it stays in fullscreen mode as long as I have `ForceDirect3D9On12` enabled.

> the FPS seems to quite drop heavily (halves my FPS from 240 to 120) in that mode when compared to just D3D9.

Interesting.  Not much I can do about that.  I guess that is the overhead of converting to Direct3D12.

Ok, instead of enabling `ForceDirect3D9On12` try using either `SetSwapEffectShim` or `DisableMaxWindowedMode` or both.  These should force the game to stay fullscreen.

**Comment by MrEWhite** [comment]
> > the game runs at 800x600 if set through olcfg.exe
> 
> Oh, I did not know about that tool. LOL
> 
> Anyways, I tried setting the game to 800x600 and it stays in fullscreen mode as long as I have `ForceDirect3D9On12` enabled.
> 
> > the FPS seems to quite drop heavily (halves my FPS from 240 to 120) in that mode when compared to just D3D9.
> 
> Interesting. Not much I can do about that. I guess that is the overhead of converting to Direct3D12.
> 
> Ok, instead of enabling `ForceDirect3D9On12` try using either `SetSwapEffectShim` or `DisableMaxWindowedMode` or both. These should force the game to stay fullscreen.

Actually, since I globally force v-sync in the Nvidia Control Panel, it turns out that was causing the FPS drops here. Turning v-sync to application-controlled and using ForceDirect3D9On12 seems to work well without any noticeable screen tearing. Only issue now as far as I can tell with the window size is, if the resolution is set to 800x600 and you're in game, if you try to mess with something like the keyboard controls from the settings, it'll put the bindings window in the top left.

**Comment by elishacloud** [comment]
> if you try to mess with something like the keyboard controls from the settings, it'll put the bindings window in the top left.

Yeah, that is not going to be fixed.  That is not Direct3D.  That is GDI.  I don't really want to try to do anything with GDI.

**Comment by elishacloud** [comment]
Closing this as not planned.
