### ISSUE TITLE
Knights of the old Republic 1-2

### ISSUE THREAD

**Issue by Magmusic** [elishacloud/dxwrapper#306]
I was able to use QindieGL wrapper to enable Knights of the old republic 2 which is an Open GL game to work with RTX remix. However the Qindie wrapper seems to be outdated causing menu to have no text and erratic triangles in some areas. 

My question is would you or somebody be able to update the Open GL of the qindieGL wrapper to work better.

Link to wrapper
https://github.com/crystice-softworks/QindieGL
[QindieGL.1.0.rev5.zip](https://github.com/user-attachments/files/17364747/QindieGL.1.0.rev5.zip)
[QindieGL-1.0.zip](https://github.com/user-attachments/files/17364751/QindieGL-1.0.zip)

Your wrappers has helped alot of games work with Remix thanks for all your work.

**Comment by Magmusic** [comment]
![image](https://github.com/user-attachments/assets/00f873e7-0ad2-46d6-8270-3bcc27871194)

![image](https://github.com/user-attachments/assets/5a40b2f6-3fd6-4f5b-bbee-59c8e135af62)

**Comment by elishacloud** [comment]
Sorry, I don't know anything about OpenGL and don't plan to support it or work on it.  I have too much work here on dxwrapper.
