### ISSUE TITLE
[Doubt] Judge Dredd

### ISSUE THREAD

**Issue by SilentMRG** [elishacloud/dxwrapper#307]
Hello... =)

I'm testing the latest version with this title, and I noticed these errors in the log: "D3DAssemble Error: Failed to Assemble shader! - Shader@0x084F6A18(15,5-7): error X5485: rcp requires replicate swizzle for the source parameter in order to select component. i.e. .x | .y | .z | .w (or rgba equivalent)".

Should I be worried about this? Well, here's the log: [dxwrapper-dredd.log](https://github.com/user-attachments/files/17387571/dxwrapper-dredd.log)

I'm using this: https://www.byeclan.be/dredd_vs_death/
To receive widescreen + correct FOV. Maybe these things aren't speaking correctly to each other...

Or maybe it's a mistake on my side, you know, Windows 7 and iGPU from the time of chipped stone.
I just want to say that everything is working perfectly within the game, with no graphical oddities or any other errors; and this is another D3D8 game that didn't show that error when closing the game. :)

Thank you in advance for your attention...
Best regards!

**Comment by elishacloud** [comment]
This looks like a bug in `d3d8to9` shader code.  Missing shaders can cause visual issues with the game.  However, it should not cause a crash or anything like that.

I need to see the original shader code before it gets modified and the updated modified code.  I will create a build for you so you can give me the log and I can see the shader code.

**Comment by elishacloud** [comment]
After looking at the code, I believe this is nothing to worry about.  d3d8to9 attempts to convert the shader to v1.4.  If that fails then it just does the normal conversion to Direct3D9, which presumably succeeds, since there is no log about it failing the second time.

Because the game is working fine, I suspect that is all that is happening here.  I believe this error can safely be ignored.

**Comment by SilentMRG** [comment]
Thank you very much for the information Elisha!
I thought it was something serious enough to make my potato explode. XD
