### ISSUE TITLE
New Worlds

### ISSUE THREAD

**Issue by LAguido** [elishacloud/dxwrapper#31]
Hello, I've been trying to get Star Trek New Worlds to run, with 
DDrawCompat= 1
DSoundCtrl= 1
I do get into the game, however after a few seconds it just freezes.
I'm using compatibility mode for windows 7, 16 bit color mode, disabled optimizations for full screen.
I've added the logfile I got from Process Monitor:
[Logfile.zip](https://github.com/elishacloud/dxwrapper/files/2392701/Logfile.zip)
I got the feeling I'm missing something really small, since it does start and you can move around for a few seconds.
(Edited with new logfile, previous didn't properly include the whole game session)

**Comment by LAguido** [comment]
[dxwrapper-stnw.log](https://github.com/elishacloud/dxwrapper/files/2397755/dxwrapper-stnw.log)
Here's the wrapper log when the issue occurs

**Comment by elishacloud** [comment]
It looks like the game is crashing.  Try setting `DSoundCtrl = 0`.  Also try adding this line into the ini file: `HandleExceptions = 0`.  This will allow you to see the crash.

If that does not work, try using the attached updated files.  This works with _Star Trek Armada 1_ and _Star Trek Armada 2_.

[ddraw.zip](https://github.com/elishacloud/dxwrapper/files/2398043/ddraw.zip)

**Comment by LAguido** [comment]
The 2 settings seemed to have worked (at least it doesn't crash in 10 seconds), I did not use the Armada files. The game needed to be launched from a FAT32 usb stick or partition to work properly. I didn't have time to test the game properly but thus far it seems ok!

**Comment by elishacloud** [comment]
Closing this since the issue seems to be resolved.  If the issue comes back you can reopen.
