### ISSUE TITLE
update wiki for Creatures 2

### ISSUE THREAD

**Issue by Percherie** [elishacloud/dxwrapper#313]
Hi,

Can you update download file with last version.
I test and windows make betteer. With version purpose in download windows name "view of creature" is very lag or broken. With last dxwrapper is very better

https://github.com/elishacloud/dxwrapper/wiki/Creatures-2-The-Albian-Years#download

**Comment by elishacloud** [comment]
Thanks for pointing this out.  I have added several fixes for this game in the latest build.  It should be 100% working as long as you have `Dd7to9` enabled and `DdrawOverrideBitMode` set to `16`.

I updated the wiki.  It has the latest version of dxwrapper now.

**Comment by Percherie** [comment]
Great... I'm amazed by the work you've done. It's a success. congratulations.
