### ISSUE TITLE
FullscreenWindowMode broken with commit 38d6363 and D3D9 games like CoD2/4

### ISSUE THREAD

**Issue by LuKeSt0rm** [elishacloud/dxwrapper#324]
`FullscreenWindowMode` no longer works with commit https://github.com/elishacloud/dxwrapper/commit/38d6363a7eaeef69bcd7edc7693e9211c01598f8 for D3D9 games such as Call of Duty 2 and Call of Duty 4 (tested ones)
Worked before without issues.

**Comment by elishacloud** [comment]
Thanks for tracking this down!  I suspect it is [this code](https://github.com/elishacloud/dxwrapper/commit/38d6363a7eaeef69bcd7edc7693e9211c01598f8#diff-486d61cdbc37b95dc23963f71226f6c6488d0bb0b0c09bf8fa0b2475ee561997R294-R297) causing the issue.  I need to filter out these messages as some DirectDraw games cannot handle those messages.  I guess Direct3D9 games don't have that issue.

Try this build and let me know if it solves the issue or not:  [dxwrapper.zip](https://github.com/user-attachments/files/18088149/dxwrapper.zip)
