### ISSUE TITLE
Enabling disable high DPI setting doesn't work

### ISSUE THREAD

**Issue by majimboo** [elishacloud/dxwrapper#33]
Hello,

I have  a game that works when I manually set the disable high dpi setting or set it to Application. To save a few clicks (of going to properties and setting high dpi) I decided to use this. But unfortunately setting it on the `.ini` doesn't really do the same thing as manually going through properties..

```
16000 16:27:12.202 Starting DxWrapper v1.0.2383.20 DDrawCompat v0.2.1 DxWnd v2.03.60
16000 16:27:12.204 Windows 10 64-bit (10.0.17763) 
16000 16:27:12.204 Intel(R) UHD Graphics 620
16000 16:27:12.204 Game.exe (PID:18168)
16000 16:27:12.204 Reading config file: dxwrapper.ini
16000 16:27:12.204 Enabling d3d8to9 wrapper
16000 16:27:12.204 Loaded library: kernel32.dll
16000 16:27:12.204 Hooking 'GetModuleFileName' API...
16000 16:27:12.204 Disabling High DPI Scaling...
16000 16:27:12.205 Set exception handler
16000 16:27:12.205 Finished setting exception handler
16000 16:27:12.209 Hooking d3d8.dll APIs...
16000 16:27:12.213 Loaded library: d3d9.dll
16000 16:27:12.227 Enabling D3d8to9 function (220)
16000 16:27:12.988 Enabling D3d8to9 function (220)
```

This is the compatibility settings I use to make it work. I was hoping that I could use dxwrapper so I don't have to manually set the compatibility setting. Specially when redistributing.

**Comment by elishacloud** [comment]
Yeah, I saw this on another game also (don't remember which one though).  I will look into this when I get a chance.  Thanks!

**Comment by elishacloud** [comment]
@majimboo, I recently put a fix in that may address this.  Can you try with the attached version?

Download it here: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/3155552/dxwrapper.zip)

**Comment by elishacloud** [comment]
Closing this issue.  It should be fixed with the latest release.
