### ISSUE TITLE
Chaser (CloakNT 1.x) Support

### ISSUE THREAD

**Issue by Saijin-Naib** [elishacloud/dxwrapper#39]
Looks like DXWrapper successfully can wrap Chaser!

```
18768 22:42:04.701 Starting DxWrapper v1.0.6298.21
18768 22:42:04.701 To Be Filled By O.E.M. To Be Filled By O.E.M. To Be Filled By O.E.M. (Desktop)
18768 22:42:04.701 ASRock B150M-ITX                        (Desktop)
18768 22:42:04.701 NVIDIA GeForce GTX 1050 Ti
18768 22:42:04.705 Windows 10 64-bit (10.0.18970) 
18768 22:42:04.705 "Chaser.exe" (PID:636)
18768 22:42:04.713 Steam game detected!
18768 22:42:04.713 DxWrapper already running!
18768 22:42:04.713 Quiting DxWrapper
18768 22:42:04.713 Unloading DxWnd
18768 22:42:04.713 Unloading libraries...
18768 22:42:04.713 Reseting screen resolution
18768 22:42:04.740 DxWrapper terminated!

```

**Comment by elishacloud** [comment]
From the log files it looks like you have not enabled any settings, so dxwrapper is not doing anything.  What are you trying to do here?

**Comment by Saijin-Naib** [comment]
`18124 22:25:15.815 Starting DxWrapper v1.0.6298.21
18124 22:25:15.815 To Be Filled By O.E.M. To Be Filled By O.E.M. To Be Filled By O.E.M. (Desktop)
18124 22:25:15.815 ASRock B150M-ITX                        (Desktop)
18124 22:25:15.815 NVIDIA GeForce GTX 1050 Ti
18124 22:25:15.820 Windows 10 64-bit (10.0.18970) 
18124 22:25:15.820 "Chaser.exe" (PID:18688)
18124 22:25:15.828 Steam game detected!
18124 22:25:15.828 DxWrapper already running!
18124 22:25:15.828 Quiting DxWrapper
18124 22:25:15.828 Unloading DxWnd
18124 22:25:15.828 Unloading libraries...
18124 22:25:15.828 Reseting screen resolution
18124 22:25:15.850 DxWrapper terminated!
`
I enabled the Dx8to9 library and an antialias over-ride to test.

I'm trying to test why your build works fine with Chaser whereas Reshade and crosire's build causes Chaser to crash before launch.

**Comment by elishacloud** [comment]
@Saijin-Naib, d3d8to9 has not been initialized.  You need to have the following events in the log file for d3d8to9 to function:

```txt
15784 19:27:28.426 Starting D3d8to9 v1.9.2.0
15784 19:27:28.426 Redirecting 'Direct3DCreate8' to --> 'Direct3DCreate9' (220)
15784 19:27:28.426 Redirecting 'Direct3DCreate9' ...
15784 19:27:28.460 Loading d3dx9_xx.dll
15784 19:27:28.723 Loaded library: d3dx9_43.dll
```

Also from your log files it looks like you are using more than one stub.  You should only be using one stub.  Try deleting all but one of the stub files.  See these items in the log:

```txt
18124 22:25:15.828 DxWrapper already running!
18124 22:25:15.828 Quiting DxWrappe
``

Can you send me a copy of the ini file you are using?

**Comment by Saijin-Naib** [comment]
`11944 23:04:53.984 Starting DxWrapper v1.0.6298.21
11944 23:04:53.984 To Be Filled By O.E.M. To Be Filled By O.E.M. To Be Filled By O.E.M. (Desktop)
11944 23:04:53.984 ASRock B150M-ITX                        (Desktop)
11944 23:04:53.984 NVIDIA GeForce GTX 1050 Ti
11944 23:04:53.985 Windows 10 64-bit (10.0.18970) 
11944 23:04:53.985 "Chaser.exe" (PID:11136)
11944 23:04:53.992 Steam game detected!
11944 23:04:53.992 Loaded library: kernel32.dll
11944 23:04:53.992 Hooking 'GetModuleFileName' API...
11944 23:04:53.992 Disabling High DPI Scaling...
11944 23:04:53.992 Loaded library: user32.dll
11944 23:04:53.994 Loaded library: shcore.dll
11944 23:04:53.994 Enabling d3d8to9 wrapper
11944 23:04:53.994 Loading 'd3d8.dll'...
11944 23:04:53.995 Hooking d3d8.dll APIs...
11944 23:04:53.995 Enabling d3d9 wrapper
11944 23:04:53.995 Loading 'd3d9.dll'...
11944 23:04:54.001 DxWrapper loaded!
11944 23:04:54.908 Starting D3d8to9 v1.9.2.0
11944 23:04:54.908 Redirecting 'Direct3DCreate8' to --> 'Direct3DCreate9' (220)
11944 23:04:54.908 Redirecting 'Direct3DCreate9' ...
11944 23:04:54.958 Loading d3dx9_xx.dll
11944 23:04:55.189 Loaded library: d3dx9_43.dll
`
I've attached the log from launching the game with only the one stub file. That looks correct, right?

Here's the ini I'm using. Bare-bones to the extreme, just trying to prove that DxWrapper can actually wrap Chaser as I continue to try to get Reshade to play nice with it.
[dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/3564334/dxwrapper.zip)

**Comment by elishacloud** [comment]
Closing.  You can reopen if you still have an issue.
