### ISSUE TITLE
Blood Omen 2 Fix no longer working

### ISSUE THREAD

**Issue by TheLawfulGeek** [elishacloud/dxwrapper#43]
As the subject name states, the Blood Omen 2 fix no longer works, with the log citing numero
us exceptions. Could be compatibility issues with the latest graphics card drivers or even windows updates. 

Attached log as reference. 
[d3d8-bo2.log](https://github.com/elishacloud/dxwrapper/files/3659894/d3d8-bo2.log)

**Comment by elishacloud** [comment]
Yes, that is a very old build.  I have not updated it in a while.  The this build below.  Unzip all three files into the Blood Omen 2 game folder.

[dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/3660425/dxwrapper.zip)

**Comment by solhuebner** [comment]
@TheLawfulGeek did it fix your issue?

**Comment by BParks21** [comment]
@TheLawfulGeek Having this same problem with my 2070 super. Is it working for you now?

**Comment by elishacloud** [comment]
@solhuebner, @BParks21, I have recently updated the wiki with a new build.  You can download it here:
https://github.com/elishacloud/dxwrapper/wiki/Legacy-of-Kain-Blood-Omen-2

Let me know if you still have issues with this update.  If you have issues, please post your logs as well.

**Comment by elishacloud** [comment]
Closing the issue.
