### ISSUE TITLE
Disable Dxwnd Banner?

### ISSUE THREAD

**Issue by AlbertHamik** [elishacloud/dxwrapper#44]
How does one disable it in the dxwrapper version?

**Comment by elishacloud** [comment]
In the latest version if dxwrapper DxWnd is disabled by default.  However, to disable it manually just add a line to the ini file that says:

```ini
DxWnd = 0
```

See this page for all basic settings:  [wiki Configuration](https://github.com/elishacloud/dxwrapper/wiki/Configuration#compatibility)

**Comment by AlbertHamik** [comment]
I think you misunderstood the question. I know how to disable Dxwnd, I meant how do you disable the Dxwnd logo that appears when you start a program with it enabled. In normal Dxwnd, you can manually set a program to have no startup logo/banner, but how do you disable it in the dxwnd.ini for DXWrapper?

**Comment by elishacloud** [comment]
You need to use the version of DxWnd that comes with dxwrapper.  Just run the DxWnd.exe file that is included in the zip file and follow the steps below:

1. Either add anew item if none exists or modify the existing item.
2. Enable option that says "No banner".

![image](https://user-images.githubusercontent.com/25625456/67548918-f61c2b00-f6b7-11e9-9583-f717184b5e3c.png)

**Comment by AlbertHamik** [comment]
Oh, okay. Pretty interesting how that works then.

**Comment by elishacloud** [comment]
Closing issue.
