### ISSUE TITLE
Issues in the latest versions (stub files)

### ISSUE THREAD

**Issue by JaegerFox** [elishacloud/dxwrapper#48]
This happens only for now in GTA San Andreas, using an earlier version of the stub file (v1.0.2383.20), but with the latest version of dxwrapper.dll the game works fine, but when using the stub of the latest version the game does not start and does not even create the log files
by the way, im renaming any stub file to vorbisFile.dll, or d3d9.dll

**Comment by elishacloud** [comment]
`vorbisFile.dll` is not supported.  First make sure to delete all extra files that the game did not come with.  Then try the build below:

[dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/3820592/dxwrapper.zip)

The log file should be namedsomething like `dxwrapper-gta-san.log`.

**Comment by JaegerFox** [comment]
![Image 3](https://user-images.githubusercontent.com/29095345/68410752-e0dedc00-014e-11ea-8562-a2e3ddea328e.jpg)

**Comment by elishacloud** [comment]
Does the game work without dxwrapper?

Try this update: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/3862441/dxwrapper.zip)

**Comment by JaegerFox** [comment]
still the same problem.
This happens when I have the option to load the scripts, but I will only use Ultimate Asi Loader
I don't know if it affects something to use the name d3d9 and vorbisFile, the order or priority that these are loaded and some scripts require to be loaded first than d3d9, well that's what I think .. you will know more about this
You can close this issue if you want
Thank you for your help
