### ISSUE TITLE
Star Trek Armada (1) not starting

### ISSUE THREAD

**Issue by BDevGW** [elishacloud/dxwrapper#49]
So I followed the tutorial and anstalled Armada from my CD, then installed 1.2 and 1.3 and then put the three files in Armada's root directory (and overwrote the old three).
After it hasn't worked I enabled compatibillity (Windows suggested Windows XP SP2 level), changed to 16 bit color mode and enabled "run as admin".

When I start it the screen changes the resolution a few times between (i guess) 640x480 and back to normal, the little splash image is centered in my screen, the screen turns black for 1/2 second and the program stops.

Is the german version supported by your patch?

**Comment by elishacloud** [comment]
@BDevGW, I never tested with the German version, but I see no reason why it would not work.

First disable all compatibility settings.  Secondly try this new update: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/3867991/dxwrapper.zip).  I put some fixes in here that may fix your issue.  If you still have issues please attach your log file.

**Comment by BDevGW** [comment]
Still not working. Completely removed Armada, reinstalled it, rebooted, instlled patch 1.2, installed patch 1.3, copied the contents of the zip into the games rootfolder.

Here is a video how startup looks like: https://youtu.be/8BcM92ETpHY
Also checkt taskimgr, no Amarda in background.

**Comment by ifrh** [comment]
@elishacloud : I am trying to start Star Trek Armada (CD is german version 1.0 for Windows 95/98) 
on Windows 10  Version 21H1 Build  19043.1889 (german , 64bit)

Installation went well.

As mentioned on https://github.com/elishacloud/dxwrapper/wiki/Star-Trek-Armada-1 
I downloaded from:
- http://armadafiles.com/files/armada/official-releases/patches/star-trek-armada-1-1-patch/details
- http://armadafiles.com/files/armada/official-releases/patches/star-trek-armada-12-patch/details
- http://armadafiles.com/files/armada/mods/patches/star-trek-armada-patch-1-3-project/details

I had installed Patch 1.2 and 1.3.

And I used the [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/3867991/dxwrapper.zip) you, elishacloud , mentioned in https://github.com/elishacloud/dxwrapper/issues/49#issuecomment-555887194.

The description of @BDevGW fits to my observation:
> When I start it the screen changes the resolution a few times between (i guess) 640x480 and back to normal, the little splash image is centered in my screen, the screen turns black for 1/2 second and the program stops.

dxdiag informs about:
- DirectX Version: DirectX 12
- DX Setup Parameters: Not found
- User DPI Setting: 96 DPI (100 percent)
- System DPI Setting: 96 DPI (100 percent)
- DWM DPI Scaling: Disabled
- Microsoft Graphics Hybrid: Not Supported
- [...]
- Card name: Intel(R) HD Graphics
- Manufacturer: Intel Corporation
- Chip type: Intel(R) HD Graphics
- DAC type: Internal
- Device Type: Full Device (POST)
- Device Key: Enum\PCI\VEN_8086&DEV_22B1&SUBSYS_8342103C&REV_35
- Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
- Device Problem Code: No Problem
- [...]
- Driver Name: igdumdim64.dll,igd10iumd64.dll,igd10iumd64.dll,igd12umd64.dll
- Driver File Version: 20.19.0015.4835 (English)
- Driver Version: 20.19.15.4835
- DDI Version: 12
- Feature Levels: 11_1,11_0,10_1,10_0,9_3,9_2,9_1
- Driver Model: WDDM 2.0

You asked for the enties of file `dxwrapper-armada.log` : 
```

3256 11:23:07.069 Starting DxWrapper v1.0.6341.21
3256 11:23:07.069 HP HP Laptop 17-bs0xx Type1ProductConfigId (Notebook)
3256 11:23:07.069 HP 8342 50.37 (Notebook)
3256 11:23:07.069 Intel(R) HD Graphics
3256 11:23:07.123 Windows 10 64-bit (10.0.19041) 
3256 11:23:07.123 "Armada.exe" (PID:7348)
3256 11:23:07.138 Disabling High DPI Scaling...
3256 11:23:07.138 Loaded library: user32.dll
3256 11:23:07.138 Loaded library: shcore.dll
3256 11:23:07.138 Loading 'ddraw.dll'...
3256 11:23:07.138 Hooking ddraw.dll APIs...
3256 11:23:07.138 Enabling DDrawCompat
3256 11:23:07.138 Enabling ddraw wrapper
3256 11:23:07.138 Process path: C:\Spiele\bit32\StarTrek_Armada\Armada.exe
3256 11:23:07.138 Loading DDrawCompat from C:\Spiele\bit32\StarTrek_Armada\dxwrapper.dll
3256 11:23:07.169 Loaded library: uxtheme.dll
3256 11:23:07.201 DDrawCompat v0.2.1 loaded successfully
3256 11:23:07.201 DxWrapper loaded!
3256 11:23:07.201 dd_DirectDrawCreateEx
3256 11:23:07.201 Redirecting 'DirectDrawCreateEx' ...
3256 11:23:07.201 Installing DirectDraw hooks
3256 11:23:07.386 Installing GDI hooks
3256 11:23:07.470 Installing registry hooks
3256 11:23:07.470 Finished installing hooks
3256 11:23:07.486 Creating device m_IDirectDrawX::m_IDirectDrawX(009DDAD8) v7
3256 11:23:07.517 m_IDirectDrawX::~m_IDirectDrawX(009DDAD8) deleting device!
3256 11:23:07.517 Loaded library: dwmapi.dll
3256 11:23:07.524 Redirecting 'DirectDrawCreateEx' ...
3256 11:23:07.524 Creating device m_IDirectDrawX::m_IDirectDrawX(009DE088) v7
3256 11:23:07.539 Creating device m_IDirect3DX::m_IDirect3DX(00A185C0) v7
3256 11:23:07.539 m_IDirect3DX::ResolutionHack Found loaded dll: 'd3dim700.dll'
3256 11:23:07.657 Failed to find the requested display mode: 640x480x32
3256 11:23:07.860 m_IDirect3DX::~m_IDirect3DX(00A185C0) deleting device!
3256 11:23:07.860 m_IDirectDrawX::~m_IDirectDrawX(009DE088) deleting device!
3256 11:23:08.154 Redirecting 'DirectDrawCreateEx' ...
3256 11:23:08.154 Creating device m_IDirectDrawX::m_IDirectDrawX(009DD938) v7
3256 11:23:08.162 Creating device m_IDirect3DX::m_IDirect3DX(00A18380) v7
3256 11:23:08.256 Failed to find the requested display mode: 640x480x32
3256 11:23:08.345 m_IDirect3DX::~m_IDirect3DX(00A18380) deleting device!
3256 11:23:08.345 m_IDirectDrawX::~m_IDirectDrawX(009DD938) deleting device!
3256 11:23:08.560 Creating device m_IDirectDrawPalette::m_IDirectDrawPalette(00A1A220)
3256 11:23:09.346 Failed to find the requested display mode: 640x480x32
3256 11:23:09.346 m_IDirectDrawPalette::~m_IDirectDrawPalette(00A1A220) deleting device!
3256 11:23:09.561 Creating device m_IDirectDrawPalette::m_IDirectDrawPalette(00A1A060)
3256 11:23:10.287 Failed to find the requested display mode: 640x480x32
3256 11:23:10.287 m_IDirectDrawPalette::~m_IDirectDrawPalette(00A1A060) deleting device!
3256 11:23:10.699 Quiting DxWrapper
3256 11:23:10.699 Detaching DDrawCompat
3256 11:23:10.753 DDrawCompat detached successfully
3256 11:23:10.753 Unloading libraries...
3256 11:23:10.753 Reseting screen resolution
3256 11:23:10.768 Reseting font smoothing
3256 11:23:10.768 DxWrapper terminated!
```

**Comment by elishacloud** [comment]
Ok, try with the following update.  Unzip this into the Armada folder, overwriting any existing files:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/9398691/dxwrapper.zip)

**Comment by ifrh** [comment]
@elishacloud Thank you for your update. I tried... but some buffers are not found (vertex buffers and index buffers).

```
26200 18:30:15.662 Starting DxWrapper v1.0.6569.21
26200 18:30:15.662 Running from: C:\Spiele\bit32\StarTrek_Armada\dxwrapper.dll
26200 18:30:15.662 Reading config file: C:\Spiele\bit32\StarTrek_Armada\dxwrapper.ini
26200 18:30:15.662 HP HP Laptop 17-bs0xx Type1ProductConfigId (Notebook)
26200 18:30:15.662 HP 8342 50.37 (Notebook)
26200 18:30:15.662 Intel(R) HD Graphics
26200 18:30:15.662 Windows 10 Home 64-bit (10.0.19041)
26200 18:30:15.662 Armada.exe (PID:26208)
26200 18:30:15.677 Environment variable __COMPAT_LAYER = "DWM8And16BitMitigation DisableDXMaximizedWindowedMode"
26200 18:30:15.677 Disabling High DPI Scaling...
26200 18:30:15.677 Loaded library: user32.dll
26200 18:30:15.677 Loaded library: shcore.dll
26200 18:30:15.677 Loading 'ddraw.dll'...
26200 18:30:15.677 Hooking ddraw.dll APIs...
26200 18:30:15.677 Enabling DDrawCompat
26200 18:30:15.677 Enabling ddraw wrapper
26200 18:30:15.677 Process path: C:\Spiele\bit32\StarTrek_Armada\Armada.exe
26200 18:30:15.677 Loading DDrawCompat dynamically from C:\Spiele\bit32\StarTrek_Armada\dxwrapper.dll
26200 18:30:15.693 Loaded library: winmm.dll
26200 18:30:15.700 Loaded library: uxtheme.dll
26200 18:30:15.777 DDrawCompat v0.3.1 version loaded successfully
26200 18:30:15.777 DxWrapper loaded!
26200 18:30:15.778 dd_DirectDrawEnumerateExA
26200 18:30:15.778 Installing display mode hooks
26200 18:30:15.804 Installing registry hooks
26200 18:30:15.804 Installing Direct3D driver hooks
26200 18:30:15.805 Installing Win32 hooks
26200 18:30:15.821 Hooking user mode display driver: C:\WINDOWS\SYSTEM32\igdumdim32.dll+0x21b00
26200 18:30:15.834 Dynamic vertex buffers are not available
26200 18:30:15.834 Dynamic index buffers are not available
26200 18:30:15.836 Checking source color key support: passed
26200 18:30:15.846 Installing DirectDraw hooks
26200 18:30:15.848 Installing Direct3D hooks
26200 18:30:15.859 Installing GDI hooks
26264 18:30:15.916 Loaded library: dwmapi.dll
26200 18:30:15.917 Finished installing hooks
26200 18:30:15.945 dd_DirectDrawCreateEx
26200 18:30:15.945 Redirecting 'DirectDrawCreateEx' ...
26200 18:30:15.968 Creating interface m_IDirectDrawX::m_IDirectDrawX (00AFD8B8) v7
26200 18:30:15.974 m_IDirectDrawX::~m_IDirectDrawX (00AFD8B8) deleting interface!
26200 18:30:16.135 Redirecting 'DirectDrawCreateEx' ...
26200 18:30:16.224 Creating interface m_IDirectDrawX::m_IDirectDrawX (00AFD0C0) v7
26200 18:30:16.224 Creating interface m_IDirect3DX::m_IDirect3DX (00B3DA10) v7
26200 18:30:16.225 m_IDirect3DX::ResolutionHack Found loaded dll: 'd3dim.dll'
26200 18:30:16.225 m_IDirect3DX::ResolutionHack Found loaded dll: 'd3dim700.dll'
26200 18:30:16.548 m_IDirectDrawX::~m_IDirectDrawX (00AFD0C0) deleting interface!
26200 18:30:16.923 Redirecting 'DirectDrawCreateEx' ...
26200 18:30:16.966 Creating interface m_IDirectDrawX::m_IDirectDrawX (00AFCAA8) v7
26200 18:30:16.966 Creating interface m_IDirect3DX::m_IDirect3DX (00B3D790) v7
26200 18:30:17.356 m_IDirectDrawX::~m_IDirectDrawX (00AFCAA8) deleting interface!
26200 18:30:17.854 Creating interface m_IDirectDrawPalette::m_IDirectDrawPalette (00B2F860)
26200 18:30:18.577 m_IDirectDrawPalette::~m_IDirectDrawPalette (00B2F860) deleting interface!
26200 18:30:19.196 m_IDirectDrawX::SetCooperativeLevel Removing window WS_CAPTION!
26200 18:30:19.250 Creating interface m_IDirectDrawPalette::m_IDirectDrawPalette (00B2F780)
26200 18:30:19.893 m_IDirectDrawPalette::~m_IDirectDrawPalette (00B2F780) deleting interface!
26200 18:30:20.165 Quiting DxWrapper
26200 18:30:20.165 DDrawCompat detached successfully
26200 18:30:20.166 Unloading libraries...
26200 18:30:20.166 Reseting screen resolution

```

**Comment by ifrh** [comment]
Just to check, what content the log file of an other dxwrapper.zip (mentioned on 15 April 2021, in https://github.com/elishacloud/dxwrapper/issues/121#issuecomment-820175971 ) would have:

```
18296 18:45:54.088 Starting DxWrapper v1.0.6492.21
18296 18:45:54.088 HP HP Laptop 17-bs0xx Type1ProductConfigId (Notebook)
18296 18:45:54.088 HP 8342 50.37 (Notebook)
18296 18:45:54.088 Intel(R) HD Graphics
18296 18:45:54.088 Windows 10 Home 64-bit (10.0.19041)
18296 18:45:54.088 "Armada.exe" (PID:10504)
18296 18:45:54.108 Environment variable __COMPAT_LAYER = "DWM8And16BitMitigation DisableDXMaximizedWindowedMode"
18296 18:45:54.108 Disabling High DPI Scaling...
18296 18:45:54.108 Loaded library: user32.dll
18296 18:45:54.108 Loaded library: shcore.dll
18296 18:45:54.108 Loading 'ddraw.dll'...
18296 18:45:54.108 Hooking ddraw.dll APIs...
18296 18:45:54.108 Enabling DDrawCompat
18296 18:45:54.108 Enabling ddraw wrapper
18296 18:45:54.108 Process path: C:\Spiele\bit32\StarTrek_Armada\Armada.exe
18296 18:45:54.108 Loading DDrawCompat from C:\Spiele\bit32\StarTrek_Armada\dxwrapper.dll
18296 18:45:54.138 Loaded library: uxtheme.dll
18296 18:45:54.138 DDrawCompat v0.2.1 loaded successfully
18296 18:45:54.138 DxWrapper loaded!
18296 18:45:54.138 dd_DirectDrawEnumerateExA
18296 18:45:54.138 dd_DirectDrawCreateEx
18296 18:45:54.138 Redirecting 'DirectDrawCreateEx' ...
18296 18:45:54.138 Installing DirectDraw hooks
18296 18:45:54.298 Installing GDI hooks
18296 18:45:54.398 Installing registry hooks
18296 18:45:54.398 Finished installing hooks
18296 18:45:54.414 Creating interface m_IDirectDrawX::m_IDirectDrawX (0091A8A0) v7
18296 18:45:54.445 m_IDirectDrawX::~m_IDirectDrawX (0091A8A0) deleting interface!
18296 18:45:54.461 Loaded library: dwmapi.dll
18296 18:45:54.467 Redirecting 'DirectDrawCreateEx' ...
18296 18:45:54.467 Creating interface m_IDirectDrawX::m_IDirectDrawX (00925D08) v7
18296 18:45:54.483 Creating interface m_IDirect3DX::m_IDirect3DX (00911470) v7
18296 18:45:54.483 m_IDirect3DX::ResolutionHack Found loaded dll: 'd3dim700.dll'
18296 18:45:54.610 Failed to find the requested display mode: 640x480x32
18296 18:45:54.793 m_IDirectDrawX::~m_IDirectDrawX (00925D08) deleting interface!
18296 18:45:54.824 Redirecting 'DirectDrawCreateEx' ...
18296 18:45:54.834 Creating interface m_IDirectDrawX::m_IDirectDrawX (009257E0) v7
18296 18:45:54.934 Failed to find the requested display mode: 640x480x32
18296 18:45:55.332 m_IDirectDrawX::~m_IDirectDrawX (009257E0) deleting interface!
18296 18:45:55.679 Creating interface m_IDirectDrawPalette::m_IDirectDrawPalette (0090F968)
18296 18:45:56.467 Failed to find the requested display mode: 640x480x32
18296 18:45:56.469 m_IDirectDrawPalette::~m_IDirectDrawPalette (0090F968) deleting interface!
18296 18:45:56.863 m_IDirectDrawX::SetCooperativeLevel Removing window WS_CAPTION!
18296 18:45:56.863 Utils::SetWndProcFilter Setting new WndProc WND(000B06D6,Armada,{0,0,1600,900})
18296 18:45:56.865 Creating interface m_IDirectDrawPalette::m_IDirectDrawPalette (0090FA48)
18296 18:45:57.567 Failed to find the requested display mode: 640x480x32
18296 18:45:57.567 m_IDirectDrawPalette::~m_IDirectDrawPalette (0090FA48) deleting interface!
18296 18:45:57.682 Quiting DxWrapper
18296 18:45:57.682 Detaching DDrawCompat
18296 18:45:57.698 DDrawCompat detached successfully
18296 18:45:57.714 Unloading libraries...
18296 18:45:57.714 Reseting screen resolution
18296 18:45:57.814 Reseting font smoothing
18296 18:45:57.852 DxWrapper terminated!
  
```

**Comment by ifrh** [comment]
My next test using some other settings in ini-file creates some graphical and accustical output.

- I can hear the "audio track" belonging to video sequences. But I cannot see the video sequences.
- I can see the Game Main Menue (from my point of view annimated buttons work), while hearing background music.
- I can choose in single player mode a task, than I can hear again the voices and sound of a videosequence

But at time when the task of the game should start (I think it has started but was not visualised), I only saw the defunctionaled task menue and I could hear the background music. I did not saw a map or ship or some other interactive element.
Since I cannot play Armada blind [*], I used task manager to kill the process.

[*] let define "blind game playing" as knowing all key short cuts and mouse movements to fullfill the task without having graphical support. 
 
**Description of changes settings:**
- I took `ddraw.dll` and `dxwrapper.dll` from **DxWrapper v1.0.6569.21** out of zip-file ( linked above in https://github.com/elishacloud/dxwrapper/issues/49#issuecomment-1223423601 )  

- AND additional I copy `d3d9.dll` out of **DxWrapper v1.0.6542.21**  from zip-file mentioned on https://github.com/elishacloud/dxwrapper/releases/tag/v1.0.6542.21.

Here attached is my modificated `dxwrapper.ini` and the `dxwrapper-armada.log`

[StarTrek_Armada_dxwrapper_ini-and_log.zip](https://github.com/elishacloud/dxwrapper/files/9410577/StarTrek_Armada_dxwrapper_ini-and_log.zip)

**And here are some Screenshots**


![Armada_1-3_GameMainMenue_active](https://user-images.githubusercontent.com/3845055/186266158-cf67dccd-e08b-4931-813e-a6b95599f069.jpg)

![Armada_1-3_GameTaskMenue_active](https://user-images.githubusercontent.com/3845055/186266262-a2bc2b4c-548f-4e6d-b41f-d2e4e5f00b43.jpg)

![Armada_1-3_TaskHasStarted_TaskMenue_deactive](https://user-images.githubusercontent.com/3845055/186266416-92a41035-17df-4c2c-abfd-b5334b253c33.jpg)

@elishacloud From technical point of view I must say: Thank you for developing a DirectX wrapper :-) !

**Comment by elishacloud** [comment]
> Here attached is my modificated `dxwrapper.ini` and the `dxwrapper-armada.log`

Disable the following settings in the ini file:  `Dd7to9`, `EnableDdrawWrapper`, `ConvertToDirectDraw7`, `ConvertToDirect3D7`, `DdrawEmulateSurface`.  Some of these are not needed and others don't work with this game.

The following settings should be enabled:

```ini
DDrawCompat                = 1
EnableDdrawWrapper         = 1
DDrawCompat31              = 1
DdrawOverrideBitMode       = 32
```

If that does not work, you could try disabling `EnableDdrawWrapper`.  Also, make sure you are using [Armada patch 1.3](http://armadafiles.com/files/armada/mods/patches/star-trek-armada-patch-1-3-project/details) (after installing 1.2) and the [latest build of dxwrapper](https://github.com/elishacloud/dxwrapper/issues/49#issuecomment-1223423601).

**Comment by elishacloud** [comment]
You could also try it with only the following enabled.  You will lose the overlays on the first screen, but it may work for you.

```ini
EnableDdrawWrapper         = 1
DdrawOverrideBitMode       = 32
```

**Comment by ifrh** [comment]
Hi, 
You wrote that I `EnableDdrawWrapper` should disable the setting and than you wrote, that I should enable it.
Perhaps its a language barriere on my side. So I will try all cases, which you mentioned in you last two posts.

**Comment by elishacloud** [comment]
> You wrote that I `EnableDdrawWrapper` should disable the setting and than you wrote, that I should enable it.
> Perhaps its a language barriere on my side.

Sorry, I meant for several test cases to see if any of them work.

**Test 1**:  Use only the following settings:

```ini
DDrawCompat                = 1
EnableDdrawWrapper         = 1
DDrawCompat31              = 1
DdrawOverrideBitMode       = 32
```

**Test 2**: use only the following settings:


```ini
DDrawCompat                = 1
DDrawCompat31              = 1
```

**Test 3**: use only the following settings:

```ini
EnableDdrawWrapper         = 1
DdrawOverrideBitMode       = 32
```

**Comment by ifrh** [comment]
Sadly none of that settings worked for me, not even the Game Menue was shown. Only Splash-Screen with flickering black boxes and than after some seconds process terminates on its own.
Attached are three zip-files containing log and ini for each of your mentioned tests.

[StarTrek_Armada_Test1.zip](https://github.com/elishacloud/dxwrapper/files/9422229/StarTrek_Armada_Test1.zip)

[StarTrek_Armada_Test2.zip](https://github.com/elishacloud/dxwrapper/files/9422230/StarTrek_Armada_Test2.zip)

[StarTrek_Armada_Test3.zip](https://github.com/elishacloud/dxwrapper/files/9422233/StarTrek_Armada_Test3.zip)

Additionaly I did a test run via Dr.Memory ...
```
~~Dr.M~~ Dr. Memory version 2.5.0
~~Dr.M~~ Running "c:\Spiele\bit32\StarTrek_Armada\armada.exe"
~~Dr.M~~ Using system call file c:\Tools\DrMemory-Windows-2.5.0\drmemory\logs\symcache\syscalls_wow64.txt
~~Dr.M~~ ERROR: Failed to find "main" for limiting memory dump
~~Dr.M~~ WARNING: application is missing line number information.
~~Dr.M~~
~~Dr.M~~ Error #1: UNADDRESSABLE ACCESS: executing 0x00000000-0x00000001 1 byte(s)
~~Dr.M~~ # 0 <not in a module> (0x00000000)
~~Dr.M~~ Note: @0:00:11.632 in thread 6928
~~Dr.M~~ WARNING: application exited with abnormal code 0xc0000005
```

**Comment by ifrh** [comment]
I open Armada.exe inside dependens.exe and got information about unfindeable dlls.

![grafik](https://user-images.githubusercontent.com/3845055/186769193-be19c31c-aa84-4046-805b-21cec6733c80.png)

I found a `dsound.dll` and `winmm.dll` inside `dxwrapper_v1.0.6542.21\Stub` 
I think for videosequences the dependency to `avifil.dll` must be resolved - some how .
But how can MSVCP60.dll be emulated?

**Comment by ifrh** [comment]
@elishacloud  And I found that your in https://github.com/elishacloud/dxwrapper/issues/49#issuecomment-1223423601 mentioned last build of `dxwrapper.dll` itself has an unfullfilled dependency on my system.

![grafik](https://user-images.githubusercontent.com/3845055/186772095-727d4a3b-a6c6-4773-ac61-2414cd07860b.png)

**Comment by mirh** [comment]
MSVCP60 is available in the Visual Studio 1998 [redist](https://web.archive.org/web/20070602022840/support.microsoft.com/kb/259403) to be fair. 
But all those dlls are ***anyway*** present in my W10 SysWOW64 folder.

**Comment by ifrh** [comment]
> MSVCP60 is available in the Visual Studio 1998 [redist](https://web.archive.org/web/20070602022840/support.microsoft.com/kb/259403) to be fair. But all those dlls are _**anyway**_ present in my W10 SysWOW64 folder.

Well, yes ... in my SysWOW64  folder all "missed" dlls are there, too.  (Perhaps dependence can be configured to look into SysWOW64 as well.)

**Comment by mirh** [comment]
That's perfectly normal and windows already does it. 
I can only guess you are using some awfully broken/old/whatever version of dependency walker. 

I'm going out on a limb and still believe that your problem is with the intel drivers.

**Comment by elishacloud** [comment]
I think this is the same issue as #153.

There are two possible causes:

1. You have some compatibiity option enabled.  See below.  To fix this see the thread [here](https://github.com/CnCNet/cnc-ddraw/issues/159#issuecomment-1147173520).

```log
10716 08:50:12.682 Environment variable __COMPAT_LAYER = "DWM8And16BitMitigation DisableDXMaximizedWindowedMoe"
```

2. The other issue could be your Intel driver version, as @mirh mentioned.  Try updating to the latest Intel driver.

Here is what your log file says:

```log
10716 08:50:12.811 Hooking user mode display driver: C:\WINDOWS\SYSTEM32\igdumdim32.dll+0x21b00
```

Here is what it should look like:

```log
7224 07:29:55.434 Hooking user mode display driver: C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_91e2144e79bce669\igdumdim32.dll+0x9fc0
```

**Comment by mirh** [comment]
Mind me, it's a total roundabout uneducated shot in the dark. 
But this month I got wind of some potentially [horrendous](https://steamcommunity.com/app/17410/discussions/0/5815856057150996763/) matter and my expectations tanked.

**Comment by elishacloud** [comment]
Yeah, Intel GPUs are not ideal for gaming.  dgVoodoo2 is an option for this game, but it does not run well using that.  I recommend updating the drivers from the [Intel Update](https://www.intel.com/content/www/us/en/download-center/home.html) site.

**Comment by mirh** [comment]
Update: I have [reasons](https://www.vogons.org/viewtopic.php?f=8&t=86912) to believe all their Gen12 graphics is using D3D9On12. 

On the other hand, the guy that hijacked this thread is using device 0x22B1. That's the base HD graphics shipping into some older pentium/celeron. And `20.19.15.4835` is almost as ancient of a driver you can go, from 2017. 
It doesn't look like Intel has been releasing anything other than security fixes for it then, but to be sure they should check out the  [latest one](https://www.intel.com/content/www/us/en/download/18369/intel-graphics-driver-for-windows-15-40.html).

**Comment by ifrh** [comment]
> but to be sure they should check out the [latest one](https://www.intel.com/content/www/us/en/download/18369/intel-graphics-driver-for-windows-15-40.html).

Quote from:
https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html

> No supported driver or software updates are available for your system.
> HP Laptop 17-bs0xx   
> BIOS Version F.17 Date 2/26/2018
> Motherboard Manufacturer HP Model 8342 Version 50.37
> 
> Operating System 
> Edition: Microsoft Windows 10 Home (64-Bit)
> Version (Build): 21H1 (10.0.19043)
>
> Graphics Intel® HD Graphics
> A customized computer manufacturer driver is installed on your computer. The Intel Driver & Support Assistant is not able to update the driver. Installing a generic Intel driver instead of the customized computer manufacturer driver may cause technical issues. Contact [Hewlett-Packard (HP)](https://support.hp.com/us-en/drivers) for the latest driver for your computer.
>     Driver Details
>     Provider Intel Corporation
>     Version 20.19.15.4835
>     Date 10/16/2017

Quote from https://support.hp.com/us-en/product/detect/results?source=swd

> HP Web Product Detection
> HP Notebook - 17-bs075ng

This list of graphic card drivers were found on HP page. 
![grafik](https://user-images.githubusercontent.com/3845055/187763911-f6929745-a68f-4aea-8984-6e306e6f6b1e.png)

**Comment by elishacloud** [comment]
According to this site [here](https://support.hp.com/us-en/document/c05566935) you have a Intel® HD Graphics 400.  Here is the latest driver for your video card.  It is a lot newer (I think) than your current one:  https://www.intel.com/content/www/us/en/products/sku/91832/intel-celeron-processor-n3060-2m-cache-up-to-2-48-ghz/downloads.html

**Comment by ifrh** [comment]
Thanks for pointer to newer driver. But I cannot install them:

![grafik](https://user-images.githubusercontent.com/3845055/187787296-add88bae-83db-47e1-99b8-f4ba027850c1.png)

Message in short is: driver was not validated for your system. visit manufacturer website and take a driver from there.

**Comment by elishacloud** [comment]
Have you tried changing resolutions and other graphics settings in the Options menu before actually starting a mission?

**Comment by ifrh** [comment]
StarTrek Armada 1 : System Compatibility settings:

![grafik](https://user-images.githubusercontent.com/3845055/189047266-cd161d34-a287-474a-938f-bdee88b0536f.png)

StarTrek Armada 1 : Graphic options menue

![grafik](https://user-images.githubusercontent.com/3845055/189047587-63dbd0a1-6c77-4054-beb2-218d0cc1b325.png)

I can not choose an other graphic modus, there is only the activated one. 
And as graphic driver (Grafiktreiber) the only possibility is activated ...

Which Option do you mean, I should be able to switch to an other value?

**Comment by elishacloud** [comment]
It looks like you are using 640x480 8-bit mode.  I recommend changing his to a larger resolution at 32bit.  Try using your native screen resolution at 32bit.

Note: you have to click and hold the mouse button down to switch the resolution.

![image](https://user-images.githubusercontent.com/25625456/189241948-8b4ec7f8-dda7-4378-a1cd-e820a4597a07.png)

**Comment by ifrh** [comment]
As you can see in this small screencast there are no options for me to change driver or display mode...


https://user-images.githubusercontent.com/3845055/189278575-19301097-0fdc-40f5-8bd9-f47f625e507d.mp4

**Comment by ifrh** [comment]
> StarTrek Armada 1 : System Compatibility settings:
> 
> ![grafik](https://user-images.githubusercontent.com/3845055/189047266-cd161d34-a287-474a-938f-bdee88b0536f.png)
> 
mhm in registry there exists some compatibility settings ...
![grafik](https://user-images.githubusercontent.com/3845055/189482499-7372a38f-500a-4a84-ac95-3d4d8a429777.png)

well, lets try what happen, if I delete this entry.

**Comment by ifrh** [comment]
> well, lets try what happen, if I delete both entries.

After deleting registry keys mentioned `Armade.exe`  in 

- `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers`
- ` Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Compatibility Assistant\Store`

and rebooting the system, sadly behavior is identical as before: Inside Armada I cannot change graphic driver or settings and cannot play a mission.

**Comment by ifrh** [comment]
there was one more entry in registry setting a compatibily value for armada.exe:

- Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers

deleting that value too, did not help ...
In dxwrapper-armada.log is noted:
> 12216 14:58:55.973 Environment variable __COMPAT_LAYER = "DWM8And16BitMitigation"

**Comment by mirh** [comment]
Can you try [dgv](http://dege.freeweb.hu/) or [D3D9On12](https://github.com/narzoul/ForceD3D9On12) to even prove it's a graphical matter to begin with?
Also.. did you even update your drivers eventually?

**Comment by ifrh** [comment]
exchanging dxwrapperfiles with files 
- 3dfxspl2.dll
- 3dfxspl3.dll
- D3D8.dll
- D3D9.dll
- D3DImm.dll
- d3drm.dll
- DDraw.dll
- Glide.dll
- Glide2x.dll
- Glide3x.dll

from dgVoodoo2 ([3DfxSplashDlls.zip](http://dege.freeweb.hu/dgVoodoo2/bin/3DfxSplashDlls.zip), [D3DRM.zip](http://dege.freeweb.hu/dgVoodoo2/bin/D3DRM.zip) , [dgVoodoo v2.79.3](http://dege.freeweb.hu/dgVoodoo2/bin/dgVoodoo2_79_3.zip) )
resulting in visible video-sequences and loadable missions. But Armada-Options.Menue is not openable. 
![grafik](https://user-images.githubusercontent.com/3845055/189545564-8a7b9652-5fa4-4838-882e-dfa7daeeff6a.png)

**Comment by ifrh** [comment]
> Also.. did you even update your drivers eventually?

I did not update the drivers, because of error message at the time I tried to update the driver, see my former comment:
https://github.com/elishacloud/dxwrapper/issues/49#issuecomment-1233435505
Message in short is: "driver was not validated for your system. visit manufacturer website and take a driver from there."
But on manufacturer website (HP) there is no newer driver.

**Comment by ifrh** [comment]
As I can see via ProcessExplorer two dgVoodoo files were used...
![grafik](https://user-images.githubusercontent.com/3845055/189546710-46ad4038-5b02-4cab-b31d-15542e12dbab.png)

**Comment by mirh** [comment]
Follow the instructions [here](https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html).

**Comment by elishacloud** [comment]
I just posted an update patch that should address this issue.  You can see the update here:  [Star Trek Armada 1 patch](https://github.com/elishacloud/dxwrapper/wiki/Star-Trek-Armada-1)

**Comment by elishacloud** [comment]
This issue should be fixed with the latest update here:  https://github.com/elishacloud/dxwrapper/wiki/Star-Trek-Armada-1
