### ISSUE TITLE
Resolution for Hitman 2 Silent Assassin

### ISSUE THREAD

**Issue by donchen** [elishacloud/dxwrapper#51]
I try to edit hitman2.ini, modify "Resolution 1920x1080";
But there was an error window:

"
![无标题](https://user-images.githubusercontent.com/809035/69792192-1ed89880-1201-11ea-93fe-aa7923db1b08.jpg)
"
How can I use 1920x1080 in this game?

**Comment by donchen** [comment]
Just use window mode,the problem has been solved.

**Comment by elishacloud** [comment]
Closing the issue.
