### ISSUE TITLE
When running multiple instances, shutting down one instance will forcefully terminate all others (Final Fantasy XI)

### ISSUE THREAD

**Issue by onetwothreefive** [elishacloud/dxwrapper#55]
The game itself runs great, but as title notes, if running multiple instances of the game, upon shutting one down, any other open instances will freeze up for a few seconds, then crash. This is using d3d8to9. The log does not show anything particularly interesting, just messages saying it's quitting, unloading libraries etc.

I'm wondering if this might be because it was not designed with using multiple instances of a game in mind?

**Comment by elishacloud** [comment]
@onetwothreefive, I don't own Final Fantasy XI.  It may be the only one that I don't own...  But, are you sure this is and issue with d3d8to9?  I tried d3d8to9 with other games (like Silent Hill 2) and did not see this issue.  Can you try this without d3d8to9 and see if you still have the same issue?

**Comment by onetwothreefive** [comment]
It definitely does not happen without, I used to use dgVoodoo2 before (have to use something of the kind to get Optimus laptops to run it on dGPU), I swapped to DxWrapper since it works better, and it only started happening after I swapped. It also does not happen if not using either of them. I also told a friend about DxWrapper, and after he swapped, he ran into the same issue.

Also, something I've discovered since then that does kind of get around it is terminating the game via task manager - if I end a process that way, any other running ones will keep running.

**Comment by elishacloud** [comment]
Can you zip up and attach all the DxWrapper files you are using, including the stub file and the ini file?

**Comment by onetwothreefive** [comment]
[DxWrapperFFXI.zip](https://github.com/elishacloud/dxwrapper/files/3969802/DxWrapperFFXI.zip)

There, it should be the latest version, and only changes done to the ini file is setting the d3d8to9 flag to 1.

**Comment by elishacloud** [comment]
Sorry for the delay in responding.  Try adding the following line into the dxwrapper.ini file:

```ini
ResetScreenRes = 0
```

By default, dxwrapper will reset the resolution of the computer on exit.  Disabling this may solve the issue.

**Comment by elishacloud** [comment]
Closing this case.  If it is still an issue you can reopen it.
