### ISSUE TITLE
Gangsters Organized Crime does not work when you have multiple monitors attached

### ISSUE THREAD

**Issue by hozy2b** [elishacloud/dxwrapper#57]
Hi Elishacloud!

I've a problem with this fix windows 10... 
I've followed your instructions to fix gangster but all the buttons are blank and in game the speed mouse is broken .. like  '' freeze unfreeze ''. 
Have i missing anything during the install ..??

I do: download the game, copy the patch 3 files (dsound.dll ; dxwrapper.dll ; dxwrapper.ini ) in game factory near gangster.exe (C:/progamefile(x86)/COG/Game/Gangster ) and run it with disable administrator.

Is it normal that there are not the same files patch in game factory to overwrite ?
I've disable G-SYNC too with panel Nvidia but it's the same :/ ...

Thanks to your help!

**Comment by elishacloud** [comment]
Can you try with this update?  If it still happens let me know and I can make a debug build to try and figure out what is happening.

Testing build: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/5289336/dxwrapper.zip)

**Comment by profplum700** [comment]
I'm having this issue with the black screen too. I swear I played this game 2 years ago and it worked with your fix then.

I see this as the game's little taskbar thumbnail if that is of any use:
![image](https://user-images.githubusercontent.com/13546520/98878059-e796e200-2479-11eb-816f-cd640f1e1992.png)

Actually I just found out what it is. I have multiple monitors and that was causing the issue. When I disconnect them and use my laptop's screen, it all loads up just fine 🤦‍♂️

**Comment by elishacloud** [comment]
Yeah, I have not added good support for multiple monitors.  It could be that the game does not support multiple monitors or that there is a bug with dxwrapper when using multiple monitors.  I will take a look at this later.

**Comment by elishacloud** [comment]
I just posted an update patch that should address this issue.  You can see the update here:  [Gangsters Organized Crime patch](https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime)

**Comment by elishacloud** [comment]
This issue should be fixed with the latest release here:  https://github.com/elishacloud/dxwrapper/wiki/Gangsters-Organized-Crime
