### ISSUE TITLE
AF doesn't work with Dark Age Of Camelot

### ISSUE THREAD

**Issue by G-DannY** [elishacloud/dxwrapper#60]
Hi,

first thank you for your work.

When you plan to push next release? I'm really interested in the anisotropic filtering commit.

Thanks

**Comment by elishacloud** [comment]
I am not sure when I will release the next update.  There are still a few things I wanted to do before releasing.  There was a crash on two games that never happened before that I wanted to troubleshoot.  But I have been busy with other project recently.

Anyways, here is the latest build.  It is pretty stable:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/4227631/dxwrapper.zip)

**Comment by G-DannY** [comment]
Wow, nice! Thanks.

How can i force AF in the settings? Need to put 1 or AF level (4, 8 16)?

Because it seems to not work for me on d3d9

**Comment by elishacloud** [comment]
> How can i force AF in the settings? Need to put 1 or AF level (4, 8 16)?

1 = highest your video card can support.  2, 4, 8, or 16 = specific AF settings you want to configure.

> Because it seems to not work for me on d3d9

Interesting.  I don't actually change the texture filtering, but just enable the AF option.  I can do an update that actually changes the texture filtering in addition to enabling the AF option.

Have you tried using the AF option in your video card's Control Panel?

![image](https://user-images.githubusercontent.com/25625456/74996549-b7e60c80-5408-11ea-8497-eb795796d11f.png)

**Comment by G-DannY** [comment]
uhm, seems that i cannot force AF with my control panel (intel hd620) in the game i play (Dark Age Of Camelot). 
I set it to forced 16x in intel control panel but in game there is no change... I also set 16x in your dxwrapper but no change.

only way i found to force it succesfull is using another kind of d3d9 wrapper (dgvodoo), but it has kinda horrible performance. (with or without AF)...

could you try to code the AF forcing in your awesome wrapper?

Thanks :D

**Comment by mirh** [comment]
Because this is about compatibility and not enhancements. 
Graphics cards control panels are already good enough for that.

**Comment by elishacloud** [comment]
This issue may be related to a fix I put in here: [Fix AF with multi-stage textures](https://github.com/elishacloud/dxwrapper/commit/aaa9d496e10d7c9c7e8c050a78e0a12fe4e99f9f).

Can you try with the latest build and see if that helps:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/11205996/dxwrapper.zip)

**Comment by elishacloud** [comment]
Closing this issue.  You can reopen it if the issue still exists.
