### ISSUE TITLE
Star Trek Armada crashes immediately after Start on Windows 10

### ISSUE THREAD

**Issue by Aysem22** [elishacloud/dxwrapper#62]
Hey there,

first of all many Thanks for your great work!

I've an issue with Star Trek Armada 1 under Windows 10. I can't start the Program. When I start the Game, I see the little Armada-SplashScreen in the middle. Then the whole Screen gets Black with a (big-scaled) waiting Cursor (Circle) in the middle. Then it immediately returns to Desktop. Program no more running according to Task Manager.

Windows 10, 1909
GeForce GTX 1070
AMD Ryzen 9 3900X
32 GB RAM
Sound Blaster AE-7
One G-sync Monitor plugged in via Displayport at 144Hz
Drivers are the latest

I installed Armada, then official Patch 1.2, then Patch 1.3 and your dxwrapper. I tried different Folders and different dxwrapper-Versions. All didn't work. Have you any Idea, how to get the Game running?

Here is the log-file (dxwrapper-armada.log):
17948 08:08:50.618 Starting DxWrapper v1.0.6341.21
17948 08:08:50.618 Gigabyte Technology Co., Ltd. X470 AORUS ULTRA GAMING Default string (Desktop)
17948 08:08:50.618 Gigabyte Technology Co., Ltd. X470 AORUS ULTRA GAMING-CF x.x (Desktop)
17948 08:08:50.618 NVIDIA GeForce GTX 1070
17948 08:08:50.619 Windows 10 64-bit (10.0.18362) 
17948 08:08:50.619 "armada.exe" (PID:10252)
17948 08:08:50.625 Disabling High DPI Scaling...
17948 08:08:50.625 Loaded library: user32.dll
17948 08:08:50.625 Loaded library: shcore.dll
17948 08:08:50.625 Loading 'ddraw.dll'...
17948 08:08:50.625 Hooking ddraw.dll APIs...
17948 08:08:50.625 Enabling DDrawCompat
17948 08:08:50.625 Enabling ddraw wrapper
17948 08:08:50.625 Process path: C:\Games\Armada\armada.exe
17948 08:08:50.625 Loading DDrawCompat from C:\Games\Armada\dxwrapper.dll
17948 08:08:50.626 Loaded library: uxtheme.dll
17948 08:08:50.626 DDrawCompat v0.2.1 loaded successfully
17948 08:08:50.627 DxWrapper loaded!
17948 08:08:50.627 dd_DirectDrawCreateEx
17948 08:08:50.627 Redirecting 'DirectDrawCreateEx' ...
17948 08:08:50.627 Installing DirectDraw hooks
17948 08:08:50.700 Installing GDI hooks
17948 08:08:50.705 Installing registry hooks
17948 08:08:50.705 Finished installing hooks
17948 08:08:50.706 Creating device m_IDirectDrawX::m_IDirectDrawX(009FB950) v7
17948 08:08:51.327 m_IDirectDrawX::~m_IDirectDrawX(009FB950) deleting device!
17948 08:08:51.328 Loaded library: dwmapi.dll
17948 08:08:51.334 Redirecting 'DirectDrawCreateEx' ...
17948 08:08:51.335 Creating device m_IDirectDrawX::m_IDirectDrawX(009FBCF8) v7
17948 08:08:51.335 Creating device m_IDirect3DX::m_IDirect3DX(085A9FB0) v7
17948 08:08:51.335 m_IDirect3DX::ResolutionHack Found loaded dll: 'd3dim700.dll'
17948 08:08:52.013 Loaded library: winmm.dll
17948 08:08:52.015 Creating device m_IDirectDrawSurfaceX::m_IDirectDrawSurfaceX(041FE608) v7
17948 08:08:52.015 Creating device m_IDirectDrawColorControl::m_IDirectDrawColorControl(085452F8)
17948 08:08:52.015 Creating device m_IDirectDrawSurfaceX::m_IDirectDrawSurfaceX(084F9768) v7
17948 08:08:52.015 Creating device m_IDirectDrawSurfaceX::m_IDirectDrawSurfaceX(084F9EB8) v7

And 2nd the other log-file (dxwrapper-splash.log)
10520 08:08:48.524 Starting DxWrapper v1.0.6341.21
10520 08:08:48.524 Gigabyte Technology Co., Ltd. X470 AORUS ULTRA GAMING Default string (Desktop)
10520 08:08:48.524 Gigabyte Technology Co., Ltd. X470 AORUS ULTRA GAMING-CF x.x (Desktop)
10520 08:08:48.524 NVIDIA GeForce GTX 1070
10520 08:08:48.524 Windows 10 64-bit (10.0.18362) 
10520 08:08:48.524 "splash.exe" (PID:2180)
10520 08:08:48.529 Disabling High DPI Scaling...
10520 08:08:48.529 Loaded library: user32.dll
10520 08:08:48.529 Loaded library: shcore.dll
10520 08:08:48.529 Loading 'ddraw.dll'...
10520 08:08:48.529 Hooking ddraw.dll APIs...
10520 08:08:48.529 Enabling DDrawCompat
10520 08:08:48.529 Enabling ddraw wrapper
10520 08:08:48.529 Process path: C:\Games\Armada\splash.exe
10520 08:08:48.529 Loading DDrawCompat from C:\Games\Armada\dxwrapper.dll
10520 08:08:48.530 Loaded library: uxtheme.dll
10520 08:08:48.530 DDrawCompat v0.2.1 loaded successfully
10520 08:08:48.530 DxWrapper loaded!
10520 08:08:48.530 dd_DirectDrawCreate
10520 08:08:48.530 Redirecting 'DirectDrawCreate' ...
10520 08:08:48.530 Installing DirectDraw hooks
10520 08:08:48.601 Installing GDI hooks
10520 08:08:48.605 Installing registry hooks
10520 08:08:48.605 Finished installing hooks
10520 08:08:48.606 Creating device m_IDirectDrawX::m_IDirectDrawX(004FAA88) v1
10520 08:08:48.606 Creating device m_IDirectDrawX::m_IDirectDrawX(004FA470) v2
10520 08:08:48.606 m_IDirectDrawX::~m_IDirectDrawX(004FA470) deleting device!
10520 08:08:48.606 Loaded library: winmm.dll
10520 08:08:48.606 Creating device m_IDirectDrawSurfaceX::m_IDirectDrawSurfaceX(08D54968) v1
10520 08:08:48.606 Creating device m_IDirectDrawSurfaceX::m_IDirectDrawSurfaceX(08D54B08) v3
10520 08:08:48.606 m_IDirectDrawSurfaceX::~m_IDirectDrawSurfaceX(08D54B08) deleting device!
10520 08:08:48.606 Creating device m_IDirectDrawSurfaceX::m_IDirectDrawSurfaceX(08D54B08) v4
10520 08:08:48.606 m_IDirectDrawSurfaceX::~m_IDirectDrawSurfaceX(08D54B08) deleting device!
10520 08:08:48.607 dd_DirectDrawCreateEx
10520 08:08:48.607 Redirecting 'DirectDrawCreateEx' ...
10520 08:08:48.608 Creating device m_IDirectDrawX::m_IDirectDrawX(004FACF8) v7
10520 08:08:48.608 m_IDirectDrawX::~m_IDirectDrawX(004FACF8) deleting device!
10520 08:08:48.608 m_IDirectDrawX::~m_IDirectDrawX(004FA3A0) deleting device!
10520 08:08:48.608 m_IDirectDrawSurfaceX::~m_IDirectDrawSurfaceX(08D54968) deleting device!
10520 08:08:50.582 Quiting DxWrapper
10520 08:08:50.582 Detaching DDrawCompat
10520 08:08:50.590 DDrawCompat detached successfully
10520 08:08:50.590 Unloading libraries...
10520 08:08:50.590 Reseting screen resolution
10520 08:08:50.605 Reseting font smoothing
10520 08:08:50.607 DxWrapper terminated!

**Comment by Aysem22** [comment]
Sorry to bother again, but I fixed it myself. Problem was Gsync. It has to be switched to a fixed Refreh Rate in the Nvidia Control Panel. Then the Game starts and is playable.

Please close this Issue.

**Comment by mirh** [comment]
You can do it yourself, though having VRR working would also seem within the scope of the project.
