### ISSUE TITLE
Interstate 82

### ISSUE THREAD

**Issue by Bomberman82** [elishacloud/dxwrapper#63]
Pls, when anyone have a chance to explain if it works with Interstate82 on win10 64Bit than pls could someone help me pls. I try anything what i can do make it possible, rename the .exe, install a virtualbox with all Windows System from 98 to XP nothing but nothing got works on it. So pls when it is possible with the wrapper i would appriciate that. 

Thx in Front

Dear Bomberman82

**Comment by elishacloud** [comment]
I have looked into Interstate '82 before.  I believe it is something to do with the sound that causes the crash.  So far, while this module can wrap the DirectSound APIs I really have not looked into correcting issues like this.  But I hope to get more into the DirectSound APIs at some point soon.

**Comment by elishacloud** [comment]
The game should be working with this update:  [dxwrapper.zip](https://github.com/user-attachments/files/18120814/dxwrapper.zip)

**Comment by elishacloud** [comment]
This is fixed in the latest release.  You can reopen it if you are still having issues.
