### ISSUE TITLE
Assassins Creed II

### ISSUE THREAD

**Issue by doctorix** [elishacloud/dxwrapper#68]
Is it possible that you can pull the graphic files, etc. from the Ezio Edition of Assassins Creed II off the console versions and make an enhanced version for the pc version like you did for Silent Hill 2?

**Comment by elishacloud** [comment]
It is possible for that to be done, but it is very unlikely that I will have time to do that.  Currently, I just have too many things going on and not enough time.

**Comment by doctorix** [comment]
Alright, take your time. Do you know of anyone I can request this besides yourself?

**Comment by mirh** [comment]
Seriously, there's no point. We aren't talking about a comically broken game. 
And the ezio collection is [basically](https://www.youtube.com/watch?v=XcRKnvK-Rx0) just a port of the pc version. Maybe some shader is better (not much that you couldn't achieve with reshade then), but then you also have [lows](https://www.oneangrygamer.net/2016/11/assassins-creed-ezio-collection-graphics-comparisons-are-embarrassing/17059/). 
The AC3 remaster [if any](https://www.eurogamer.net/articles/digitalfoundry-2019-assassins-creed-3-remaster-analysis) stepped up the game, but that's another story. 

https://www.nexusmods.com/assassinscreedii
https://www.moddb.com/games/assassins-creed-ii
See here for some mods, but idk about any supportive community behind like it could be for skyrim, or gta. And certainly if we are still stuck to the "having to use texmod" phase we are still kinda far.

**Comment by elishacloud** [comment]
Closing as not planned.
