### ISSUE TITLE
Rayman 2 incompatibility with Dd7to9 (for Reshade)

### ISSUE THREAD

**Issue by deton24** [elishacloud/dxwrapper#71]
Current stable version of DXwrapper (v1.0.6334.21) doesn't work with Rayman 2 (DX6 in ubi.ini).
To make it work read here:
https://www.pcgamingwiki.com/wiki/Rayman_2:_The_Great_Escape#Game_runs_in_windowed_mode_.28fullscreen_fix.29
For reference:
https://github.com/elishacloud/dxwrapper/issues/35#issuecomment-500131861
edit. I'm not sure whether I tested all versions with XP SP2 compatibility mode, though.

Haven't tested this build yet (I just discovered it):
https://github.com/elishacloud/dxwrapper/issues/60#issuecomment-588491511

When you make the wrapper work, setting Dd7to9 =1 shows black screen in small window with sound playing in background.
Sorry I just read it now:
_It supports all 7 versions of ddraw 2D APIs, however most of the 3D APIs are not implemented yet_

When you set Force32bitColor = 1 it shows black and white 2D loading screens, but is frozen on those screens when it should display 3D main menu with sound in background.

Dd7to9 =1 is the only way to make DXGI.dll reshade to work, and Reshade is injected successfully during testing, showing proper message.

Force32bitColor = 1 fixes some FPS drops with overlays enabled, but normally also show in black and white, or causes displaying some random glitched elements instead of loading screens.

dgVoodoo successfully injects Reshade in DX6, but causes more FPS dips (dxWrapper is also not completely deprived of them, though).
nGlide works the best with this game, but cannot be used with newly released complete texture mod, because of Glide API texture size limitation:
https://raymanpc.com/forum/viewtopic.php?f=89&t=74254

Tested with and without Reshade and with fullscreen = 0 and 1.

edit.
Dege from dgVoodoo repaired literally all DX6 (and Glide) 30 FPS lock issues by modifying the game renderer so there is absolutely no rush with implementing Dd7to9 to dxwrapper in this game.
https://www.vogons.org/viewtopic.php?p=855828#p855828

**Comment by elishacloud** [comment]
Yeah, Raymond 2 uses 3D APIs and I have not implemented those yet.  I have not had much time recently, but I hope to get those implemented later.

**Comment by elishacloud** [comment]
_Rayman 2_ should be fully working with Dd7to9 now.  Here is the latest build:  [dxwrapper.zip](https://github.com/user-attachments/files/18107585/dxwrapper.zip)

You may need to update your `ubi.ini` file.  Below is what I have:
```ini
[Rayman2]
GLI_DllFile=GliDX6
GLI_Dll=DirectX6
GLI_Driver=display
GLI_Device=Direct3D HAL
GLI_Mode=1 - 1024 x 768 x 16
Language=English
ParticuleRate=High
```

**Comment by elishacloud** [comment]
This is fixed with the latest release.  You can reopen it if you are still having issues.
