### ISSUE TITLE
Request | Add an option to choose which CPU to use

### ISSUE THREAD

**Issue by JaegerFox** [elishacloud/dxwrapper#76]
in classic games it is recommended to use single core, and it would be nice to assign a specific one to give it priority...

**Comment by elishacloud** [comment]
This feature already exists.  It is called `SingleProcAffinity`.  Just set this to the CPU you want to use.  For example, if you set this to `2` then it will assign the process to use the second CPU.  If you set this to a CPU that does not exist then it will just use the last CPU.

See more details in the [wiki](https://github.com/elishacloud/dxwrapper/wiki/Configuration#compatibility).

**Comment by JaegerFox** [comment]
Really? I thought it only activated the use of the first CPU core, apparently the wiki is updated and better explained
Thank you-
