### ISSUE TITLE
"Convenience information" logging

### ISSUE THREAD

**Issue by mirh** [elishacloud/dxwrapper#77]
So.. For encyclopedic purposes (but sometimes even for practical ones, like for example the famous <dx7 resolution limits) over at PCGW we need to determine which API version games use. 
But as far as I am being told, logging here only gets you as far as this
```
9412 00:28:14.535 Creating device m_IDirectDrawX::m_IDirectDrawX(03528A70) v1
9412 00:28:14.535 Creating device m_IDirectDrawX::m_IDirectDrawX(03528CF0) v4
```
or
```
7060 00:31:29.234 Creating device m_IDirectDrawX::m_IDirectDrawX(0061B1F0) converting device from v1 to v9
m_IDirectDrawSurfaceX::m_IDirectDrawSurfaceX(0066E978) converting device from v4 to v9
```
(and let's avoid mentioning the mess that associating an interface version to a dx release is)

Now, I really absolutely am not saying this should even be within the purposes of this project (perhaps there is already some tool for this), though from the top of my mind I couldn't come up with any other place as comprehensive and potentially related.

**Comment by elishacloud** [comment]
> (and let's avoid mentioning the mess that associating an interface version to a dx release is)

Yes, you are right.  I am just logging the interface version not the DirectX version.  So far I am not actually sure how to get the DirectX version of DirctDraw applications.  Anyways, I will try and make the logs more clear on this point.  Thanks.

**Comment by elishacloud** [comment]
Closing this issue.  The latest release changes the logs to try and make this more clear.
