### ISSUE TITLE
"Please enter an integer." error - SimCity Classic

### ISSUE THREAD

**Issue by MadeInDutch** [elishacloud/dxwrapper#78]
I have a 64-Bit Windows 10 laptop on which I play SimCity Classic. Because it wouldn't load or save any cities, I downloaded this patch. Thankfully, it mostly seems to work just fine, with one massive exception: after I save a given city, the next time the yearly budget comes up, all the values come up blank. When I try to continue by pressing "Go with these figures", I get a pop-up saying "Please enter an integer.". The one Reddit thread I found which had the same problem had no solutions but did mention that he installed your patch, and that the error only came up after he saved his city, which is also what happened to me. It's also worth mentioning that the error doesn't come up when I activate the Auto-Budget option. Hopefully, the patch can be fixed.

**Comment by MadeInDutch** [comment]
I realise this was posted only 15 days ago, but I'm just curious if there's any sort of progress on solving this bug, or at least if you're too busy to do this right now. Hopefully, the problem can be solved and I can play this game I've been dying to properly.

**Comment by elishacloud** [comment]
The issue with SimCity Classic is with one of the dlgcom API's.  I have not had time to troubleshoot this yet, but the `HandleExceptions` option is able to handle this error and allow you to play the game.

Try using this update. Just unzip all these files into the SimCity Classic folder, overwriting any existing file: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/4976911/dxwrapper.zip)

**Comment by elishacloud** [comment]
Ok, if I disable Auto-Budget then I see the same issue.  It is possible that something is not getting saved correctly.  I will need to look into this more.

**Comment by elishacloud** [comment]
I think I fixed the issue.  I don't know if there was more than one version of SimCity Classic released.  I am using version 2.0.  The fix will likely only work on this version.  Just unzip this into the SimCity folder overwriting all files.

Here is the update:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/4977172/dxwrapper.zip)

**Comment by MadeInDutch** [comment]
Thanks a lot!

26 Tem 2020 Paz 07:53 tarihinde Elisha Riedlinger <notifications@github.com>
şunu yazdı:

**Comment by MadeInDutch** [comment]
It works!

Kanal Q <civancor@gmail.com>, 26 Tem 2020 Paz, 10:33 tarihinde şunu yazdı:

**Comment by elishacloud** [comment]
Glad it is working for you!
