### ISSUE TITLE
can you update configuration guide ?

### ISSUE THREAD

**Issue by pm67190** [elishacloud/dxwrapper#80]
hello and thank you very much for your works

can you update configuration guide ? to reflect new release fonctions

**Comment by elishacloud** [comment]
Yes, it's on my list.  But I probably won't be able to do it until later this month.

**Comment by pm67190** [comment]
hello 

did you have a new version 

of dxwrapper ? for test ^^ with new features 

thank you in advance for your work

**Comment by elishacloud** [comment]
The configuration guide has been updated for basic settings.

**Comment by elishacloud** [comment]
The [Configuration](https://github.com/elishacloud/dxwrapper/wiki/Configuration) wiki has been updated with all options.  Closing this issue.
