### ISSUE TITLE
ddraw compat not work anymore

### ISSUE THREAD

**Issue by JaegerFox** [elishacloud/dxwrapper#83]
In the last version the module ddraw compat dont work, in the log file the file ddraw.dll its loaded but not these functions

**Comment by elishacloud** [comment]
DDrawCompat works ok for me on the games I tested.  Can you tell me what game you are testing this with?  Also, please attach your ini file and log file.

**Comment by JaegerFox** [comment]
[dxwrapper-metal gear solid.log](https://github.com/elishacloud/dxwrapper/files/5092364/dxwrapper-metal.gear.solid.log)

**Comment by elishacloud** [comment]
These are all logs from DDrawCompat:

```txt
3988 14:12:07.759 Loading DDrawCompat from E:\Games\MGS1\dxwrapper.dll
3988 14:12:07.761 Loaded library: uxtheme.dll
3988 14:12:07.761 DDrawCompat v0.2.1 loaded successfully
3988 14:12:07.761 DxWrapper loaded!
3988 14:12:08.344 Installing DirectDraw hooks
3988 14:12:08.358 Installing GDI hooks
3988 14:12:08.364 Installing registry hooks
3988 14:12:08.365 Finished installing hooks
3988 14:12:08.866 Loaded library: winmm.dll
3988 14:12:08.880 GDI used DC cache size: 1
```

DDrawCompat is loading correctly into this game.

**Comment by JaegerFox** [comment]
Yes but the game dont start with the functions, what I mean, in the previous versions the game started in full screen without borders, now it starts in window mode with borders (as if DDrawCompat did not work) also the performance is lower

**Comment by JaegerFox** [comment]
Here with DDrawingCompat in the previous version of DxWrapper
![IMG_20200818_173553~01](https://user-images.githubusercontent.com/29095345/90572738-667dc680-e17a-11ea-9341-6f08cd0a3670.jpg)

And the last version
![IMG_20200818_173450](https://user-images.githubusercontent.com/29095345/90572744-68478a00-e17a-11ea-9ef2-c19ba719db17.jpg)

**Comment by elishacloud** [comment]
Try setting `EnableDdrawWrapper         = 1`

**Comment by JaegerFox** [comment]
Enabling `EnableDdrawWrapper` fixed the problem, why that change? is it a bug or is it how it should work?

**Comment by elishacloud** [comment]
This is correct functionality.  `EnableDdrawWrapper` has an option to remove the frame from fullscreen windows.

**Comment by JaegerFox** [comment]
No... Forgive but no, the game without any Wrapper, in high resolutions the performance is bad, if the DxWrapper with `DDrawCompat21 = 1` or any other option in the previous versions the performance improves and the borders are not shown, only in this version if I enable `DDrawCompat` the game continues with poor performance as if  dont have the Wrapper enabled.
