### ISSUE TITLE
DXWrapper not fixing an older DDraw DX3-DX7 application...

### ISSUE THREAD

**Issue by Archangel35757** [elishacloud/dxwrapper#84]
Elisha, I apologize for creating this issue ticket but I have no other way to contact you via github.  And I need your assistance to figure out why DXwrapper is not patching this older application which used DX3-DX7 to create the render device.  Please contact me:  archangel35757 (at) yahoo (dot) com.

Your assistance is greatly appreciated.

**Comment by elishacloud** [comment]
Closing issue.
