### ISSUE TITLE
[Star Trek: Starfleet Command III] dxwrapper error: Unable to retrieve back buffer

### ISSUE THREAD

**Issue by GhostCoder22** [elishacloud/dxwrapper#94]
Hi. I've been trying but failing to run Star Trek: Starfleet Command III in Windows 10 64-bit. The game in question was originally designed to run on Windows 98/ME/XP with DirectX 8.1 or higher but even though the game correctly plays the credits as well as the intro movie, the screen itself flashes two or three times before turning completely blank where the game's menu should appear and a **Debug Window** pops up with the error **Someone threw the following string: Unable to retrieve back buffer**. I've extracted **d3d8.dll**, **dxwrapper.dll** and **dxwrapper.ini** in the games base folder. I think I correctly modified **dxwrapper.ini** for this game, but I'm not sure which is why I'm attaching it to this report in the hopes of a compatibility fix as well as the **dxwrapper-sfc3.log** files in a zip. The game itself reports no errors. Please help!

[dxwrapper-sfc3.zip](https://github.com/elishacloud/dxwrapper/files/5505936/dxwrapper-sfc3.zip)

**Comment by elishacloud** [comment]
I only have Star Trek: Starfleet Command 1.  I don't have 2 or 3.  Try enabling only the following, and disabling everything else:

```ini
D3d8to9                    = 1
SingleProcAffinity         = 1
```

**Comment by BigGammer** [comment]
> 
> 
> I only have Star Trek: Starfleet Command 1. I don't have 2 or 3. Try enabling only the following, and disabling everything else:
> 
> ```ini
> D3d8to9                    = 1
> SingleProcAffinity         = 1
> ```

Doesn't work. Same results every time. I've even tried enabling and disabling Windows 10's **Windows XP (Service Pack 3) Compatibility Mode** but left **Reduced color mode: 16-bit (65535 Color)** on since the game refuses to run in 32-bit color mode.

**NOTE: Compatibility Mode** must be set to **Windows XP (Service Pack 2)** or ** Windows XP (Service Pack 3)** if enabled, otherwise this game refuses to run on Windows 10.

**Comment by elishacloud** [comment]
I don't have Star Trek: Starfleet Command III to test.  However, I just posted an update patch for Star Trek Armada 1 that might work here.  From what I have seen online, the engine for Star Trek: Starfleet Command III is similar to the one in Star Trek Armada 1.  You can see if this update helps:  [Star Trek Armada 1 patch](https://github.com/elishacloud/dxwrapper/wiki/Star-Trek-Armada-1)

**Comment by mirh** [comment]
> NOTE: Compatibility Mode must be set to Windows XP (Service Pack 2) or Windows XP (Service Pack 3) if enabled

If you feel like wanting to waste some time, you could investigate inside the [compatibility administrator](https://learn.microsoft.com/en-us/windows-hardware/get-started/adk-install) which of the fixes included with those modes make the difference. 

![immagine](https://user-images.githubusercontent.com/9366725/232308143-67175b2a-4af2-4b39-9740-62d61e36406f.png)

**Comment by elishacloud** [comment]
You can try with this update.  I don't have Star Trek: Starfleet Command III so I cannot test it.  But this update works with Star Trek: Armada 1.  This converts the menu to using GDI and converts the game play to using Direct3D9.

Here is the new update: [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/12306900/dxwrapper.zip)

**Comment by elishacloud** [comment]
Ok, try it with this update.  I think it should be fixed now:  [dxwrapper.zip](https://github.com/elishacloud/dxwrapper/files/14625856/dxwrapper.zip)

**Comment by elishacloud** [comment]
Closing this issue.
