### ISSUE TITLE
Possible to add deadzone/antideadzone settings per-stick or axis for dinput/8?

### ISSUE THREAD

**Issue by instinctualjealousy** [elishacloud/dxwrapper#97]
XInputPlus is overkill for simply setting deadzones especially when the native gamepad support of a game works fine as is, plus it's predicated on having a real or virtual xinput compatible pad, so people with dinput-only pads are left out. There are a few older games out there that have absolutely or nearly no deadzone (Daytona USA Deluxe, Crazy Taxi 3, Starsky & Hutch for example) and no way to set it in-game, which results in twitchy controls on controllers that have no or minimal firmware or driver deadzone.

I currently use [https://github.com/d-b/gurumin-pad](url), but it has no configuration whatsoever. I was able to make multiple DLLs by figuring out the PROJECT_DEADZONE value in hex, so I didn't have to set up a build environment for such a tiny plugin. This does work for the most part, but I figured it'd be a neat feature to have in dxwrapper.

ThirteenAG's NFS widescreen fixes do include a deadzone-setting-by-percentage, if the implementation can be worked with.

**Comment by mirh** [comment]
Gurming pad has sources though. 
Can't you just try to set a different `PROJECT_DEADZONE` value?

**Comment by instinctualjealousy** [comment]
Of course. Didn't bother setting up a compile environment though just for
that when I could set the project deadzone value in hex. It'd just be nicer
to have more fine-grained control and have it built in dxwrapper. It's
already able to do a lot for 3D and a decent bit for sound. dinputto8 is a
godsend, though. My personal solution is usually a 15-20% deadzone
gurumin-pad and if the game is dinput I use dinputto8 to make it work, and
the vast majority of games work with this.

It'd be much better to fork it over into a generic deadzone wrapper with
ini configuration, but that's beyond me. My brother could probably do it,
but he's not familiar with Windows APIs though.

I don't think it's beyond the scope of this project, but that isn't up to
me to call. I do think if something can be done better, it's worth doing,
though. There's so many amazing graphics wrappers these days but not near
as much for input, and what's out there has meaningful ways to be improved
or iterated on.

**Comment by elishacloud** [comment]
Thanks for the suggestion!  However, I don't have any plans to do this.  Closing this issue.
