### ISSUE TITLE
Possible to remap buttons/axes to other buttons/axes in dinput/8?

### ISSUE THREAD

**Issue by instinctualjealousy** [elishacloud/dxwrapper#98]
In games like Midnight Club 2, certain menu controls are hardcoded in the game and not configurable by the user. The ability to remap these hardcoded controls to better-suited buttons would be useful. This would also be useful for games with controls that are outright hardcoded with no configuration ability. XInputPlus is able to do this, but it's converting to XInput which leaves people out who are using dinput pads without some virtual controller driver.

Anyway, just want to thank you for this delightful wrapper to rule them all.

**Comment by elishacloud** [comment]
Thanks for the suggestion!  However, I don't have any plans to do this.  You could use [Xidi](https://github.com/samuelgr/Xidi) for this, I think.  Closing this issue.
