### ISSUE TITLE
Warcraft III

### ISSUE THREAD

**Issue by avindra** [elishacloud/dxwrapper#99]
Warcraft 3 (Frozen Throne) and (Reign of Chaos) are working! (I was surprised to learn this game uses DirectX 8 before it's `1.31` patch).

`WINEDLLOVERRIDES="d3d8.dll=n" WINE_PREFIX=~/.wine32 DXVK_HUD=full wine war3.exe`

![thro](https://user-images.githubusercontent.com/126848/100309118-192ea380-2f78-11eb-9a04-a42c2c93b871.jpg)

`WINEDLLOVERRIDES="d3d8.dll=n" WINE_PREFIX=~/.wine32 DXVK_HUD=full wine war3.exe -classic`

![roc](https://user-images.githubusercontent.com/126848/100309175-3f544380-2f78-11eb-9d3b-b09c5295ec42.jpg)

This are no issues to report :sweat_smile:. Thought I'd log something as`dxwrapper` proved critical here, especially since the _OpenGL_ backend is so slow and has lighting corruption problems when the window gets resized.

Being able to use the DirectX backend for this game on Linux is a newly possible thing. Didn't think I would ever see the day, but we just had to wait a decade or so! Thanks for your work on this project.

Here is the DXVK side of this:

https://github.com/doitsujin/dxvk/issues/1808#issuecomment-734043638

**Comment by avindra** [comment]
It's not a real issue so I'm closing this :+1:

**Comment by mirh** [comment]
`d3d8to9` is probably a project more specific to your use case. 
Wined3d shouldn't be that bad for old games though.

**Comment by avindra** [comment]
The performance of wined3d seems to be fraught with issues (can't blame them, it's still pretty new). Although, I am not sure if it is just falling back to OpenGL, which has worked since as early as 2006. That's the problem with this game on Linux. You will never hit above 30fps, and it drops below 14fps typically. That's even with high end AMD+NVIDIA hardware. 

Not a problem anymore... using `d3d8to9` now I am rendering it at 2560x1440@95hz. This makes the old game quite useful, and a good alternative to Warcraft III: Reforged. I think if your project offered that alone it would be a great service to game preservation efforts, but I can see it hooks into a whole bunch more :open_mouth:

**Comment by mirh** [comment]
??D3d8to9 is what dxwrapper uses to make the conversion, and if any it's this to have more "stuff" than you'd likely need. 
Also, wined3d is like possibly more than 20yo. 

I wonder if perhaps [this bug](https://bugs.winehq.org/show_bug.cgi?id=21204) regressed.

**Comment by avindra** [comment]
I understand, dxwrapper kind of "puts it together." I think I will still use it anyway, because I can also add Anti-aliasing to the game which was previously impossible.
